import { UAppTheme } from "../app-theme.slint";

import { UIconButtonTheme, UIconButtonThemes } from "icon-button.slint";


export struct UAlertTheme {
	background: brush,
	border-radius: length,
	border-width: length,
	border-color: brush,
	icon-image: image,
	icon-color: brush,
	icon-size: length,
	text-color: brush,
	text-font-size: length,
	horizontal-padding: length,
	vertical-padding: length,
	close-button-theme: UIconButtonTheme,
}


export global UAlertThemes {
    out property <UAlertTheme> info: {
        background: UAppTheme.primary-selected,
        border-radius: UAppTheme.radius-base,
        border-width: 1px,
        border-color: UAppTheme.primary,
        icon-image: @image-url("../assets/icons/info.svg"),
        icon-color: UAppTheme.primary,
        icon-size: UAppTheme.icon-size-base,
        text-color: UAppTheme.text,
        text-font-size: UAppTheme.font-size-base,
        horizontal-padding: UAppTheme.padding-big,
        vertical-padding: UAppTheme.padding-medium,
        close-button-theme: UIconButtonThemes.text-raw,
    };
    out property <UAlertTheme> success: {
        background: UAppTheme.success-selected,
        border-radius: UAppTheme.radius-base,
        border-width: 1px,
        border-color: UAppTheme.success,
        icon-image: @image-url("../assets/icons/circle-check.svg"),
        icon-color: UAppTheme.success,
        icon-size: UAppTheme.icon-size-base,
        text-color: UAppTheme.text,
        text-font-size: UAppTheme.font-size-base,
        horizontal-padding: UAppTheme.padding-big,
        vertical-padding: UAppTheme.padding-medium,
        close-button-theme: UIconButtonThemes.text-raw,
    };
    out property <UAlertTheme> warning: {
        background: UAppTheme.warning-selected,
        border-radius: UAppTheme.radius-base,
        border-width: 1px,
        border-color: UAppTheme.warning,
        icon-image: @image-url("../assets/icons/info.svg"),
        icon-color: UAppTheme.warning,
        icon-size: UAppTheme.icon-size-base,
        text-color: UAppTheme.text,
        text-font-size: UAppTheme.font-size-base,
        horizontal-padding: UAppTheme.padding-big,
        vertical-padding: UAppTheme.padding-medium,
        close-button-theme: UIconButtonThemes.text-raw,
    };
    out property <UAlertTheme> danger: {
        background: UAppTheme.danger-selected,
        border-radius: UAppTheme.radius-base,
        border-width: 1px,
        border-color: UAppTheme.danger,
        icon-image: @image-url("../assets/icons/circle-x.svg"),
        icon-color: UAppTheme.danger,
        icon-size: UAppTheme.icon-size-base,
        text-color: UAppTheme.text,
        text-font-size: UAppTheme.font-size-base,
        horizontal-padding: UAppTheme.padding-big,
        vertical-padding: UAppTheme.padding-medium,
        close-button-theme: UIconButtonThemes.text-raw,
    };
}
