import { UAppTheme } from "../app-theme.slint";


export struct UButtonThemeColors {
	background: brush,
	background-hover: brush,
	background-active: brush,
	background-checked: brush,
	background-disabled: brush,
	text-color: brush,
	text-color-hover: brush,
	text-color-active: brush,
	text-color-checked: brush,
	text-color-disabled: brush,
	border: brush,
	border-hover: brush,
	border-active: brush,
	border-checked: brush,
	border-disabled: brush,
}

export struct UButtonTheme {
	border-width: length,
	border-radius: length,
	content-spacing: length,
	padding-vertical: length,
	padding-horizontal: length,
	font-size: length,
	icon-size: length,
	base-colors: UButtonThemeColors,
	danger-colors: UButtonThemeColors,
}


export global UButtonThemes {
    out property <UButtonTheme> primary: {
        border-width: 1px * UAppTheme.scale-factor,
        border-radius: UAppTheme.radius-base,
        content-spacing: UAppTheme.spacing-base,
        padding-vertical: UAppTheme.padding-vertical,
        padding-horizontal: UAppTheme.padding-horizontal,
        font-size: UAppTheme.font-size-base,
        icon-size: UAppTheme.icon-size-base,
        base-colors: {
            background: UAppTheme.primary,
            background-hover: UAppTheme.primary-hover,
            background-active: UAppTheme.primary-active,
            background-checked: UAppTheme.primary,
            background-disabled: UAppTheme.border-secondary,
            text-color: Colors.white,
            text-color-hover: Colors.white,
            text-color-active: Colors.white,
            text-color-checked: Colors.white,
            text-color-disabled: UAppTheme.text-disabled,
            border-disabled: UAppTheme.border,
        },
        danger-colors: {
            background: UAppTheme.danger,
            background-hover: UAppTheme.danger-hover,
            background-active: UAppTheme.danger-active,
            background-checked: UAppTheme.danger,
            background-disabled: UAppTheme.border-secondary,
            text-color: Colors.white,
            text-color-hover: Colors.white,
            text-color-active: Colors.white,
            text-color-checked: Colors.white,
            text-color-disabled: UAppTheme.text-disabled,
            border-disabled: UAppTheme.border,
        }
    };
    out property <UButtonTheme> default: {
        border-width: 1px * UAppTheme.scale-factor,
        border-radius: UAppTheme.radius-base,
        content-spacing: UAppTheme.spacing-base,
        padding-vertical: UAppTheme.padding-vertical,
        padding-horizontal: UAppTheme.padding-horizontal,
        font-size: UAppTheme.font-size-base,
        icon-size: UAppTheme.icon-size-base,
        base-colors: {
            background-active: UAppTheme.primary-selected,
            background-checked: UAppTheme.primary-selected,
            text-color:  UAppTheme.text,
            text-color-hover: UAppTheme.primary-hover,
            text-color-active: UAppTheme.primary-active,
            text-color-checked: UAppTheme.primary,
            text-color-disabled: UAppTheme.text-disabled,
            border:  UAppTheme.border,
            border-hover: UAppTheme.primary-hover,
            border-active: UAppTheme.primary-active,
            border-checked: UAppTheme.primary,
            border-disabled: UAppTheme.border,
        },
        danger-colors: {
            background-active: UAppTheme.danger-selected,
            background-checked: UAppTheme.danger-selected,
            text-color: UAppTheme.danger,
            text-color-hover: UAppTheme.danger-hover,
            text-color-active: UAppTheme.danger-active,
            text-color-checked: UAppTheme.danger,
            text-color-disabled: UAppTheme.text-disabled,
            border: UAppTheme.danger,
            border-hover: UAppTheme.danger-hover,
            border-active: UAppTheme.danger-active,
            border-checked: UAppTheme.danger,
            border-disabled: UAppTheme.border,
        }
    };
    out property <UButtonTheme> filled: {
        border-radius: UAppTheme.radius-base,
        content-spacing: UAppTheme.spacing-base,
        padding-vertical: UAppTheme.padding-vertical,
        padding-horizontal: UAppTheme.padding-horizontal,
        font-size: UAppTheme.font-size-base,
        icon-size: UAppTheme.icon-size-base,
        base-colors: {
            background: UAppTheme.color-fill-tertiary,
            background-hover: UAppTheme.color-fill-secondary,
            background-active: UAppTheme.color-fill,
            background-checked: UAppTheme.primary-selected,
            text-color: UAppTheme.text,
            text-color-hover: UAppTheme.text,
            text-color-active: UAppTheme.text,
            text-color-checked: UAppTheme.primary,
            text-color-disabled: UAppTheme.text-disabled,
        },
        danger-colors: {
            background: UAppTheme.danger.with-alpha(0.1),
            background-hover: UAppTheme.danger-hover.with-alpha(0.3),
            background-active: UAppTheme.danger-active.with-alpha(0.4),
            background-checked: UAppTheme.danger-selected,
            text-color: UAppTheme.danger,
            text-color-hover: UAppTheme.danger-hover,
            text-color-active: UAppTheme.danger-active,
            text-color-checked: UAppTheme.danger,
            text-color-disabled: UAppTheme.text-disabled,
        }
    };
    out property <UButtonTheme> text: {
        border-radius: UAppTheme.radius-base,
        content-spacing: UAppTheme.spacing-base,
        padding-vertical: UAppTheme.padding-vertical,
        padding-horizontal: UAppTheme.padding-horizontal,
        font-size: UAppTheme.font-size-base,
        icon-size: UAppTheme.icon-size-base,
        base-colors: {
            background-hover: UAppTheme.color-fill-secondary,
            background-active: UAppTheme.color-fill,
            text-color: UAppTheme.text,
            text-color-hover: UAppTheme.text,
            text-color-active: UAppTheme.text,
            text-color-checked: UAppTheme.primary,
            text-color-disabled: UAppTheme.text-disabled,
        },
        danger-colors: {
            background-hover: UAppTheme.danger-hover.with-alpha(0.1),
            background-active: UAppTheme.danger-active.with-alpha(0.3),
            text-color: UAppTheme.danger,
            text-color-hover: UAppTheme.danger-hover,
            text-color-active: UAppTheme.danger-active,
            text-color-checked: UAppTheme.danger,
            text-color-disabled: UAppTheme.text-disabled,
        }
    };
}
