import { UAppTheme } from "../app-theme.slint";


export struct ULinkTheme {
	font-size: length,
	text-color: brush,
	text-color-hover: brush,
	text-color-active: brush,
	underline-spacing: length,
	underline-thickness: length,
}


export global ULinkThemes {
    out property <ULinkTheme> primary: {
        font-size: UAppTheme.font-size-base,
        text-color: UAppTheme.primary,
        underline-spacing: -1px,
        underline-thickness: 1px * UAppTheme.scale-factor,
    };
}
