import { UAppTheme } from "../app-theme.slint";

import { UIconButtonVariant } from "../widgets/icon-button.slint";
import { UButtonVariant } from "../widgets/button.slint";


export struct UModalTheme {
	blurred-background-color: brush,
	title-horizontal-padding: length,
	title-vertical-padding: length,
	content-horizontal-padding: length,
	content-vertical-padding: length,
	buttons-horizontal-padding: length,
	buttons-vertical-padding: length,
	buttons-spacing: length,
	title-level: int,
	close-button-variant: UIconButtonVariant,
	cancel-button-variant: UButtonVariant,
	accept-button-variant: UButtonVariant,
}


export global UModalThemes {
    out property <UModalTheme> default: {
        blurred-background-color: rgba(0, 0, 0, 0.2),
        title-horizontal-padding: UAppTheme.padding-big,
        title-vertical-padding: UAppTheme.padding-medium,
        content-horizontal-padding: UAppTheme.padding-big,
        content-vertical-padding: UAppTheme.padding-medium,
        buttons-horizontal-padding: UAppTheme.padding-big,
        buttons-vertical-padding: UAppTheme.padding-medium,
        buttons-spacing: UAppTheme.padding-medium,
        title-level: 6,
        close-button-variant: UIconButtonVariant.text,
        cancel-button-variant: UButtonVariant.default,
        accept-button-variant: UButtonVariant.primary,
    };
}
