import { UAppTheme } from "../app-theme.slint";
import { Palette } from "std-widgets.slint";


export struct UProgressTheme {
	progress-color: brush,
	background: brush,
	default-size: length,
	radius: length,
}


export global UProgressThemes {
    out property <UProgressTheme> primary: {
        progress-color: UAppTheme.primary,
        background: UAppTheme.color-fill-secondary,
        default-size: 10px * UAppTheme.scale-factor,
        radius: UAppTheme.radius-round,
    };
    out property <UProgressTheme> success: {
        progress-color: UAppTheme.success,
        background: UAppTheme.color-fill-secondary,
        default-size: 10px * UAppTheme.scale-factor,
        radius: UAppTheme.radius-round,
    };
    out property <UProgressTheme> warning: {
        progress-color: UAppTheme.warning,
        background: UAppTheme.color-fill-secondary,
        default-size: 10px * UAppTheme.scale-factor,
        radius: UAppTheme.radius-round,
    };
    out property <UProgressTheme> danger: {
        progress-color: UAppTheme.danger,
        background: UAppTheme.color-fill-secondary,
        default-size: 10px * UAppTheme.scale-factor,
        radius: UAppTheme.radius-round,
    };
}
