import { UAppTheme } from "../app-theme.slint";


export struct URadioTheme {
	text-color: brush,
	text-color-selected: brush,
	font-size: length,
	font-weight: int,
	font-weight-selected: int,
	border: brush,
	border-hover: brush,
	border-selected: brush,
	border-selected-hover: brush,
	background: brush,
	background-selected: brush,
	background-selected-hover: brush,
	main-circle-size: length,
	main-circle-border-width: length,
	dot-circle-size: length,
	dot-color: brush,
	radio-spacing: length,
	radio-text-spacing: length,
	radio-text-spacing: length,
}

export global URadioThemes {
    out property <URadioTheme> default: {
        text-color: UAppTheme.text,
        text-color-selected: UAppTheme.text,
        font-size: UAppTheme.font-size-base,
        border: UAppTheme.border,
        border-hover: UAppTheme.primary-hover,
        border-selected: UAppTheme.primary,
        border-selected-hover: UAppTheme.primary-hover,
        background: UAppTheme.bg-elevated,
        background-selected: UAppTheme.primary,
        background-selected-hover: UAppTheme.primary-hover,
        main-circle-size: UAppTheme.font-size-base,
        main-circle-border-width: 1px * UAppTheme.scale-factor,
        dot-circle-size: UAppTheme.font-size-base / 3,
        dot-color: Colors.white,
        radio-spacing: UAppTheme.spacing-base,
        radio-text-spacing: UAppTheme.spacing-base,
    };
}
