import { UAppTheme } from "../app-theme.slint";


export struct USelectTheme {
	background: brush,
	border-width: length,
	border-radius: length,
	border-color: brush,
	border-color-hover: brush,
	border-color-disabled: brush,
	font-size: length,
	text-color: brush,
	text-color-disabled: brush,
	icon-size: length,
	icon-color: brush,
	popup-max-height: length,
	option-height: length,
	option-bg-fill: brush,
	option-bg-selected: brush,
	option-text-selected-color: brush,
	option-text-disabled-color: brush,
	padding-vertical: length,
	padding-horizontal: length,
	padding-popover: length,
}


export global USelectThemes {
    out property <USelectTheme> default: {
        background: Colors.transparent,
        border-width: 1px * UAppTheme.scale-factor,
        border-radius: UAppTheme.radius-base,
        border-color: UAppTheme.border,
        border-color-hover: UAppTheme.primary-hover,
        border-color-disabled: UAppTheme.border-secondary,
        font-size: UAppTheme.font-size-base,
        text-color: UAppTheme.text,
        text-color-disabled: UAppTheme.text-disabled,
        icon-size: UAppTheme.icon-size-base,
        icon-color: UAppTheme.border,
        popup-max-height: 124px * UAppTheme.scale-factor,
        option-height: 29px * UAppTheme.scale-factor,
        option-bg-fill: UAppTheme.color-fill-tertiary,
        option-bg-selected: UAppTheme.primary-selected,
        option-text-selected-color: UAppTheme.primary,
        option-text-disabled-color: UAppTheme.text-disabled,
        padding-vertical: UAppTheme.padding-vertical,
        padding-horizontal: UAppTheme.padding-horizontal,
        padding-popover: UAppTheme.padding-base,
    };
}
