import { UAppTheme } from "../app-theme.slint";


export struct UTextTheme {
	color: brush,
	font-size: length,
	font-weight: int,
	font-family: string,
	font-italic: bool,
	horizontal-alignment: TextHorizontalAlignment,
	letter-spacing: length,
	overflow: TextOverflow,
	vertical-alignment: TextVerticalAlignment,
	wrap: TextWrap,
	stroke: brush,
	stroke-width: length,
	stroke-style: TextStrokeStyle,
}


export global UTextThemes {
    out property <UTextTheme> default: {
        color: UAppTheme.text,
        font-size: UAppTheme.font-size-base,
    };
}
