import { UAppTheme } from "../app-theme.slint";


export struct UTitleTheme {
	color: brush,
	font-size: length,
	font-weight: int,
	font-family: string,
	font-italic: bool,
	horizontal-alignment: TextHorizontalAlignment,
	letter-spacing: length,
	overflow: TextOverflow,
	vertical-alignment: TextVerticalAlignment,
	wrap: TextWrap,
	stroke: brush,
	stroke-width: length,
	stroke-style: TextStrokeStyle,
}


export global UTitleThemes {
    out property <UTitleTheme> level-1: {
        color: UAppTheme.text-heading,
        font-size: 36px * UAppTheme.scale-factor,
        font-weight: 600,
    };
    out property <UTitleTheme> level-2: {
        color: UAppTheme.text-heading,
        font-size: 30px * UAppTheme.scale-factor,
        font-weight: 500,
    };
    out property <UTitleTheme> level-3: {
        color: UAppTheme.text-heading,
        font-size: 24px * UAppTheme.scale-factor,
        font-weight: 400,
    };
    out property <UTitleTheme> level-4: {
        color: UAppTheme.text-heading,
        font-size: 20px * UAppTheme.scale-factor,
        font-weight: 400,
    };
    out property <UTitleTheme> level-5: {
        color: UAppTheme.text-heading,
        font-size: 18px * UAppTheme.scale-factor,
        font-weight: 400,
    };
    out property <UTitleTheme> level-6: {
        color: UAppTheme.text-heading,
        font-size: 16px * UAppTheme.scale-factor,
        font-weight: 400,
    };
}
