import { UAppTheme } from "../sleek-ui/app-theme.slint";
import { UTitle, UText, UCode, ULink } from "../sleek-ui/widgets.slint";

import { DocTitle } from "../components/doc-widgets.slint";
import { PageBase } from "../components/page-base.slint";
import { AppLogic } from "../app-logic.slint";
import { AboutSlint } from "std-widgets.slint";


export component AboutPage inherits PageBase {
    UTitle {
        level: 3;
        text: "About";
    }

    StyledText {
        text: @markdown("Sleek-ui is a widgets library based on [Ant Design](https://ant.design/) made with only Slint, which makes it compatible with Rust, C++, Python and Javascript.\nIt comes with a reactive theming system and a color scheme implementation using the Palette standart global.");
        link-color: UAppTheme.primary.base;
        link-clicked(link) => {
            Platform.open-url(link);
        }
    }

    HorizontalLayout {
        alignment: center;
        padding-top: 200px;
        AboutSlint {
            width: 200px;
        }
    }
}
