import {
	UText,
	UTitle
} from "../sleek-ui/widgets.slint";
import { UAppTheme } from "../sleek-ui/app-theme.slint";
import { ScrollView, AboutSlint } from "std-widgets.slint";

export component About {
    VerticalLayout {
        padding: 10px * UAppTheme.scale-factor;
        HorizontalLayout {
            alignment: start;
            padding-bottom: 36px * UAppTheme.scale-factor;
            UTitle {
                level: 4;
                text: "About";
            }
        }

        UText {
            wrap: word-wrap;
            text: "Sleek-ui is an widget library made for Slint. It comes with 25+ customisable widget using a theme system compatible with Slint's color scheme.";
        }

        Rectangle { }

        HorizontalLayout {
            alignment: center;
            AboutSlint {
                width: 175px * UAppTheme.scale-factor;
            }
        }
    }
}
