import { UAppTheme } from "../sleek-ui/app-theme.slint";
import { UTitle } from "../sleek-ui/widgets.slint";
import { UPrimaryColor } from "../sleek-ui/structs/theme.slint";
import { ULightColors, UDarkColors } from "../sleek-ui/colors.slint";

import { DocTitle, DocSection, DocCode } from "../components/doc-widgets.slint";
import { PageBase } from "../components/page-base.slint";
import { AppLogic } from "../app-logic.slint";


component ColorRect inherits Rectangle {
    in property <brush> color-brush;
    width: 80px;
    height: 40px;
    background: color-brush;
    border-width: UAppTheme.border-width-base;
    border-color: UAppTheme.focus-color;
}

component ColorPresentation {
    in property <string> color-name;
    in property <UPrimaryColor> light;
    in property <UPrimaryColor> dark;
    VerticalLayout {
        alignment: start;
        spacing: UAppTheme.spacing-big;
        padding-top: UAppTheme.padding-big;
        padding-bottom: UAppTheme.padding-big;
        UTitle {
            level: 6;
            text: color-name;
        }

        HorizontalLayout {
            alignment: space-around;
            HorizontalLayout {
                ColorRect {
                    color-brush: light.base;
                }

                ColorRect {
                    color-brush: light.hover;
                }

                ColorRect {
                    color-brush: light.active;
                }

                ColorRect {
                    color-brush: light.disabled;
                }

                ColorRect {
                    color-brush: light.selected;
                }
            }

            HorizontalLayout {
                ColorRect {
                    color-brush: dark.base;
                }

                ColorRect {
                    color-brush: dark.hover;
                }

                ColorRect {
                    color-brush: dark.active;
                }

                ColorRect {
                    color-brush: dark.disabled;
                }

                ColorRect {
                    color-brush: dark.selected;
                }
            }
        }
    }
}

export component ColorsPage inherits PageBase {
    UTitle {
        level: 3;
        text: "Default colors";
    }

    DocSection {
        title: "Primary color struct";
        description: [
            [
                { text: "A primary color is represented by the " },
                { code: "UPrimaryColor" },
                { text: " struct." }
            ],
            [
                { text: "This struct is available in the " },
                { code: "@sleek-ui/structs/theme.slint" },
                { text: " file." }
            ]
        ];
    }

    DocCode {
        code: "UPrimaryColor {\n    base: brush,\n    hover: brush,\n    active: brush,\n    disabled: brush,\n    selected: brush,\n}";
    }

    DocSection {
        title: "Default colors";
        description: [
            [
                { text: "The default colors are available in the " },
                { code: "ULightColors" },
                { text: " and " },
                { code: "UDarkColors" },
                { text: " globals from the " },
                { code: "@sleek-ui/colors.slint" },
                { text: " file." }
            ],
            [
                { text: "All colors are available on the " },
                { link: "And Design website" },
                { text: "." }
            ]
        ];
        link-clicked(id) => {
            AppLogic.open-url("https://ant.design/docs/spec/colors");
        }
    }

    ColorPresentation {
        color-name: "Dust red";
        light: ULightColors.dust-red;
        dark: UDarkColors.dust-red;
    }

    ColorPresentation {
        color-name: "Volcano";
        light: ULightColors.volcano;
        dark: UDarkColors.volcano;
    }

    ColorPresentation {
        color-name: "Sunset orange";
        light: ULightColors.sunset-orange;
        dark: UDarkColors.sunset-orange;
    }

    ColorPresentation {
        color-name: "Calendula gold";
        light: ULightColors.calendula-gold;
        dark: UDarkColors.calendula-gold;
    }

    ColorPresentation {
        color-name: "Sunrise yellow";
        light: ULightColors.sunrise-yellow;
        dark: UDarkColors.sunrise-yellow;
    }

    ColorPresentation {
        color-name: "Lime";
        light: ULightColors.lime;
        dark: UDarkColors.lime;
    }

    ColorPresentation {
        color-name: "Polar green";
        light: ULightColors.polar-green;
        dark: UDarkColors.polar-green;
    }

    ColorPresentation {
        color-name: "Cyan";
        light: ULightColors.cyan;
        dark: UDarkColors.cyan;
    }

    ColorPresentation {
        color-name: "Daybreak blue";
        light: ULightColors.daybreak-blue;
        dark: UDarkColors.daybreak-blue;
    }

    ColorPresentation {
        color-name: "Geek blue";
        light: ULightColors.geek-blue;
        dark: UDarkColors.geek-blue;
    }

    ColorPresentation {
        color-name: "Golden purple";
        light: ULightColors.golden-purple;
        dark: UDarkColors.golden-purple;
    }

    ColorPresentation {
        color-name: "French magenta";
        light: ULightColors.french-magenta;
        dark: UDarkColors.french-magenta;
    }
}
