import {
    UButton,
    UCheckbox,
    UDivider,
    UIconButton,
    UInput,
    UInputNumber,
    ULink,
    ULinearProgress,
    URadio,
    URadioButton,
    USelect,
    USlider,
    USwitch,
    UText,
    UTitle,
} from "../sleek-ui/widgets.slint";
import { UAppTheme } from "../sleek-ui/app-theme.slint";
import { ScrollView } from "std-widgets.slint";
import { OptionsBarLogic } from "../components/options-bar.slint";


// TODO Remove this import once dev of UMenu is done
import {
    UMenu,
    UMenuLink,
    UMenuGroupTitle,
    UMenuSubmenu,
} from "../sleek-ui/widgets.slint";


export component Controls inherits Rectangle {
    ScrollView {
        VerticalLayout {
            alignment: start;
            padding: 10px * UAppTheme.scale-factor;
            HorizontalLayout {
                alignment: space-between;
                padding-bottom: 36px * UAppTheme.scale-factor;
                UTitle {
                    level: 4;
                    text: "Controls";
                }
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-base;
                padding-top: UAppTheme.padding-base;
                UMenu {
                    width: 300px * UAppTheme.scale-factor;
                    UMenuLink {
                        id: "Home";
                        name: "Home";
                    }

                    UMenuLink {
                        id: "dashboard";
                        name: "Dashboard";
                        activated => {
                            debug("ttestinge");
                        }
                    }

                    UMenuSubmenu {
                        enable-animation: false;
                        name: "Controls";
                        has-child-selected: cont1.is-selected || cont2.is-selected || cont3.is-selected || cont4.is-selected || conts1.has-child-selected;
                        cont1 := UMenuLink {
                            id: "Mouse";
                            name: "Mouse";
                        }

                        cont2 := UMenuLink {
                            id: "Keyboard";
                            name: "Keyboard";
                        }

                        cont3 := UMenuLink {
                            id: "Controller";
                            name: "Controller";
                        }

                        conts1 := UMenuSubmenu {
                            enable-animation: false;
                            name: "Custom controls";
                            has-child-selected: cust1.is-selected || cust2.is-selected || cust3.is-selected;
                            cust1 := UMenuLink {
                                id: "custom 1";
                                name: "Custom 1";
                            }

                            cust2 := UMenuLink {
                                id: "custom 2";
                                name: "Custom 2";
                            }

                            cust3 := UMenuLink {
                                id: "custom 3";
                                name: "Custom 3";
                            }
                        }

                        UMenuGroupTitle {
                            title: "Settings";
                        }

                        cont4 := UMenuLink {
                            id: "ControlsSettings";
                            name: "Settings";
                        }
                    }

                    UMenuLink {
                        enabled: false;
                        id: "Users";
                        name: "Users";
                    }

                    UMenuLink {
                        id: "Settings";
                        name: "Settings";
                    }
                }
            }

            UText {
                text: "Buttons";
                font-weight: 600;
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-base;
                padding-top: UAppTheme.padding-base;
                UButton {
                    enabled: OptionsBarLogic.widgets-enabled;
                    text: "Default";
                }

                UButton {
                    enabled: OptionsBarLogic.widgets-enabled;
                    variant: primary;
                    text: "Primary";
                }

                UButton {
                    enabled: OptionsBarLogic.widgets-enabled;
                    variant: filled;
                    text: "Filled";
                }

                UButton {
                    enabled: OptionsBarLogic.widgets-enabled;
                    variant: text;
                    text: "Text";
                }
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-base;
                padding-top: UAppTheme.padding-base;
                UButton {
                    enabled: OptionsBarLogic.widgets-enabled;
                    text: "Danger";
                    danger: true;
                }

                UButton {
                    enabled: OptionsBarLogic.widgets-enabled;
                    variant: filled;
                    text: "Filled";
                    danger: true;
                    loading: true;
                }

                UButton {
                    enabled: OptionsBarLogic.widgets-enabled;
                    variant: primary;
                    text: "Primary";
                    loading: true;
                }
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-base;
                padding-top: UAppTheme.padding-base;
                padding-bottom: 24px * UAppTheme.scale-factor;
                UButton {
                    enabled: OptionsBarLogic.widgets-enabled;
                    variant: primary;
                    text: "Primary";
                    icon: @image-url("../assets/images/plus.svg");
                    icon-placement: start;
                }

                UButton {
                    enabled: OptionsBarLogic.widgets-enabled;
                    text: "Default";
                    icon: @image-url("../assets/images/plus.svg");
                    icon-placement: end;
                }

                UIconButton {
                    enabled: OptionsBarLogic.widgets-enabled;
                    variant: primary;
                    icon: @image-url("../assets/images/search.svg");
                }

                UIconButton {
                    enabled: OptionsBarLogic.widgets-enabled;
                    icon: @image-url("../assets/images/search.svg");
                }
            }

            UText {
                text: "Checkbox - Select - Switch";
                font-weight: 600;
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-big;
                padding-top: UAppTheme.padding-base;
                padding-bottom: 24px * UAppTheme.scale-factor;
                UCheckbox {
                    enabled: OptionsBarLogic.widgets-enabled;
                    text: self.checked ? "Checked" : "Unchecked";
                    text-placement: end;
                }

                USelect {
                    enabled: OptionsBarLogic.widgets-enabled;
                    width: 150px * UAppTheme.scale-factor;
                    options: [
                        { text: "Europe", value: "eu", enabled: true },
                        { text: "Asia", value: "asia", enabled: true },
                        { text: "North America", value: "na", enabled: true }
                    ];
                }

                VerticalLayout {
                    alignment: center;
                    USwitch {
                        enabled: OptionsBarLogic.widgets-enabled;
                    }
                }
            }

            UText {
                text: "Radio";
                font-weight: 600;
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-big;
                padding-top: UAppTheme.padding-base;
                URadio {
                    enabled: OptionsBarLogic.widgets-enabled;
                    orientation: horizontal;
                    options: ["Apple", "Banana", "Orange"];
                }
            }

            HorizontalLayout {
                padding: UAppTheme.padding-bigger;
                UDivider {
                    width: 150px * UAppTheme.scale-factor;
                }
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-big;
                padding-bottom: 24px * UAppTheme.scale-factor;
                URadio {
                    enabled: OptionsBarLogic.widgets-enabled;
                    options: ["Apple", "Banana", "Orange"];
                }
            }

            UText {
                text: "Radio Button";
                font-weight: 600;
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-big;
                padding-top: UAppTheme.padding-base;
                URadioButton {
                    enabled: OptionsBarLogic.widgets-enabled;
                    options: ["Apple", "Banana", "Orange"];
                }
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-big;
                padding-top: UAppTheme.padding-base;
                padding-bottom: 24px * UAppTheme.scale-factor;
                URadioButton {
                    variant: primary;
                    enabled: OptionsBarLogic.widgets-enabled;
                    options: ["Apple", "Banana", "Orange"];
                }
            }

            UText {
                text: "Input - InputNumber";
                font-weight: 600;
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-big;
                padding-top: UAppTheme.padding-base;
                padding-bottom: 24px * UAppTheme.scale-factor;
                UInput {
                    enabled: OptionsBarLogic.widgets-enabled;
                    width: 150px * UAppTheme.scale-factor;
                    placeholder: "Enter some text";
                }

                UInputNumber {
                    enabled: OptionsBarLogic.widgets-enabled;
                    width: 150px * UAppTheme.scale-factor;
                }
            }

            UText {
                text: "Link";
                font-weight: 600;
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-big;
                padding-top: UAppTheme.padding-base;
                padding-bottom: 24px * UAppTheme.scale-factor;
                ULink {
                    text: "Website";
                }
            }

            UText {
                text: "Slider";
                font-weight: 600;
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-base;
                padding-top: UAppTheme.padding-base;
                padding-bottom: 24px * UAppTheme.scale-factor;
                USlider {
                    enabled: OptionsBarLogic.widgets-enabled;
                    value: 30;
                    step: 1;
                    width: 300px * UAppTheme.scale-factor;
                }
            }

            UText {
                text: "Progress";
                font-weight: 600;
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-big;
                VerticalLayout {
                    alignment: center;
                    progress := ULinearProgress {
                        width: 300px * UAppTheme.scale-factor;
                        indeterminate: progress-indeterminate.checked;
                        progress: 35%;
                    }
                }

                UIconButton {
                    enabled: OptionsBarLogic.widgets-enabled;
                    variant: primary;
                    icon: @image-url("../assets/images/minus.svg");
                    clicked => {
                        progress.progress -= 10%;
                    }
                }

                UIconButton {
                    enabled: OptionsBarLogic.widgets-enabled;
                    variant: primary;
                    icon: @image-url("../assets/images/plus.svg");
                    clicked => {
                        progress.progress += 10%;
                    }
                }
            }

            HorizontalLayout {
                alignment: start;
                padding-top: UAppTheme.padding-base;
                progress-indeterminate := UCheckbox {
                    enabled: OptionsBarLogic.widgets-enabled;
                    checked: false;
                    text: "Indeterminate";
                    text-placement: end;
                }
            }
        }
    }
}
