import {
	UButton,
	UCheckbox,
	UDivider,
	UIconButton,
	UInput,
	UInputNumber,
	ULink,
	ULinearProgress,
	URadio,
	URadioButton,
	USelect,
	USwitch,
	UText,
	UTitle
} from "../sleek-ui/widgets.slint";
import { UAppTheme } from "../sleek-ui/app-theme.slint";
import { ScrollView } from "std-widgets.slint";

export component Controls inherits Rectangle {
    in-out property <bool> widgets-enabled <=> enable-switch.checked;
    ScrollView {
        VerticalLayout {
            alignment: start;
            padding: 10px * UAppTheme.scale-factor;
            HorizontalLayout {
                alignment: space-between;
                padding-bottom: 36px * UAppTheme.scale-factor;
                UTitle {
                    level: 4;
                    text: "Controls";
                }

                HorizontalLayout {
                    spacing: UAppTheme.spacing-big;
                    enable-switch := USwitch { }

                    UText {
                        text: widgets-enabled ? "Widgets enabled" : "Widgets disabled";
                        color: UAppTheme.text-secondary;
                    }
                }
            }

            UText {
                text: "Buttons";
                font-weight: 600;
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-base;
                padding-top: UAppTheme.padding-base;
                UButton {
                    enabled: widgets-enabled;
                    text: "Default";
                }

                UButton {
                    enabled: widgets-enabled;
                    variant: primary;
                    text: "Primary";
                }

                UButton {
                    enabled: widgets-enabled;
                    variant: filled;
                    text: "Filled";
                }

                UButton {
                    enabled: widgets-enabled;
                    variant: text;
                    text: "Text";
                }
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-base;
                padding-top: UAppTheme.padding-base;
                UButton {
                    enabled: widgets-enabled;
                    text: "Danger";
                    danger: true;
                }

                UButton {
                    enabled: widgets-enabled;
                    variant: filled;
                    text: "Filled";
                    danger: true;
                    loading: true;
                }

                UButton {
                    enabled: widgets-enabled;
                    variant: primary;
                    text: "Primary";
                    loading: true;
                }
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-base;
                padding-top: UAppTheme.padding-base;
                padding-bottom: 24px * UAppTheme.scale-factor;
                UButton {
                    enabled: widgets-enabled;
                    variant: primary;
                    text: "Primary";
                    icon: @image-url("../assets/images/plus.svg");
                    icon-placement: start;
                }

                UButton {
                    enabled: widgets-enabled;
                    text: "Default";
                    icon: @image-url("../assets/images/plus.svg");
                    icon-placement: end;
                }

                UIconButton {
                    enabled: widgets-enabled;
                    variant: primary;
                    icon: @image-url("../assets/images/search.svg");
                }

                UIconButton {
                    enabled: widgets-enabled;
                    icon: @image-url("../assets/images/search.svg");
                }
            }

            UText {
                text: "Checkbox - Select - Switch";
                font-weight: 600;
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-big;
                padding-top: UAppTheme.padding-base;
                padding-bottom: 24px * UAppTheme.scale-factor;
                UCheckbox {
                    text: self.checked ? "Checked" : "Unchecked";
                    text-placement: end;
                }

                USelect {
                    enabled: widgets-enabled;
                    width: 150px * UAppTheme.scale-factor;
                    options: [
                        { text: "Europe", value: "eu", enabled: true },
                        { text: "Asia", value: "asia", enabled: true },
                        { text: "North America", value: "na", enabled: true }
                    ];
                }

                VerticalLayout {
                    alignment: center;
                    USwitch {
                        enabled: widgets-enabled;
                    }
                }
            }

            UText {
                text: "Radio";
                font-weight: 600;
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-big;
                padding-top: UAppTheme.padding-base;
                URadio {
                    orientation: horizontal;
                    options: ["Apple", "Banana", "Orange"];
                }
            }

            HorizontalLayout {
                padding: UAppTheme.padding-bigger;
                UDivider {
                    width: 150px * UAppTheme.scale-factor;
                }
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-big;
                padding-bottom: 24px * UAppTheme.scale-factor;
                URadio {
                    options: ["Apple", "Banana", "Orange"];
                }
            }

            UText {
                text: "Radio Button";
                font-weight: 600;
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-big;
                padding-top: UAppTheme.padding-base;
                URadioButton {
                    options: ["Apple", "Banana", "Orange"];
                }
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-big;
                padding-top: UAppTheme.padding-base;
                padding-bottom: 24px * UAppTheme.scale-factor;
                URadioButton {
                    variant: primary;
                    options: ["Apple", "Banana", "Orange"];
                }
            }

            UText {
                text: "Input - InputNumber";
                font-weight: 600;
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-big;
                padding-top: UAppTheme.padding-base;
                padding-bottom: 24px * UAppTheme.scale-factor;
                UInput {
                    enabled: widgets-enabled;
                    width: 150px * UAppTheme.scale-factor;
                    placeholder: "Enter some text";
                }

                UInputNumber {
                    enabled: widgets-enabled;
                    width: 150px * UAppTheme.scale-factor;
                }
            }

            UText {
                text: "Link";
                font-weight: 600;
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-big;
                padding-top: UAppTheme.padding-base;
                padding-bottom: 24px * UAppTheme.scale-factor;
                ULink {
                    text: "Website";
                }
            }

            UText {
                text: "Progress";
                font-weight: 600;
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-big;
                padding-top: UAppTheme.padding-base;
                VerticalLayout {
                    alignment: center;
                    progress := ULinearProgress {
                        width: 300px * UAppTheme.scale-factor;
                        indeterminate: progress-indeterminate.checked;
                        progress: 35%;
                    }
                }

                UIconButton {
                    variant: primary;
                    icon: @image-url("../assets/images/minus.svg");
                    clicked => {
                        progress.progress -= 10%;
                    }
                }

                UIconButton {
                    variant: primary;
                    icon: @image-url("../assets/images/plus.svg");
                    clicked => {
                        progress.progress += 10%;
                    }
                }
            }

            HorizontalLayout {
                alignment: start;
                padding-top: UAppTheme.padding-base;
                progress-indeterminate := UCheckbox {
                    checked: false;
                    text: "Indeterminate";
                    text-placement: end;
                }
            }
        }
    }
}
