import { UAppTheme } from "../sleek-ui/app-theme.slint";
import {
    UTitle,
    UMenuLogic,
} from "../sleek-ui/widgets.slint";

import {
    DocSection,
    DocDescription,
} from "../components/doc-widgets.slint";
import { PageBase } from "../components/page-base.slint";
import { AppLogic } from "../app-logic.slint";
import { SlintDocPage } from "../structs/doc-content.slint";



export component ContentPage inherits PageBase {
    in-out property <SlintDocPage> content: AppLogic.get-page-content(UMenuLogic.current-link);
    UTitle {
        level: 3;
        text: root.content.title;
    }

    if root.content.description != "": DocDescription {
        text: root.content.description;
    }
    for section in root.content.sections: DocSection {
        title: section.title;
        description: section.description;
        widget-id: section.widget-id;
        code: section.code;
    }
}
