import {
	UBreadcrumb,
	UCard,
	UCollapse,
	UDivider,
	UIcon,
	USpinner,
	UTag,
	UText,
	UTitle,
	UTooltip
} from "../sleek-ui/widgets.slint";
import { UAppTheme } from "../sleek-ui/app-theme.slint";
import { ScrollView } from "std-widgets.slint";


export component DataDisplay {
    ScrollView {
        VerticalLayout {
            alignment: start;
            padding: 10px * UAppTheme.scale-factor;
            HorizontalLayout {
                alignment: start;
                padding-bottom: 36px * UAppTheme.scale-factor;
                UTitle {
                    level: 4;
                    text: "Data display";
                }
            }

            UText {
                text: "Breadcrumb";
                font-weight: 600;
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-base;
                padding-top: UAppTheme.padding-base;
                padding-bottom: 24px * UAppTheme.scale-factor;
                UBreadcrumb {
                    steps: ["Home", "Settings", "User", "Confidentiality"];
                }
            }

            UText {
                text: "Card";
                font-weight: 600;
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-big;
                padding-top: UAppTheme.padding-base;
                padding-bottom: 24px * UAppTheme.scale-factor;
                UCard {
                    width: 200px;
                    VerticalLayout {
                        HorizontalLayout {
                            alignment: start;
                            padding: UAppTheme.padding-base;
                            UText {
                                text: "This is a card, a simple elevated component that take children components.";
                                wrap: word-wrap;
                            }
                        }
                    }
                }
            }

            UText {
                text: "Tooltip";
                font-weight: 600;
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-base;
                padding-top: UAppTheme.padding-base;
                padding-bottom: 24px * UAppTheme.scale-factor;
                t-text := TouchArea {
                    UText {
                        text: "Hover this text to display a tooltip.";
                    }
                }
            }

            UText {
                text: "Collapse";
                font-weight: 600;
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-big;
                padding-top: UAppTheme.padding-base;
                padding-bottom: 24px * UAppTheme.scale-factor;
                UCollapse {
                    title: "Summary";
                    content-height: 30px * UAppTheme.scale-factor;
                    UText {
                        text: "Sleek-ui offer a set a custom made and customizable widgets.";
                    }
                }
            }

            UText {
                text: "Divider";
                font-weight: 600;
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-big;
                padding-top: UAppTheme.padding-base;
                padding-bottom: 24px * UAppTheme.scale-factor;
                HorizontalLayout {
                    alignment: start;
                    spacing: UAppTheme.spacing-big;
                    VerticalLayout {
                        alignment: center;
                        UText {
                            text: "First part";
                        }
                    }

                    UDivider {
                        orientation: vertical;
                        height: 20px;
                    }

                    VerticalLayout {
                        alignment: center;
                        UText {
                            text: "Last part";
                        }
                    }
                }
            }

            UText {
                text: "Icon";
                font-weight: 600;
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-big;
                padding-top: UAppTheme.padding-base;
                padding-bottom: 24px * UAppTheme.scale-factor;
                HorizontalLayout {
                    alignment: start;
                    spacing: UAppTheme.spacing-big;
                    UIcon {
                        source: @image-url("../assets/images/search.svg");
                    }

                    UIcon {
                        source: @image-url("../assets/images/minus.svg");
                    }

                    UIcon {
                        source: @image-url("../assets/images/plus.svg");
                    }
                }
            }

            UText {
                text: "Spinner";
                font-weight: 600;
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-big;
                padding-top: UAppTheme.padding-base;
                padding-bottom: 24px * UAppTheme.scale-factor;
                HorizontalLayout {
                    alignment: start;
                    spacing: UAppTheme.spacing-base;
                    USpinner {
                        size: 24px * UAppTheme.scale-factor;
                    }
                }
            }

            UText {
                text: "Tag";
                font-weight: 600;
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-big;
                padding-top: UAppTheme.padding-base;
                padding-bottom: 24px * UAppTheme.scale-factor;
                HorizontalLayout {
                    alignment: start;
                    spacing: UAppTheme.spacing-base;
                    UTag {
                        variant: info;
                        text: "Info";
                    }

                    UTag {
                        variant: success;
                        text: "Sucess";
                    }

                    UTag {
                        variant: warning;
                        text: "Warning";
                    }

                    UTag {
                        variant: danger;
                        text: "Danger";
                    }
                }
            }

            UText {
                text: "Text";
                font-weight: 600;
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-big;
                padding-top: UAppTheme.padding-base;
                padding-bottom: 24px * UAppTheme.scale-factor;
                UText {
                    text: "A simple text element pre-configured and themeable.";
                }
            }

            UText {
                text: "Title";
                font-weight: 600;
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-big;
                padding-top: UAppTheme.padding-base;
                padding-bottom: 24px * UAppTheme.scale-factor;
                VerticalLayout {
                    alignment: start;
                    spacing: UAppTheme.spacing-base;
                    UTitle {
                        level: 1;
                        text: "Hello world";
                    }

                    UTitle {
                        level: 2;
                        text: "Hello world";
                    }

                    UTitle {
                        level: 3;
                        text: "Hello world";
                    }

                    UTitle {
                        level: 4;
                        text: "Hello world";
                    }

                    UTitle {
                        level: 5;
                        text: "Hello world";
                    }

                    UTitle {
                        level: 6;
                        text: "Hello world";
                    }
                }
            }
        }

        UTooltip {
            text: "The tooltip can use one of the following positions: top, bottom, left, right.";
            position: top;
            user_is_hovering: t-text.has-hover;
            inner-x: t-text.absolute-position.x - root.absolute-position.x;
            inner-y: t-text.absolute-position.y;
            inner-width: t-text.width;
            inner-height: t-text.height;
        }
    }
}
