import { UAppTheme } from "../sleek-ui/app-theme.slint";
import {
    UTitle,
    UText,
    UCode,
    ULink,
    UMenuLogic,
} from "../sleek-ui/widgets.slint";

import { DocTitle, DocSection, DocCode } from "../components/doc-widgets.slint";
import { PageBase } from "../components/page-base.slint";
import { AppLogic } from "../app-logic.slint";


export component HowToUsePage inherits PageBase {
    UTitle {
        level: 3;
        text: "How to use Sleek-ui";
    }

    DocTitle {
        text: "Add the library to your project";
    }

    DocSection {
        title: "Add the library to your project";
        description: [
            [
                { text: "1. Download the library from the latest release on its " },
                {
                    link: "github repository",
                    url: "https://github.com/uAtomicBoolean/sleek-ui/releases"
                },
                { text: "." }
            ],
            [
                {
                    text: "2. Unzip the library and move it either to your project, or to another folder on your computer."
                }
            ],
            [
                { text: "3. Add Sleek-ui as a library following the " },
                {
                    link: "official documentation",
                    url: "https://docs.slint.dev/latest/docs/slint/guide/language/coding/file/#component-libraries"
                },
                { text: "." }
            ]
        ];
        link-clicked(url) => {
            AppLogic.open-url(url);
        }
    }

    DocSection {
        title: "Use the widgets in your code";
        description: [
            [
                { text: "All widgets can be imported from the " },
                { code: "@sleek-ui/widgets.slint" },
                { text: "file." }
            ],
            [{ text: "They can be then used like a native widget:" }]
        ];
    }

    DocCode {
        code: "import { UButton, UText } from \"@sleek-ui/widgets.slint\";\n\nexport component AppWindow inherits Window {\n    VerticalLayout {\n        UButton {\n            text: \"Button\";\n            variant: primary;\n        }\n        UText {\n            text: \"Some custom text displayed with UText.\";\n        }\n    }\n}";
    }

    DocSection {
        title: "Use the library's theme.";
        description: [
            [
                { text: "sleek-ui comes with design tokens fully available in the " },
                {
                    link: "UAppTheme",
                    url: "https://github.com/uAtomicBoolean/sleek-ui/blob/main/ui/sleek-ui/app-theme.slint"
                },
                { text: " global." }
            ],
            [
                {
                    text: " This allows you to keep the same look and feel across your whole application."
                }
            ],
            [
                { text: "The global also re-export all the " },
                { link: "default colors", url:"default-colors" },
                { text: " as properties synced to the color scheme." }
            ]
        ];
        link-clicked(url) => {
            if url == "default-colors" {
                UMenuLogic.current-link = url;
            } else {
                AppLogic.open-url(url);
            }
        }
    }

    DocCode {
        code: "import { UAppTheme } from \"@sleek-ui/app-theme.slint\";\n\n export component CustomCard inherits Rectangle {\n    border-radius: UAppTheme.radius-base;\n    border-width: UAppTheme.border-width-base;\n    border-color: UAppTheme.border;\n    background: UAppTheme.golden-purple.base;\n    // Your code...\n}";
    }
}
