import { UAppTheme } from "../sleek-ui/app-theme.slint";
import { UTitle, UText, UCode, ULink } from "../sleek-ui/widgets.slint";

import { DocTitle, DocSection, DocCode } from "../components/doc-widgets.slint";
import { PageBase } from "../components/page-base.slint";
import { AppLogic } from "../app-logic.slint";


export component HowToUsePage inherits PageBase {
    UTitle {
        level: 3;
        text: "How to use Sleek-ui";
    }

    DocTitle {
        text: "Add the library to your project";
    }

    DocSection {
        title: "Add the library to your project";
        description: [
            [
                { text: "1. Download the library from the latest release on its " },
                { link: "github repository", id: "github" },
                { text: "." }
            ],
            [
                {
                    text: "2. Unzip the library and move it either to your project, or to another folder on your computer."
                }
            ],
            [
                { text: "3. Add Sleek-ui as a library following the " },
                { link: "official documentation", id: "official-doc" },
                { text: "." }
            ]
        ];
        link-clicked(id) => {
            if id == "github" {
                AppLogic.open-url("https://github.com/uAtomicBoolean/sleek-ui/releases");
            } else if id == "official-doc" {
                AppLogic.open-url("https://docs.slint.dev/latest/docs/slint/guide/language/coding/file/#component-libraries");
            }
        }
    }

    DocSection {
        title: "Use the widgets in your code";
        description: [
            [
                { text: "All widgets can be imported from the " },
                { code: "@sleek-ui/widgets.slint" },
                { text: "file." }
            ],
            [{ text: "They can be then used like a native widget:" }]
        ];
    }

    DocCode {
        code: "import { UButton, UText } from \"@sleek-ui/widgets.slint\";\n\nexport component AppWindow inherits Window {\n    VerticalLayout {\n        UButton {\n            text: \"Button\";\n            variant: primary;\n        }\n        UText {\n            text: \"Some custom text displayed with UText.\";\n        }\n    }\n}";
    }

    DocSection {
        title: "Use the library's theme.";
        description: [
            [
                { text: "SleekUI comes with design tokens fully available in the " },
                { link: "UAppTheme", id: "app-theme" },
                { text: " global." }
            ],
            [
                {
                    text: " This allows you to keep the same look and feel across your whole application."
                }
            ]
        ];
        link-clicked(id) => {
            AppLogic.open-url("https://github.com/uAtomicBoolean/SleekUI/blob/main/ui/sleek-ui/app-theme.slint");
        }
    }

    DocCode {
        code: "import { UAppTheme } from \"@sleek-ui/app-theme.slint\";\n\n export component CustomCard inherits Rectangle {\n    border-radius: UAppTheme.radius-base;\n    border-width: UAppTheme.border-width-base;\n    border-color: UAppTheme.border;\n    // Your code...\n}";
    }
}
