import {
    UBreadcrumb,
    UText,
    UTitle,
    UTabs,
    UMenu,
    UMenuLink,
    UMenuSubmenu,
} from "../sleek-ui/widgets.slint";
import { UAppTheme } from "../sleek-ui/app-theme.slint";
import { ScrollView, AboutSlint } from "std-widgets.slint";


export component Navigation {
    ScrollView {
        VerticalLayout {
            alignment: start;
            padding: 10px * UAppTheme.scale-factor;
            HorizontalLayout {
                alignment: start;
                padding-bottom: 36px * UAppTheme.scale-factor;
                UTitle {
                    level: 4;
                    text: "Navigation";
                }
            }

            UText {
                text: "Breadcrumb";
                font-weight: 600;
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-base;
                padding-top: UAppTheme.padding-base;
                padding-bottom: 24px * UAppTheme.scale-factor;
                UBreadcrumb {
                    steps: ["Home", "Settings", "User", "Confidentiality"];
                }
            }

            UText {
                text: "Tabs";
                font-weight: 600;
            }

            VerticalLayout {
                alignment: start;
                padding-top: UAppTheme.padding-base;
                height: 120px;
                UTabs {
                    tabs: ["France", "Germany", "United Kingdom", "Italy"];
                    if self.current-index == 0: VerticalLayout {
                        spacing: UAppTheme.spacing-base;
                        UText {
                            text: "Welcome to France!";
                        }

                        UText {
                            text: "You can put whatever you want in a tab's content.";
                        }
                    }
                    if self.current-index == 1: UText {
                        text: "Welcome to Germany!";
                    }
                    if self.current-index == 2: UText {
                        text: "Welcome to the United Kingdom!";
                    }
                    if self.current-index == 3: UText {
                        text: "Welcome to Italy!";
                    }
                }
            }

            VerticalLayout {
                alignment: start;
                padding-top: UAppTheme.padding-base;
                padding-bottom: 24px * UAppTheme.scale-factor;
                UTabs {
                    tabs-alignement: stretch;
                    tabs: ["France", "Germany", "United Kingdom", "Italy"];
                    if self.current-index == 0: UText {
                        text: "You can also enable the tabs to take all the available space.";
                    }
                    if self.current-index == 1: UText {
                        text: "You can also enable the tabs to take all the available space.";
                    }
                    if self.current-index == 2: UText {
                        text: "You can also enable the tabs to take all the available space.";
                    }
                    if self.current-index == 3: UText {
                        text: "You can also enable the tabs to take all the available space.";
                    }
                }
            }

            UText {
                text: "Menu";
                font-weight: 600;
            }

            VerticalLayout {
                alignment: start;
                padding-top: UAppTheme.padding-base;
                height: 120px;
                UMenu {
                    UMenuLink {
                        id: "home";
                        name: "Home";
                    }

                    UMenuLink {
                        id: "how-to-use";
                        name: "How to use";
                    }

                    UMenuLink {
                        id: "Theming";
                        name: "Theming";
                    }

                    UMenuLink {
                        id: "Color scheme";
                        name: "Color scheme";
                    }

                    UMenuSubmenu {
                        name: "Widgets";
                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "home 2";
                            name: "Home";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "how-to-use 2";
                            name: "How to use";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "Theming 2";
                            name: "Theming";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "Color scheme 2";
                            name: "Color scheme";
                        }

                        UMenuSubmenu {
                            name: "Sub widgets";
                            parent-child-opened <=> parent.child-opened;
                            UMenuLink {
                                parent-child-opened <=> parent.child-opened;
                                id: "Theming 3";
                                name: "Theming";
                            }

                            UMenuLink {
                                parent-child-opened <=> parent.child-opened;
                                id: "Color scheme 3";
                                name: "Color scheme";
                            }
                        }
                    }
                }
            }
        }
    }
}
