import { UBreadcrumb, UText, UTitle, UTabs } from "../sleek-ui/widgets.slint";
import { UAppTheme } from "../sleek-ui/app-theme.slint";
import { ScrollView, AboutSlint } from "std-widgets.slint";


export component Navigation {
    ScrollView {
        VerticalLayout {
            alignment: start;
            padding: 10px * UAppTheme.scale-factor;
            HorizontalLayout {
                alignment: start;
                padding-bottom: 36px * UAppTheme.scale-factor;
                UTitle {
                    level: 4;
                    text: "Navigation";
                }
            }

            UText {
                text: "Breadcrumb";
                font-weight: 600;
            }

            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-base;
                padding-top: UAppTheme.padding-base;
                padding-bottom: 24px * UAppTheme.scale-factor;
                UBreadcrumb {
                    steps: ["Home", "Settings", "User", "Confidentiality"];
                }
            }

            UText {
                text: "Tabs";
                font-weight: 600;
            }

            VerticalLayout {
                alignment: start;
                padding-top: UAppTheme.padding-base;
                height: 120px;
                UTabs {
                    tabs: ["France", "Germany", "United Kingdom", "Italy"];
                    if self.current-index == 0: VerticalLayout {
                        spacing: UAppTheme.spacing-base;
                        UText {
                            text: "Welcome to France!";
                        }

                        UText {
                            text: "You can put whatever you want in a tab's content.";
                        }
                    }
                    if self.current-index == 1: UText {
                        text: "Welcome to Germany!";
                    }
                    if self.current-index == 2: UText {
                        text: "Welcome to the United Kingdom!";
                    }
                    if self.current-index == 3: UText {
                        text: "Welcome to Italy!";
                    }
                }
            }

            VerticalLayout {
                alignment: start;
                padding-top: UAppTheme.padding-base;
                UTabs {
                    tabs-alignement: stretch;
                    tabs: ["France", "Germany", "United Kingdom", "Italy"];
                    if self.current-index == 0: UText {
                        text: "You can also enable the tabs to take all the available space.";
                    }
                    if self.current-index == 1: UText {
                        text: "You can also enable the tabs to take all the available space.";
                    }
                    if self.current-index == 2: UText {
                        text: "You can also enable the tabs to take all the available space.";
                    }
                    if self.current-index == 3: UText {
                        text: "You can also enable the tabs to take all the available space.";
                    }
                }
            }
        }
    }
}
