export { HomePage } from "home.slint";
export { HowToUsePage } from "how-to-use.slint";
export { ColorsPage } from "colors.slint";
export { ThemingPage } from "theming.slint";
export { AccessabilityPage } from "accessability.slint";
export { AboutPage } from "about.slint";

// General widgets
export { ButtonPage } from "widgets/button.slint";
export { DividerPage } from "widgets/divider.slint";
export { IconButtonPage } from "widgets/icon-button.slint";
export { FloatingButtonPage } from "widgets/floating-button.slint";
export { FloatingIconButtonPage } from "widgets/floating-icon-button.slint";
export { LinkPage } from "widgets/link.slint";
export { SpinnerPage } from "widgets/spinner.slint";

// Navigation widgets
export { BreadcrumbPage } from "widgets/breadcrumb.slint";
export { TabsPage } from "widgets/tabs.slint";
export { MenuPageHowTo } from "widgets/menu-how-to.slint";
export { MenuPageLink } from "widgets/menu-link.slint";
export { MenuPageSubmenu } from "widgets/menu-submenu.slint";
export { MenuPageGroupTitle } from "widgets/menu-group-title.slint";

// Data entry widgets
export { CheckboxPage } from "widgets/checkbox.slint";
export { InputPage } from "widgets/input.slint";
export { InputNumberPage } from "widgets/input-number.slint";
export { SelectPage } from "widgets/select.slint";
export { RadioPage } from "widgets/radio.slint";
export { RadioButtonPage } from "widgets/radio-button.slint";
export { SliderPage } from "widgets/slider.slint";
export { SwitchPage } from "widgets/switch.slint";

// Data display widgets
export { CardPage } from "widgets/card.slint";
export { CodePage } from "widgets/code.slint";
export { CollapsePage } from "widgets/collapse.slint";
export { IconPage } from "widgets/icon.slint";
export { LinearProgressPage } from "widgets/linear-progress.slint";
export { TagPage } from "widgets/tag.slint";
export { TextPage } from "widgets/text.slint";

// Structs
export { OptionDataPage } from "structs/option-data.slint";