import { UAppTheme } from "../sleek-ui/app-theme.slint";
import { UPrimaryColor } from "../sleek-ui/structs/theme.slint";
import {
    UDivider,
    UTitle,
    UText,
    USlider,
    UScrollView,
    ButtonInterface,
} from "../sleek-ui/widgets.slint";

import { DocTitle, DocSection, DocCode } from "../components/doc-widgets.slint";
import { PageBase } from "../components/page-base.slint";
import { AppLogic } from "../app-logic.slint";


component ColorDisplay inherits Rectangle {
    in-out property <string> name;
    in-out property <UPrimaryColor> theme-color;
    VerticalLayout {
        padding: UAppTheme.padding-base;
        padding-bottom: 0;
        spacing: UAppTheme.spacing-base;
        Rectangle {
            HorizontalLayout {
                spacing: UAppTheme.spacing-big;
                Rectangle {
                    width: 40px;
                    height: 30px;
                    background: theme-color.base;
                    border-radius: UAppTheme.radius-base;
                    border-width: UAppTheme.border-width-base;
                    border-color: UAppTheme.border;
                }

                VerticalLayout {
                    alignment: center;
                    color-name := UText {
                        text: name;
                        animate color { duration: UAppTheme.animation-duration; }
                    }
                }
            }

            touch := ButtonInterface {
                clicked => {
                    UAppTheme.light.primary = theme-color;
                    UAppTheme.dark.primary = theme-color;
                }
            }

            states [
                pressed when touch.pressed: {
                    color-name.color: theme-color.base;
                    background: theme-color.selected;
                }
                hover when touch.has-hover: {
                    background: theme-color.selected;
                }
            ]
        }

        HorizontalLayout {
            alignment: center;
            UDivider {
                width: 580px;
            }
        }
    }
}

export component SettingsPage inherits PageBase {
    private property <[{ name: string, color: UPrimaryColor}]> colors: [
        { name: "Dust red", color: UAppTheme.dust-red },
        { name: "Volcano", color: UAppTheme.volcano },
        { name: "Sunset orange", color: UAppTheme.sunset-orange },
        { name: "Calendula gold", color: UAppTheme.calendula-gold },
        { name: "Sunrise yellow", color: UAppTheme.sunrise-yellow },
        { name: "Lime", color: UAppTheme.lime },
        { name: "Polar green", color: UAppTheme.polar-green },
        { name: "Cyan", color: UAppTheme.cyan },
        { name: "Daybreak blue", color: UAppTheme.daybreak-blue },
        { name: "Geek blue", color: UAppTheme.geek-blue },
        { name: "Golden purple", color: UAppTheme.golden-purple },
        { name: "French magenta", color: UAppTheme.french-magenta },
    ];
    UTitle {
        level: 3;
        text: "Settings";
    }

    DocSection {
        title: "Primary color";
        description: [[{ text: "Change the current primary color." }]];
    }

    HorizontalLayout {
        alignment: start;
        padding-top: UAppTheme.padding-base;
        UScrollView {
            height: 200px;
            width: 600px;
            border-width: UAppTheme.border-width-base;
            border-color: UAppTheme.border;
            border-radius: UAppTheme.radius-base;
            VerticalLayout {
                for color[idx] in colors: ColorDisplay {
                    name: color.name;
                    theme-color: color.color;
                }
            }
        }
    }

    DocSection {
        title: "Scale factor";
        description: [
            [
                { text: "Change the application's scale factor using the slint's scale factor." }
            ]
        ];
    }

    HorizontalLayout {
        alignment: start;
        spacing: UAppTheme.spacing-big;
        padding-top: UAppTheme.padding-big;
        text-left := UText {
            text: "50%";
            font-weight: 600;
        }

        VerticalLayout {
            alignment: center;
            slider := USlider {
                width: 300px;
                value <=> AppLogic.scale-factor;
                min-value: 50;
                max-value: 200;
                step: 25;
                display-steps: true;
                released(value) => {
                    AppLogic.update-scale-factor(value);
                }
            }
        }

        UText {
            text: "200%";
            font-weight: 600;
        }
    }

    HorizontalLayout {
        alignment: start;
        padding-top: UAppTheme.padding-base;
        VerticalLayout {
            Text {
                x: text-left.width + slider.handle-pos;
                text: "\{AppLogic.scale-factor}%";
                font-weight: 600;
            }
        }
    }
}
