import { UAppTheme } from "../sleek-ui/app-theme.slint";
import { UTitle, UText, UCode, ULink } from "../sleek-ui/widgets.slint";

import { DocTitle } from "../components/doc-widgets.slint";
import { PageBase } from "../components/page-base.slint";
import { DocumentationLogic } from "../logic/documentation-logic.slint";


export component ThemingPage inherits PageBase {
    UTitle {
        level: 3;
        text: "Application theming";
    }

	// TODO Split this page into the following pages: use the application's theme with UAppTheme, modify the theme with ThemeConfig, Default colors.
}
