export struct USingleColor {
	light: brush,
	dark: brush,
}

export struct UVariantsColor {
	base: brush,
	hover: brush,
	active: brush,
	disabled: brush,
	selected: brush,
}


export struct UColorSchemeVariantsColor {
	light: UVariantsColor,
	dark: UVariantsColor,
}


export struct UThemeColors {
    // Main colors
    primary: UVariantsColor,
    success: UVariantsColor,
    warning: UVariantsColor,
    danger: UVariantsColor,

    // Background colors
    bg-layout: brush,
    bg-container: brush,
    bg-elevated: brush,
    bg-inverse: brush,

    // Fill colors
    color-fill-plus: brush,
    color-fill: brush,
    color-fill-secondary: brush,
    color-fill-tertiary: brush,
    color-fill-quaternary: brush,
	
    // Borders
    border: brush,
    border-secondary: brush,
    separator: brush,

    // Shadow
    shadow-color: brush,

    // Focus display
    focus-color: brush,

    // Text colors
    inverse-text: brush,
    text: brush,
    text-secondary: brush,
    text-heading: brush,
    text-disabled: brush,
}