import { USingleColor, UColorSchemeVariantsColor } from "../structs/colors.slint";

export struct UMainColorsStyle {
	primary: UColorSchemeVariantsColor,
	success: UColorSchemeVariantsColor,
	warning: UColorSchemeVariantsColor,
	danger: UColorSchemeVariantsColor,
}

export struct UBackgroundColorsStyle {
	layout: USingleColor,
	container: USingleColor,
	elevated: USingleColor,
	inverse: USingleColor,
}


export struct UFillColorsStyle {
    fill-plus: USingleColor,
    fill: USingleColor,
    fill-secondary: USingleColor,
    fill-tertiary: USingleColor,
    fill-quaternary: USingleColor,
}


export struct UShadowStyle {
    color: USingleColor,
    blur: length,
    x-offset: length,
    y-offset: length,
}

export struct UFocusStyle {
	color: USingleColor,
	border-width: length,
}


export struct UTextStyle {
    color-inverse: USingleColor,
    color: USingleColor,
    color-secondary: USingleColor,
    color-heading: USingleColor,
    color-disabled: USingleColor,
}

export struct UFontStyle {
    smaller: length,
    small: length,
    base: length,
    medium: length,
    big: length,
    bigger: length,
	icon-base-size: length,
}


export struct UBorderStyle {
	width: length,
    color: USingleColor,
    color-secondary: USingleColor,
    separator: USingleColor,
}


export struct UPaddingStyle {
    vertical: length,
    horizontal: length,
    small: length,
    base: length,
    medium: length,
    big: length,
    bigger: length,
}


export struct USpacingStyle {
    small: length,
    base: length,
    medium: length,
    big: length,
    bigger: length,
}

export struct URadiusStyle {
    small: length,
    base: length,
    medium: length,
    large: length,
    round: length,
    circle: length,
}