export struct ThemeColors {
    // Primary color.
    primary: brush,
    primary-hover: brush,
    primary-active: brush,
    primary-disabled: brush,
    primary-selected: brush,

    // Success color.
    success: brush,
    success-hover: brush,
    success-active: brush,
    success-disabled: brush,
    success-selected: brush,

    // Warning color.
    warning: brush,
    warning-hover: brush,
    warning-active: brush,
    warning-disabled: brush,
    warning-selected: brush,

    // Danger color.
    danger: brush,
    danger-hover: brush,
    danger-active: brush,
    danger-disabled: brush,
    danger-selected: brush,

    // Background color
    bg-container: brush,
    bg-elevated: brush,
    bg-layout: brush,
	bg-inverse: brush,

    // Color fill
    color-fill-plus: brush,
    color-fill: brush,
    color-fill-secondary: brush,
    color-fill-tertiary: brush,
    color-fill-quaternary: brush,

    // Shadow
    shadow-color: brush,

    // Text color
    inverse-text: brush,
    text: brush,
    text-secondary: brush,
    text-heading: brush,
    text-disabled: brush,

	// Focus display
    focus-color: brush,

    // Borders
    border: brush,
    border-secondary: brush,
    separator: brush,
}
