export struct ThemeColors {
    // Primary color.
    primary: color,
    primary-hover: color,
    primary-active: color,
    primary-disabled: color,
    primary-selected: color,

    // Success color.
    success: color,
    success-hover: color,
    success-active: color,
    success-disabled: color,
    success-selected: color,

    // Warning color.
    warning: color,
    warning-hover: color,
    warning-active: color,
    warning-disabled: color,
    warning-selected: color,

    // Danger color.
    danger: color,
    danger-hover: color,
    danger-active: color,
    danger-disabled: color,
    danger-selected: color,

    // Background color
    bg-container: color,
    bg-elevated: color,
    bg-layout: color,

    // Color fill
    color-fill-plus: color,
    color-fill: color,
    color-fill-secondary: color,
    color-fill-tertiary: color,
    color-fill-quaternary: color,

    // Shadow
    shadow-color: color,

    // Text color
    inverse-text: color,
    text: color,
    text-secondary: color,
    text-heading: color,
    text-disabled: color,

	// Focus display
    focus-color: color,

    // Borders
    border: color,
    border-secondary: color,
    separator: color,
}
