import { UAppTheme } from "../sleek-ui/app-theme.slint";
import { UText, UTitle, ULink, UCode } from "../sleek-ui/widgets.slint";


export component DocTitle {
    in property <string> text;
    HorizontalLayout {
        padding-top: UAppTheme.padding-bigger;
        padding-bottom: UAppTheme.padding-base;
        UTitle {
            level: 5;
            text: root.text;
        }
    }
}

export component DocDescription {
    in property <string> text;
    HorizontalLayout {
        padding-top: UAppTheme.padding-bigger;
        padding-bottom: UAppTheme.padding-base;
        UText {
            text: root.text;
        }
    }
}

export component WidgetPresentation {
    in property <bool> full-width: false;
    HorizontalLayout {
        width: 100%;
        alignment: full-width ? stretch : start;
        padding-top: UAppTheme.padding-big;
        padding-bottom: UAppTheme.padding-base;
        spacing: UAppTheme.spacing-base;
        @children
    }
}


// Elements for the description of DocSection.
struct DescStyledText {
	id: string,
	text: string,
	link: string,
	code: string,
}


export component DocSection {
    in property <string> title;
    in property <[[DescStyledText]]> description;
    callback link-clicked(id: string);
    VerticalLayout {
        DocTitle {
            text: root.title;
        }

        if description.length != 0: VerticalLayout {
            alignment: start;
            for line in description: HorizontalLayout {
                alignment: start;
                for item in line: HorizontalLayout {
                    alignment: start;
                    if item.text != "": UText {
                        text: item.text;
                        wrap: word-wrap;
                    }
                    if item.link != "": ULink {
                        text: item.link;
                        wrap: word-wrap;
                        clicked => root.link-clicked(item.id);
                    }
                    if item.code != "": UCode {
                        type: inline;
                        code: item.code;
                        wrap: word-wrap;
                    }
                }
            }
        }
    }
}
