import { UAppTheme } from "../sleek-ui/app-theme.slint";
import {
    UText,
    UTitle,
    ULink,
    UCode,
    UMenuLogic,
} from "../sleek-ui/widgets.slint";
import { SlintDocPageStyledText } from "../structs/doc-content.slint";
import { AppLogic } from "../app-logic.slint";


export component DocDescription inherits HorizontalLayout {
    in property <string> text;
    padding-top: UAppTheme.padding-bigger;
    padding-bottom: UAppTheme.padding-base;
    UText {
        text: root.text;
    }
}

export component DocCode inherits HorizontalLayout {
    in property <string> code;
    in property <bool> enable-clipboard;
    padding-top: UAppTheme.padding-base;
    UCode {
        code: root.code;
        enable-clipboard: root.enable-clipboard;
    }
}

export component WidgetPresentation inherits HorizontalLayout {
    in property <bool> full-width: false;
    width: 100%;
    alignment: full-width ? stretch : start;
    padding-top: UAppTheme.padding-big;
    padding-bottom: UAppTheme.padding-base;
    spacing: UAppTheme.spacing-base;
    @children
}

export component DocSection inherits Rectangle {
    in property <string> title;
    in property <[[SlintDocPageStyledText]]> description;
    in-out property <string> widget-id;
    in-out property <string> code;
    private property <duration> bg-animation: 0;
    callback link-clicked(url: string);
    animate background { duration: bg-animation; }
    public function trigger-signal() {
        self.bg-animation = 0;
        self.background = Colors.yellow.with-alpha(0.8);
        echo-timer.start();
    }
    VerticalLayout {
        padding-top: UAppTheme.padding-big;
        if title != "": HorizontalLayout {
            in property <string> text;
            padding-top: UAppTheme.padding-bigger;
            padding-bottom: UAppTheme.padding-base;
            UTitle {
                level: 5;
                text: root.title;
            }
        }
        if description.length != 0: VerticalLayout {
            alignment: start;
            for line in description: HorizontalLayout {
                alignment: start;
                for stext in line: HorizontalLayout {
                    alignment: start;
                    if stext.text != "": UText {
                        text: stext.text;
                    }
                    if stext.link != "": ULink {
                        text: stext.link;
                        clicked => {
                            if stext.local {
                                UMenuLogic.current-link = stext.url;
                            } else {
                                AppLogic.open-url(stext.url)
                            }
                        }
                    }
                    if stext.code != "": UCode {
                        type: inline;
                        code: stext.code;
                    }
                }
            }
        }

		// TODO Implement widget ID selection

		if code != "": DocCode {
            code: root.code;
        }
    }

    echo-timer := Timer {
        running: false;
        interval: 10ms;
        triggered => {
            root.bg-animation = 2s;
            root.background = Colors.transparent;
            self.stop();
        }
    }
}
