import { UMenuLogic } from "../sleek-ui/widgets.slint";

import {
    HomePage,
    HowToUsePage,
    ColorsPage,
    ThemingPage,

	// General widgets.
    ButtonPage,
    DividerPage,
    IconButtonPage,
    FloatingButtonPage,
    FloatingIconButtonPage,
    LinkPage,
    SpinnerPage,

	// Navigation widgets.
	BreadcrumbPage,
} from "../pages/page-index.slint";


export component PageManager {
    in property <string> current-page: UMenuLogic.current-link;
    VerticalLayout {
        alignment: start;
        if current-page == "home": HomePage { }
        if current-page == "how-to-use": HowToUsePage { }
        if current-page == "default-colors": ColorsPage { }
        if current-page == "theming": ThemingPage { }
		
		// General widgets
        if current-page == "button": ButtonPage { }
        if current-page == "divider": DividerPage { }
        if current-page == "icon-button": IconButtonPage { }
        if current-page == "floating-button": FloatingButtonPage { }
        if current-page == "floating-icon-button": FloatingIconButtonPage { }
        if current-page == "link": LinkPage { }
        if current-page == "spinner": SpinnerPage { }

		// Navigation widgets
		if current-page == "breadcrumb": BreadcrumbPage { }
    }
}
