import { ScrollView } from "std-widgets.slint";
import { UAppTheme } from "../sleek-ui/app-theme.slint";
import { UScrollview } from "../sleek-ui/widgets.slint";


export component PageBase {
    height: 100%;
    UScrollview {
        VerticalLayout {
            alignment: start;
            padding: UAppTheme.padding-big;
            padding-top: UAppTheme.padding-bigger;
            @children
        }
    }
}
