import { UAppTheme } from "../sleek-ui/app-theme.slint";
import {
    UDivider,
    UText,
    UTitle,
    UMenu,
    UMenuLink,
    UMenuSubmenu,
    UMenuGroupTitle,
    UScrollView,
} from "../sleek-ui/widgets.slint";
import { ScrollView } from "std-widgets.slint";


export component Sidebar inherits Rectangle {
    width: 250px;
    HorizontalLayout {
        UScrollView {
            width: root.width;
            VerticalLayout {
                width: root.width;
                padding-bottom: 24px;
                UMenu {
                    current-link: "home";
                    UMenuLink {
                        id: "home";
                        name: "Home";
                    }

                    UMenuLink {
                        id: "how-to-use";
                        name: "How to use";
                    }

                    UMenuLink {
                        id: "theming";
                        name: "Theming";
                    }

                    UMenuLink {
                        id: "default-colors";
                        name: "Default colors";
                    }

                    UMenuLink {
                        id: "accessability";
                        name: "Accessability";
                    }

                    UMenuSubmenu {
                        name: "Widgets";
                        opened: true;
                        UMenuGroupTitle {
                            title: "General";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "button";
                            name: "Button";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "divider";
                            name: "Divider";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "icon-button";
                            name: "Icon button";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "floating-button";
                            name: "Floating button";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "floating-icon-button";
                            name: "Floating icon button";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "link";
                            name: "Link";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "spinner";
                            name: "Spinner";
                        }

                        UMenuGroupTitle {
                            title: "Navigation";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "breadcrumb";
                            name: "Breadcrumb";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "tabs";
                            name: "Tabs";
                        }

                        UMenuSubmenu {
                            parent-child-opened <=> parent.child-opened;
                            name: "Menu";
                            UMenuLink {
                                parent-child-opened <=> parent.child-opened;
                                id: "menu-how-to";
                                name: "How to use";
                            }

                            UMenuLink {
                                parent-child-opened <=> parent.child-opened;
                                id: "menu-link";
                                name: "Menu link";
                            }

                            UMenuLink {
                                parent-child-opened <=> parent.child-opened;
                                id: "menu-submenu";
                                name: "Menu submenu";
                            }

                            UMenuLink {
                                parent-child-opened <=> parent.child-opened;
                                id: "menu-group-title";
                                name: "Menu group title";
                            }
                        }

                        UMenuGroupTitle {
                            title: "Data entry";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "checkbox";
                            name: "Checkbox";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "input";
                            name: "Input";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "input-number";
                            name: "Input number";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "select";
                            name: "Select";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "radio";
                            name: "Radio";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "radio-button";
                            name: "Radio button";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "slider";
                            name: "Slider";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "switch";
                            name: "Switch";
                        }

                        UMenuGroupTitle {
                            title: "Data display";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "card";
                            name: "Card";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "code";
                            name: "Code";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "collapse";
                            name: "Collapse";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "icon";
                            name: "Icon";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "linear-progress";
                            name: "Linear progress";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "tag";
                            name: "Tag";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "text";
                            name: "Text";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "title";
                            name: "Title";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "tooltip";
                            name: "Tooltip";
                        }

                        UMenuGroupTitle {
                            title: "Feedback";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "alert";
                            name: "Alert";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "modal";
                            name: "Modal";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "notification";
                            name: "Notification";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "popover";
                            name: "Popover";
                        }

                        UMenuGroupTitle {
                            title: "Misc";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "button-interface";
                            name: "Button interface";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "center-layout";
                            name: "Center layout";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "scrollview";
                            name: "Scrollview";
                        }
                    }

                    UMenuSubmenu {
                        name: "Structs";
                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "option-data";
                            name: "OptionData";
                        }
                    }

                    UMenuLink {
                        id: "settings";
                        name: "Settings";
                    }

                    UMenuLink {
                        id: "about";
                        name: "About";
                    }
                }
            }
        }

        UDivider {
            orientation: vertical;
            height: 100%;
        }
    }
}
