import { UAppTheme } from "../sleek-ui/app-theme.slint";
import { UDivider, UText, UTitle } from "../sleek-ui/widgets.slint";


export global SidebarLogic {
    in-out property <string> current-page: "Controls";
}

export component Sidebar inherits Rectangle {
    width: 200px * UAppTheme.scale-factor;
    HorizontalLayout {
        VerticalLayout {
            alignment: start;
            horizontal-stretch: 1;
            HorizontalLayout {
                padding: UAppTheme.padding-base;
                padding-top: UAppTheme.padding-big;
                UTitle {
                    horizontal-alignment: center;
                    level: 5;
                    text: "Sleek-ui Widgets Gallery";
                    font-weight: 600;
                    wrap: word-wrap;
                }
            }

            Rectangle {
                height: 40px;
            }

            for link in ["Controls", "Data display", "Feedback", "Navigation", "About"]: HorizontalLayout {
                padding: UAppTheme.padding-small;
                Rectangle {
                    border-radius: UAppTheme.radius-base;
                    HorizontalLayout {
                        padding: 6px;
                        UText {
                            text: link;
                            animate color { duration: UAppTheme.animation-duration; }
                            states [
                                active when SidebarLogic.current-page == link: {
                                    color: UAppTheme.primary.base;
                                }
                            ]
                        }
                    }

                    ctrls-touch := TouchArea {
                        clicked => {
                            SidebarLogic.current-page = link;
                        }
                    }

                    animate background { duration: UAppTheme.animation-duration; }
                    states [
                        active when SidebarLogic.current-page == link: {
                            background: UAppTheme.primary.selected;
                        }
                        hover when ctrls-touch.has-hover: {
                            background: UAppTheme.color-fill-secondary;
                        }
                    ]
                }
            }
        }

        UDivider {
            orientation: vertical;
            height: 100%;
        }
    }
}
