import { UAppTheme } from "../sleek-ui/app-theme.slint";
import {
    UDivider,
    UText,
    UTitle,
    UMenu,
    UMenuLink,
    UMenuSubmenu,
    UMenuGroupTitle,
    UScrollView,
} from "../sleek-ui/widgets.slint";
import { ScrollView } from "std-widgets.slint";


export component Sidebar inherits Rectangle {
    width: 250px;
    HorizontalLayout {
        UScrollView {
            width: parent.width;
            VerticalLayout {
                padding: UAppTheme.padding-base;
                padding-right: parent.scrollbar-area;
                padding-bottom: 32px;
                UMenu {
                    current-link: "home";
                    UMenuLink {
                        id: "home";
                        name: "Home";
                    }

                    UMenuLink {
                        id: "how-to-use";
                        name: "How to use";
                    }

                    UMenuLink {
                        id: "theming";
                        name: "Theming";
                    }

                    UMenuLink {
                        id: "default-colors";
                        name: "Default colors";
                    }

                    UMenuLink {
                        id: "accessability";
                        name: "Accessability";
                    }

                    UMenuSubmenu {
                        name: "Widgets";
                        opened: true;
                        UMenuGroupTitle {
                            title: "General";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "widgets/button";
                            name: "Button";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "widgets/divider";
                            name: "Divider";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "widgets/icon-button";
                            name: "Icon button";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "widgets/floating-button";
                            name: "Floating button";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "widgets/floating-icon-button";
                            name: "Floating icon button";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "widgets/link";
                            name: "Link";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "widgets/spinner";
                            name: "Spinner";
                        }

                        UMenuGroupTitle {
                            title: "Navigation";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "widgets/breadcrumb";
                            name: "Breadcrumb";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "widgets/tabs";
                            name: "Tabs";
                        }

                        UMenuSubmenu {
                            parent-child-opened <=> parent.child-opened;
                            name: "Menu";
                            UMenuLink {
                                parent-child-opened <=> parent.child-opened;
                                id: "widgets/menu-how-to";
                                name: "How to use";
                            }

                            UMenuLink {
                                parent-child-opened <=> parent.child-opened;
                                id: "widgets/menu-link";
                                name: "Menu link";
                            }

                            UMenuLink {
                                parent-child-opened <=> parent.child-opened;
                                id: "widgets/menu-submenu";
                                name: "Menu submenu";
                            }

                            UMenuLink {
                                parent-child-opened <=> parent.child-opened;
                                id: "widgets/menu-group-title";
                                name: "Menu group title";
                            }
                        }

                        UMenuGroupTitle {
                            title: "Data entry";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "widgets/checkbox";
                            name: "Checkbox";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "widgets/input";
                            name: "Input";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "widgets/input-number";
                            name: "Input number";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "widgets/select";
                            name: "Select";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "widgets/radio";
                            name: "Radio";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "widgets/radio-button";
                            name: "Radio button";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "widgets/slider";
                            name: "Slider";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "widgets/switch";
                            name: "Switch";
                        }

                        UMenuGroupTitle {
                            title: "Data display";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "widgets/card";
                            name: "Card";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "widgets/code";
                            name: "Code";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "widgets/collapse";
                            name: "Collapse";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "widgets/icon";
                            name: "Icon";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "widgets/linear-progress";
                            name: "Linear progress";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "widgets/tag";
                            name: "Tag";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "widgets/text";
                            name: "Text";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "widgets/title";
                            name: "Title";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "widgets/tooltip";
                            name: "Tooltip";
                        }

                        UMenuGroupTitle {
                            title: "Feedback";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "widgets/alert";
                            name: "Alert";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "widgets/modal";
                            name: "Modal";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "widgets/notification";
                            name: "Notification";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "widgets/popover";
                            name: "Popover";
                        }

                        UMenuGroupTitle {
                            title: "Misc";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "widgets/button-interface";
                            name: "Button interface";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "widgets/scrollview";
                            name: "Scrollview";
                        }

                        UMenuGroupTitle {
                            title: "Structs";
                        }

                        UMenuLink {
                            parent-child-opened <=> parent.child-opened;
                            id: "widgets/option-data";
                            name: "OptionData";
                        }
                    }

                    UMenuLink {
                        id: "settings";
                        name: "Settings";
                    }

                    UMenuLink {
                        id: "about";
                        name: "About";
                    }
                }
            }
        }

        UDivider {
            orientation: vertical;
            height: 100%;
        }
    }
}
