import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import { UTitle } from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { AppLogic } from "../../app-logic.slint";


export component OptionDataPage inherits PageBase {
    UTitle {
        level: 3;
        text: "UOptionData";
    }

    DocDescription {
        text: "A struct used to define the choices in a select or radio.";
    }

    DocSection {
        title: "Definition";
        description: @markdown("The struct can be imported from the [@sleek-ui/common.slint](https://github.com/uAtomicBoolean/sleek-ui/blob/main/ui/sleek-ui/common.slint) file.");
        link-clicked(url) => {
            Platform.open-url(url);
        }
    }

    DocCode {
        code: "UOptionData {\n    // The visual text of the value.\n    text: string,\n\n    // The value that can be used in your logic to check the current value.\n    value: string,\n\n    // Whether the option is enabled or not.\n    // A disabled option will be greyed out and not selectable.\n    // Note that you must set it to true as the default value of a boolean in Slint is false.\n    enabled: bool,\n}";
    }
}
