export component UCenter {
	// Vertical layout properties.
    in-out property <length> u-spacing <=> h-layout.spacing;
    in-out property <length> u-padding <=> h-layout.padding;
    in-out property <length> u-padding-top <=> h-layout.padding-top;
    in-out property <length> u-padding-bottom <=> h-layout.padding-bottom;
    in-out property <length> u-padding-left <=> h-layout.padding-left;
    in-out property <length> u-padding-right <=> h-layout.padding-right;
    VerticalLayout {
        alignment: center;
        h-layout := HorizontalLayout {
            alignment: center;
            @children
        }
    }
}
