export component UCenter {
	// Vertical layout properties.
    in-out property <LayoutAlignment> v-alignment: center;
    in-out property <LayoutAlignment> h-alignment: center;
    in-out property <length> u-spacing <=> h-layout.spacing;
    in-out property <length> u-padding <=> h-layout.padding;
    in-out property <length> u-padding-top <=> h-layout.padding-top;
    in-out property <length> u-padding-bottom <=> h-layout.padding-bottom;
    in-out property <length> u-padding-left <=> h-layout.padding-left;
    in-out property <length> u-padding-right <=> h-layout.padding-right;
    v-layout := VerticalLayout {
        alignment: v-alignment;
        h-layout := HorizontalLayout {
            alignment: h-alignment;
            @children
        }
    }
}
