import { Palette } from "std-widgets.slint";

import { UAppTheme } from "../../app-theme.slint";


export enum UMenuVariant {
	light,
	dark,
}


export global UMenuLogic {
    in-out property <UMenuVariant> variant;
    in-out property <string> current-link;
}

export struct UMenuLinkTheme {
	text: brush,
	text-selected: brush,
	text-disabled: brush,
	bg-hover: brush,
	bg-selected: brush,
}

export global UMenuLinkThemes {
	// private property <ColorScheme> variant-cs: {
    //     if UMenuLogic.variant == UMenuVariant.dark {
    //         return Palette.color-scheme == light ? dark : light;
    //     }
    //     return Palette.color-scheme == dark ? dark : light;
    // };
    out property <UMenuLinkTheme> light: {
        text: UAppTheme.text,
        text-selected: UAppTheme.primary.base,
        text-disabled: UAppTheme.text-disabled,
        bg-hover: UAppTheme.color-fill-secondary,
        bg-selected: UAppTheme.primary.selected,
    };
    // out property <UMenuLinkTheme> dark: {
    //     text: variant-cs == ColorScheme.dark ? UAppTheme.light.text : UAppTheme.dark.text,
    //     text-selected: variant-cs == ColorScheme.dark ? UAppTheme.light.primary.base : UAppTheme.dark.primary.base,
    //     text-disabled: variant-cs == ColorScheme.dark ? UAppTheme.light.text-disabled : UAppTheme.dark.text-disabled,
    //     bg-hover: variant-cs == ColorScheme.dark ? UAppTheme.light.color-fill-secondary : UAppTheme.dark.color-fill-secondary,
    //     bg-selected: variant-cs == ColorScheme.dark ? UAppTheme.light.primary.selected : UAppTheme.dark.primary.selected,
    // };
}
