import { Palette } from "std-widgets.slint";

import { UAppTheme } from "../../app-theme.slint";

import { UMenuLogic, UMenuVariant } from "index.slint";
import { UMenuLink } from "menu-link.slint";
import { UMenuSubmenu } from "menu-submenu.slint";
import { UMenuGroupTitle } from "menu-group-title.slint";


export { UMenuVariant, UMenuLink, UMenuGroupTitle, UMenuSubmenu }

export component UMenu inherits Rectangle {
    in-out property <UMenuVariant> variant: inverse;
    in-out property <string> current-link;
    init => {
        UMenuLogic.variant = variant;
    }
    changed variant => {
        UMenuLogic.variant = variant;
    }
    function get-background() -> brush {
        if variant == UMenuVariant.inverse {
            return Palette.color-scheme == ColorScheme.light ? UAppTheme.dark.primary.active : UAppTheme.light.bg-container;
        }
        return UAppTheme.bg-container;
    }
    background: get-background();
    VerticalLayout {
        alignment: start;
        @children
    }
}
