import { Palette } from "std-widgets.slint";

import { UAppTheme } from "../../app-theme.slint";

import { UMenuLogic, UMenuVariant } from "index.slint";
import { UMenuLink } from "menu-link.slint";
import { UMenuSubmenu } from "menu-submenu.slint";
import { UMenuGroupTitle } from "menu-group-title.slint";


export { UMenuVariant, UMenuLink, UMenuGroupTitle, UMenuSubmenu }

export component UMenu inherits Rectangle {
    in-out property <UMenuVariant> variant: default;
    in-out property <string> current-link;
    init => {
        UMenuLogic.variant = variant;
    }
    changed variant => {
        UMenuLogic.variant = variant;
    }
    background: self.variant == UMenuVariant.default ? UAppTheme.bg-container : UAppTheme.primary.active;
    VerticalLayout {
        alignment: start;
        @children
    }
}
