import { UAppTheme } from "../../app-theme.slint";

import { UText } from "../text.slint";
import { ButtonInterface } from "../button-interface.slint";

import {
    UMenuLogic,
    UMenuVariant,
    UMenuLinkTheme,
    UMenuLinkThemes,
} from "index.slint";


export component UMenuLink inherits Rectangle {
    private property <UMenuLinkTheme> theme: UMenuLogic.variant == UMenuVariant.default ? UMenuLinkThemes.default : UMenuLinkThemes.primary;
    in-out property <string> id;
    in-out property <string> name;
    in-out property <string> parent-id;
    in-out property <bool> enabled: true;
    out property <bool> is-selected: UMenuLogic.current-link == id;
    callback activated();
    ButtonInterface {
        enabled: root.enabled;
        clicked => {
            UMenuLogic.current-link = id;
            root.activated();
        }
        border-radius: UAppTheme.radius-base;
        HorizontalLayout {
            alignment: space-between;
            padding: UAppTheme.padding-base;
            padding-top: UAppTheme.padding-vertical;
            padding-bottom: UAppTheme.padding-vertical;
            padding-left: UAppTheme.padding-horizontal;
            padding-right: UAppTheme.padding-horizontal;
            link-text := UText {
                text: name;
                overflow: elide;
                color: theme.text;
            }
        }

        states [
            disabled when !root.enabled: {
                link-text.color: theme.text-disabled;
            }
            focus-selected when self.has-focus && root.is-selected: {
                background: theme.bg-selected;
                link-text.color: theme.text-selected;
                border-color: UAppTheme.focus-color;
                border-width: UAppTheme.focus-border-width;
            }
            selected when root.is-selected: {
                background: theme.bg-selected;
                link-text.color: theme.text-selected;
            }
            focus-hover when self.has-focus && self.has-hover: {
                border-color: UAppTheme.focus-color;
                border-width: UAppTheme.focus-border-width;
                background: theme.bg-hover;
            }
            hover when self.has-hover: {
                background: theme.bg-hover;
            }
            focus when self.has-focus: {
                border-color: UAppTheme.focus-color;
                border-width: UAppTheme.focus-border-width;
            }
        ]
    }
}
