import { UAppTheme } from "../../app-theme.slint";
import { ButtonInterface } from "../button-interface.slint";
import { UText } from "../text.slint";
import { UIcon } from "../icon.slint";

import { UMenuLink, UMenuSubmenu } from "menu-items.slint";
import { UMenuData, UMenuItemType } from "structs.slint";


export { UMenuData, UMenuItemType }


export component UMenu {
    in-out property <[UMenuData]> items;
    in-out property <string> current-link;
    private property <string> current-submenu;

    VerticalLayout {
        for item in items: VerticalLayout {
            if item.type == UMenuItemType.link: UMenuLink {
                menu-current-link <=> current-link;
                menu-current-submenu <=> current-submenu;
                id: item.id;
                name: item.name;
            }
            if item.type == UMenuItemType.submenu: UMenuSubmenu {
                menu-current-link <=> current-link;
                menu-current-submenu <=> current-submenu;
                id: item.id;
                name: item.name;
                children: item.children;
            }
        }
    }
}
