/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const main: () => void;
export const send_keyboard_string_sequence: (a: number, b: number) => void;
export const slint_get_mocked_time: () => bigint;
export const slint_mock_elapsed_time: (a: bigint) => void;
export const slint_send_keyboard_char: (a: number, b: number, c: number) => void;
export const slint_send_keyboard_key_text: (a: number, b: number, c: number) => void;
export const slint_send_mouse_click: (a: number, b: number, c: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h0998c1391c08d896: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__hf67f9e5f0aacf325: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h10aec86cb6717fac: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h10aec86cb6717fac_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h503a73df7e0837b4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h503a73df7e0837b4_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h503a73df7e0837b4_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h10aec86cb6717fac_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h10aec86cb6717fac_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h503a73df7e0837b4_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h503a73df7e0837b4_10: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h10aec86cb6717fac_11: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h10aec86cb6717fac_12: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h10aec86cb6717fac_13: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h503a73df7e0837b4_14: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h10aec86cb6717fac_15: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h6ca00e857044532d: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
