/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const main: () => void;
export const wasm_bindgen__convert__closures_____invoke__h9422eaf7acb520a9: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__hef6c2db803679121: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0398934a1a9fdbdb: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0398934a1a9fdbdb_12: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0398934a1a9fdbdb_13: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0398934a1a9fdbdb_14: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0398934a1a9fdbdb_16: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0398934a1a9fdbdb_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0398934a1a9fdbdb_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0398934a1a9fdbdb_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h37e588a8c1ac94b4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h37e588a8c1ac94b4_10: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h37e588a8c1ac94b4_11: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h37e588a8c1ac94b4_15: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h37e588a8c1ac94b4_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h37e588a8c1ac94b4_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hb93a506091da2d80: (a: number, b: number, c: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h1161ce032f23deab: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hd042dfea9f44b3da: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
