/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const main: () => void;
export const send_keyboard_string_sequence: (a: number, b: number) => void;
export const slint_get_mocked_time: () => bigint;
export const slint_mock_elapsed_time: (a: bigint) => void;
export const slint_send_keyboard_char: (a: number, b: number, c: number) => void;
export const slint_send_keyboard_key_text: (a: number, b: number, c: number) => void;
export const slint_send_mouse_click: (a: number, b: number, c: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h5823a62a601cdd8e: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h5e7098a2e5e4d79b: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h93a2feca5808bbb8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h93a2feca5808bbb8_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1228acebca57adff: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1228acebca57adff_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1228acebca57adff_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h93a2feca5808bbb8_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h93a2feca5808bbb8_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1228acebca57adff_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1228acebca57adff_10: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h93a2feca5808bbb8_11: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h93a2feca5808bbb8_12: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h93a2feca5808bbb8_13: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1228acebca57adff_14: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h93a2feca5808bbb8_15: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h8d27705fb5bcaf3e: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
