import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import { UTitle, UAlert } from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { AppLogic } from "../../app-logic.slint";


export component AlertPage inherits PageBase {
    UTitle {
        level: 3;
        text: "Alert";
    }

    DocDescription {
        text: "An alert to display an informational message.";
    }

    DocSection {
        title: "How to use";
        description: [
            [
                { text: "The alert widget comes with four variants: " },
                { code: "info (default)" },
                { text: ", " },
                { code: "success" },
                { text: ", " },
                { code: "warning" },
                { text: " and " },
                { code: "danger" },
                { text: "." }
            ],
            [
                { text: "The message property is of type " },
                { code: "styled-text" },
                { text: " so that you can include rich text formatting." }
            ],
            [
                { text: "You can use the " },
                { code: "link-clicked" },
                { text: " callback to handle clicks on links in the message." }
            ]
        ];
    }

    WidgetPresentation {
        full-width: true;
        VerticalLayout {
            spacing: UAppTheme.spacing-base;
            UAlert {
                message: @markdown("This is an info alert.");
            }

            UAlert {
                variant: success;
                message: @markdown("This is an success alert.");
            }

            UAlert {
                variant: warning;
                message: @markdown("This is an warning alert.");
            }

            UAlert {
                variant: danger;
                message: @markdown("This is an danger alert with a [link that redirects to nothing]().");
            }
        }
    }

    DocCode {
        code: "UAlert {\n    message: @markdown(\"This is an info alert.\");\n}\n\nUAlert {\n    variant: success;\n    message: @markdown(\"This is a success alert.\");\n}\n\nUAlert {\n    variant: warning;\n    message: @markdown(\"This is a warning alert.\");\n}\n\nUAlert {\n    variant: danger;\n    message: @markdown(\"This is a danger alert with a [link that redirects to nothing]().\");\n    link-clicked(link) => {\n        // Your code.\n    }\n}";
    }

    DocSection {
        title: "Close button";
        description: [
            [
                { text: "You can display a close button in the alert with the " },
                { code: "display-close-button" },
                { text: " property." }
            ],
            [{ text: "This button will fire the " }, { code: "close" }, { text: " callback." }]
        ];
    }

    WidgetPresentation {
        full-width: true;
        UAlert {
            display-close-button: true;
            message: @markdown("This is an alert.");
            close => {
                debug("Closing the alert.");
            }
        }
    }

    DocCode {
        code: "UAlert {\n    message: @markdown(\"This is an alert.\");\n    close => {\n        // Your code.\n    }\n}";
    }

    DocSection {
        title: "Custom colors and icon";
        description: [
            [
                { text: "You can use custom colors with the " },
                { code: "border-color" },
                { text: ", " },
                { code: "background" },
                { code: "icon-color" },
                { text: " and " },
                { code: "text-color" },
                { text: " properties." },
            ],
            [
                { text: "You can set a custom icon with the " },
                { code: "icon" },
                { text: " property." },
            ]
        ];
    }

    WidgetPresentation {
        full-width: true;
        UAlert {
            message: @markdown("Alert using custom colors");
            background: UAppTheme.golden-purple.selected;
            border-color: UAppTheme.golden-purple.base;
            text-color: UAppTheme.golden-purple.base;
            icon: @image-url("../../assets/images/rocket.svg");
            icon-color: UAppTheme.golden-purple.base;
            display-close-button: true;
        }
    }

    DocCode {
        code: "UAlert {\n    message: @markdown(\"This is an alert.\");\n    background: UAppTheme.golden-purple.selected;\n    border-color: UAppTheme.golden-purple.base;\n    text-color: UAppTheme.golden-purple.base;\n    icon: @image-url(your-path);\n    icon-color: UAppTheme.golden-purple.base;\n}";
    }
}
