import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import { UTitle, UButton } from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { AppLogic } from "../../app-logic.slint";


export component ButtonPage inherits PageBase {
    UTitle {
        level: 3;
        text: "Button";
    }

    DocDescription {
        text: "A simple button to execute an action on click.";
    }

    DocSection {
        title: "Simple buttons";
        description: [
            [
                {
                    text: "The button widget comes with 4 variants: primary, default, filled and text."
                }
            ]
        ];
    }

    WidgetPresentation {
        UButton {
            variant: primary;
            text: "Primary";
        }

        UButton {
            text: "Default";
        }

        UButton {
            variant: filled;
            text: "Filled";
        }

        UButton {
            variant: text;
            text: "Text";
        }
    }

    DocCode {
        code: "UButton {\n    variant: primary;\n    text: \"Primary\";\n}";
    }

    DocSection {
        title: "Disabled buttons";
    }

    WidgetPresentation {
        UButton {
            enabled: false;
            variant: primary;
            text: "Primary";
        }

        UButton {
            enabled: false;
            text: "Default";
        }

        UButton {
            enabled: false;
            variant: filled;
            text: "Filled";
        }

        UButton {
            enabled: false;
            variant: text;
            text: "Text";
        }
    }

    DocCode {
        code: "UButton {\n    enabled: false;\n    text: \"Disabled\";\n}";
    }

    DocSection {
        title: "Icons";
        description: [[{ text: "Display an icon either at the start or the end of the button." }]];
    }

    WidgetPresentation {
        UButton {
            variant: primary;
            text: "Primary";
            icon: @image-url("../../assets/images/plus.svg");
            icon-placement: start;
        }

        UButton {
            text: "Default";
            icon: @image-url("../../assets/images/search.svg");
            icon-placement: end;
        }
    }

    DocCode {
        code: "UButton {\n    icon: @image-url(\"url-to-image\");\n    icon-placement: start;\n    text: \"Danger\";\n}";
    }

    DocSection {
        title: "Colored icons";
        description: [[{ text: "Keep the original color of your icons." }]];
    }

    WidgetPresentation {
        UButton {
            variant: primary;
            text: "Primary";
            icon: @image-url("../../assets/images/rocket.svg");
            colorize-icon: false;
            icon-placement: start;
        }
    }

    DocCode {
        code: "UButton {\n    icon: @image-url(\"url-to-image\");\n    icon-placement: start;\n    colorize-icon: false;\n    text: \"Danger\";\n}";
    }

    DocSection {
        title: "Loading buttons";
        description: [[{ text: "A loading state in which the button is not interactive." }]];
    }

    WidgetPresentation {
        UButton {
            loading: true;
            variant: primary;
            text: "Primary";
        }

        UButton {
            loading: true;
            text: "Default";
        }

        UButton {
            loading: true;
            variant: filled;
            text: "Filled";
        }

        UButton {
            loading: true;
            variant: text;
            text: "Text";
        }
    }

    DocCode {
        code: "UButton {\n    loading: true;\n    text: \"Loading\";\n}";
    }

    DocSection {
        title: "Danger mode";
        description: [
            [
                {
                    text: "Change the button's color to the danger color of the theme. It is compatible with all the other states."
                }
            ]
        ];
    }

    WidgetPresentation {
        UButton {
            danger: true;
            variant: primary;
            text: "Primary";
        }

        UButton {
            danger: true;
            text: "Default";
        }

        UButton {
            danger: true;
            variant: filled;
            text: "Filled";
        }

        UButton {
            danger: true;
            variant: text;
            text: "Text";
        }
    }

    DocCode {
        code: "UButton {\n    danger: true;\n    text: \"Danger\";\n}";
    }

    DocSection {
        title: "Checked button";
        description: [
            [
                {
                    text: "A state in which the button keeps a different looks even on hover and active events."
                }
            ]
        ];
    }

    WidgetPresentation {
        UButton {
            checked: true;
            variant: primary;
            text: "Primary";
            clicked => {
                self.checked = !self.checked;
            }
        }

        UButton {
            checked: true;
            text: "Default";
            clicked => {
                self.checked = !self.checked;
            }
        }

        UButton {
            checked: true;
            variant: filled;
            text: "Filled";
            clicked => {
                self.checked = !self.checked;
            }
        }

        UButton {
            checked: true;
            variant: text;
            text: "Text";
            clicked => {
                self.checked = !self.checked;
            }
        }
    }

    DocCode {
        code: "UButton {\n    checked: true;\n    text: \"Checked\";\n}";
    }
}
