import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import { UTitle } from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { AppLogic } from "../../app-logic.slint";


export component ButtonInterfacePage inherits PageBase {
    UTitle {
        level: 3;
        text: "Button interface";
    }

    DocDescription {
        text: "A widget that is used to build interactive widgets with an implementation of both TouchArea and FocusScope.";
    }

    DocSection {
        title: "Enabled and mouse cursor";
        description-md: @markdown("The `enabled` property enables/disables both the FocusScope and the TouchArea.");
    }

    DocSection {
        title: "TouchArea implementation";
        description-md: @markdown("All the properties and callbacks are available in the `ButtonInterface`.");
    }

    DocSection {
        title: "FocusScope implementation";
        description-md: @markdown(
			"With the exception of the `focus()` and `clear-focus()` functions, all the properties, callbacks and functions are available.\n"
			"However, the `set-focus()` and `release-focus()` functions are available to manage the focus on the interface."
		);
    }

    DocSection {
        title: "The has-tab-focus property";
        description-md: @markdown(
			"The `has-tab-focus` property allows you to know when a widget gains the focus from a tab navigation.\n"
			"This means that a widget can get the focus while this property keeps being false.\n"
			"In sleek-ui, this property is used to display the focus when navigating with tab, and to focus a widget without displaying the keyboard focus style."
		);
    }
}
