import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import {
    UText,
    UTitle,
    UCard,
} from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { AppLogic } from "../../app-logic.slint";


export component CardPage inherits PageBase {
    UTitle {
        level: 3;
        text: "Card";
    }

    DocDescription {
        text: "A simple card container.";
    }

    DocSection {
        title: "Example";
        description: [
            [{ text: "A card is basically a Rectangle with some predefined properties." }],
        ];
    }

    WidgetPresentation {
        UCard {
            VerticalLayout {
                spacing: UAppTheme.spacing-base;
                padding: UAppTheme.padding-base;
                UText {
                    text: "A small line of text.";
                }

                UText {
                    text: "A second line of text.";
                }
            }
        }
    }

    DocCode {
        code: "UCard {\n    VerticalLayout {\n        spacing: 4px;\n        padding: 4px;\n        UText {\n            text: \"A small line of text.\";\n        }\n\n        UText {\n            text: \"A second line of text.\";\n        }\n    }\n}";
    }
}
