import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import {
    UTitle,
    UText,
    UCheckbox,
} from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { DocumentationLogic } from "../../logic/documentation-logic.slint";


export component CheckboxPage inherits PageBase {
    UTitle {
        level: 3;
        text: "Checkbox";
    }

    DocDescription {
        text: "A basic checkbox representing a true or false state.";
    }

    DocSection {
        title: "Basic usage";
        description: [
            [
                { text: "Display text with the " },
                { code: "text" },
                { text: " property and use the " },
                { code: "checked" },
                { text: " property to check weither the checkbox is checked or not." }
            ]
        ];
    }

    WidgetPresentation {
        UCheckbox {
            text: "Checkbox \{self.checked ? "checked" : "not checked"}";
        }
    }

    DocCode {
        code: "UCheckbox {\n    text: \"Checkbox \\{self.checked ? \"checked\" : \"not checked\"}\";\n}";
    }

    DocSection {
        title: "Text position and alignment";
        description: [
            [
                { text: "You can choose the text position with the " },
                { code: "text-placement" },
                { text:" property." }
            ],
            [
                { text:"The placement can be either " },
                { code: "start" },
                { text: ", " },
                { code: "end" },
                { text: ", " },
                { code: "hidden" },
                { text:" and defaults to " },
                { code:"start" },
                { text:"." }
            ],
            [
                {
                    text: "The alignment between the text and the checkbox itself can be modified with the "
                },
                { code:"alignment" },
                { text: " property. It defaults to " },
                { code: "LayoutAligment.space-between" },
                { text:"." }
            ]
        ];
    }

    WidgetPresentation {
        full-width: true;
        UCheckbox {
            text: "Checkbox with end placing and space-around as alignment.";
            text-placement: end;
            alignment: space-around;
        }
    }

    DocCode {
        code: "UCheckbox {\n    text: \"Checkbox\";\n    text-placement: end;\n    alignment: space-around;\n}";
    }
}
