import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import { UTitle, UCheckbox } from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { AppLogic } from "../../app-logic.slint";


export component CheckboxPage inherits PageBase {
    UTitle {
        level: 3;
        text: "Checkbox";
    }

    DocDescription {
        text: "A basic checkbox representing a true or false state.";
    }

    DocSection {
        title: "Basic usage";
        description-md: @markdown("Display text with the `text` property and use the `checked` property to know the status of the checkbox.");
    }

    WidgetPresentation {
        UCheckbox {
            text: "Checkbox \{self.checked ? "checked" : "not checked"}";
        }
    }

    DocCode {
        code: "UCheckbox {\n    text: \"Checkbox \\{self.checked ? \"checked\" : \"not checked\"}\";\n}";
    }

    DocSection {
        title: "Text position and alignment";
        description-md: @markdown(
			"You can choose the text position with the `text-placement` property. It can be either `start`, `end`, `hidden` and defaults to `start`.\n"
			"The alignment between the text and the checkbox itself can be modified with the `alignment` property. It defaults to `LayoutAlignment.space-between`."
		);
    }

    WidgetPresentation {
        full-width: true;
        UCheckbox {
            text: "Checkbox with end placing and space-around as alignment.";
            text-placement: end;
            alignment: space-around;
        }
    }

    DocCode {
        code: "UCheckbox {\n    text: \"Checkbox\";\n    text-placement: end;\n    alignment: space-around;\n}";
    }
}
