import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import { UTitle, UCircleProgress } from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { AppLogic } from "../../app-logic.slint";


export component CircleProgressPage inherits PageBase {
    UTitle {
        level: 3;
        text: "Circle progress";
    }

    DocDescription {
        text: "A circular progress bar.";
    }

    DocSection {
        title: "Basic usage";
        description: [
            [
                { text: "Define the current progress with the " },
                { code: "progress" },
                { text: " property." },
            ],
            [
                { text:"Do not forget to set the width or height depending on the orientation." }
            ],
        ];
    }

    WidgetPresentation {
        UCircleProgress {
            width: 300px;
            progress: 40%;
            indeterminate: true;
        }
    }

    DocCode {
        code: "ULinearProgress {\n    width: 300px;\n    progress: 40%;\n}";
    }
}
