import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import { UTitle, UCode } from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { AppLogic } from "../../app-logic.slint";


export component CodePage inherits PageBase {
    UTitle {
        level: 3;
        text: "Code";
    }

    DocDescription {
        text: "A widget to display a block of code.";
    }

    DocSection {
        title: "Basic usage";
    }

    DocCode {
        code: "UCode {\n    code: \"some code...\";\n}";
    }

    DocSection {
        title: "Text wrapping";
        description: @markdown("Use the `wrap` property to change the text's wrapping in the code block. It defaults to `TextWrap.no-wrap`.");
    }

    WidgetPresentation {
        alignment: start;
        UCode {
            wrap: word-wrap;
            width: 500px;
            code: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.";
        }
    }

    DocCode {
        code: "UCode {\n    wrap: word-wrap;\n    code: \"some long code...\";\n}";
    }

    DocSection {
        title: "Clipboard button";
        description: @markdown(
			"This button is enabled with the `enable-clipboard` property and fires the `copied(string) -> bool` callback which will display a \"Copied!\" "
			"message when returning `true`.\n"
			"The widget has a default implementation of the callback that always returns true.\n"
			"Please note that you must implement the clipboard logic in your code as it is not supported by Slint."
		);
    }

    DocCode {
        enable-clipboard: true;
        code: "UCode {\n    enable-clipboard: true;\n    copied(code: string) => {\n        debug(code);\n    }\n}";
    }
}
