import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import { UAlert, UTitle, UCode } from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { AppLogic } from "../../app-logic.slint";


export component CodePage inherits PageBase {
    UTitle {
        level: 3;
        text: "Code";
    }

    DocDescription {
        text: "A widget to display some code, either inline or as a block.";
    }

    DocSection {
        title: "Basic usage";
        description: @markdown("The code widget is by default of type `block`.");
    }

    DocCode {
        code: "UCode {\n    code: \"some code...\";\n}";
    }

    DocSection {
        title: "Inline code";
        description: @markdown("With the `inline` type, you can display some code next to a text.");
    }

    DocCode {
        padding-bottom: 10px;
        code: "HorizontalLayout {\n    UText {\n        text: \"Some random text: \";\n    }\n\n    UCode {\n        type: inline;\n        code: \"some code\";\n    }\n}";
    }

    UAlert {
        message: @markdown("You can also use the `StyledText` standard widget to display some inline code.");
    }

    DocSection {
        title: "Text wrapping";
        description: @markdown("The `wrap` default value is `TextWrap.no-wrap`.");
    }

    WidgetPresentation {
        alignment: start;
        UCode {
            wrap: word-wrap;
            width: 500px;
            code: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.";
        }
    }

    DocCode {
        code: "UCode {\n    wrap: word-wrap;\n    code: \"some long code...\";\n}";
    }

    DocSection {
        title: "Clipboard button";
        description: @markdown(
			"The clipboard button is only available when using the block type.\n"
			"This button is enabled with the `enable-clipboard` property and fires the `copied(string) -> bool` callback which will display a \"Copied !\" "
			"message when returning `true`.\n"
			"The widget has a default implementation of the callback that always returns true.\n"
			"Please note that you must implement the clipboard logic in your code as it is not supported by Slint."
		);
    }

    DocCode {
        enable-clipboard: true;
        code: "UCode {\n    enable-clipboard: true;\n    copied(code: string) => {\n        debug(code);\n    }\n}";
    }
}
