import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import { UTitle, UIcon } from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { AppLogic } from "../../app-logic.slint";


export component IconPage inherits PageBase {
    UTitle {
        level: 3;
        text: "Icon";
    }

    DocDescription {
        text: "A basic component to display an icon.";
    }

    DocSection {
        title: "Basic usage";
        description-md: @markdown("This widget inherits from `Image` hence all its parent properties are available.");
    }

    WidgetPresentation {
        UIcon {
            source: @image-url("../../assets/images/rocket.svg");
        }
    }

    DocCode {
        code: "UIcon {\n    source: @image-url(\"image-path\");\n}";
    }

    DocSection {
        title: "Change the size";
        description-md: @markdown(
			"Use the `size` property to manage the icon's size. This property sets both the height and width of the image."
		);
    }

    WidgetPresentation {
        spacing: UAppTheme.spacing-base;
        cross-axis-alignment: center;
        UIcon {
            size: UAppTheme.icon-size-base;
            source: @image-url("../../assets/images/rocket.svg");
        }

        UIcon {
            size: 24px;
            source: @image-url("../../assets/images/rocket.svg");
        }

        UIcon {
            size: 32px;
            source: @image-url("../../assets/images/rocket.svg");
        }

        UIcon {
            size: 48px;
            source: @image-url("../../assets/images/rocket.svg");
        }

        UIcon {
            size: 64px;
            source: @image-url("../../assets/images/rocket.svg");
        }

        UIcon {
            size: 96px;
            source: @image-url("../../assets/images/rocket.svg");
        }
    }

    DocCode {
        code: "UIcon {\n    size: 24px;\n    source: @image-url(\"image-path\");\n}";
    }

    DocSection {
        title: "Color";
        description-md: @markdown(
			"By default, the icon's color is set to `UAppTheme.text`, but you can make it keep its original color by setting "
			"`colorize` to `transparent`.\nYou can also apply a custom color with the same property."
		);
    }

    WidgetPresentation {
        spacing: UAppTheme.spacing-base;
        UIcon {
            size: 32px;
            source: @image-url("../../assets/images/rocket.svg");
            colorize: transparent;
        }

        UIcon {
            size: 32px;
            source: @image-url("../../assets/images/rocket.svg");
            colorize: red;
        }
    }

    DocCode {
        code: "UIcon {\n    colorize: transparent;\n    source: @image-url(\"image-path\");\n}\n\nUIcon {\n    colorize: red;\n    source: @image-url(\"image-path\");\n}";
    }
}
