import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import { UTitle, UIcon } from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { AppLogic } from "../../app-logic.slint";


export component IconPage inherits PageBase {
    UTitle {
        level: 3;
        text: "Icon";
    }

    DocDescription {
        text: "A basic component to display an icon.";
    }

    DocSection {
        title: "Basic usage";
        description: [
            [
                { text: "This widget inherits from " },
                { code: "Image" },
                { text: " hence all its parent properties are available." },
            ],
        ];
    }

    WidgetPresentation {
        UIcon {
            source: @image-url("../../assets/images/rocket.svg");
        }
    }

    DocCode {
        code: "UIcon {\n    source: @image-url(\"image-path\");\n}";
    }

    DocSection {
        title: "Change the size";
        description: [
            [
                { text: "Use the " },
                { code: "size" },
                { text: " property to mange the icon's size." },
            ],
            [{ text: "This property sets both the height and width of the image." }]
        ];
    }

    WidgetPresentation {
        spacing: UAppTheme.spacing-base;
        VerticalLayout {
            alignment: center;
            UIcon {
                size: UAppTheme.icon-size-base;
                source: @image-url("../../assets/images/rocket.svg");
            }
        }

        VerticalLayout {
            alignment: center;
            UIcon {
                size: 24px;
                source: @image-url("../../assets/images/rocket.svg");
            }
        }

        VerticalLayout {
            alignment: center;
            UIcon {
                size: 32px;
                source: @image-url("../../assets/images/rocket.svg");
            }
        }

        VerticalLayout {
            alignment: center;
            UIcon {
                size: 48px;
                source: @image-url("../../assets/images/rocket.svg");
            }
        }

        VerticalLayout {
            alignment: center;
            UIcon {
                size: 64px;
                source: @image-url("../../assets/images/rocket.svg");
            }
        }

        VerticalLayout {
            alignment: center;
            UIcon {
                size: 96px;
                source: @image-url("../../assets/images/rocket.svg");
            }
        }
    }

    DocCode {
        code: "UIcon {\n    size: 24px;\n    source: @image-url(\"image-path\");\n}";
    }

    DocSection {
        title: "Color";
        description: [
            [
                { text: "By default, the icon's color is set to " },
                { code: "UAppTheme.text" },
                { text: ", but you can make it keep its original color by setting " },
                { code: "colorize" },
                { text: " to " },
                { code: "transparent" }
            ],
            [{ text: "You can also apply a custom color with the same property." }]
        ];
    }

    WidgetPresentation {
        spacing: UAppTheme.spacing-base;
        UIcon {
            size: 32px;
            source: @image-url("../../assets/images/rocket.svg");
            colorize: transparent;
        }

        UIcon {
            size: 32px;
            source: @image-url("../../assets/images/rocket.svg");
            colorize: red;
        }
    }

    DocCode {
        code: "UIcon {\n    colorize: transparent;\n    source: @image-url(\"image-path\");\n}\n\nUIcon {\n    colorize: red;\n    source: @image-url(\"image-path\");\n}";
    }
}
