import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import {
    UAlert,
    UText,
    UTitle,
    UInlineCode,
} from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { AppLogic } from "../../app-logic.slint";


export component InlineCodePage inherits PageBase {
    UTitle {
        level: 3;
        text: "InlineCode";
    }

    HorizontalLayout {
        padding-top: UAppTheme.padding-base;
        padding-bottom: UAppTheme.padding-base;
        UAlert {
            variant: danger;
            message: @markdown("This widget will be removed once `StyledText` inline code support has been improved (should be in Slint 1.18).");
        }
    }

    DocDescription {
        text: "A widget to display some code inlined in text.";
    }

    DocSection {
        title: "Usage";
    }

    WidgetPresentation {
        alignment: start;
        UText {
            text: "Use the";
        }

        UInlineCode {
            code: "UInlineCode";
        }

        UText {
            text: "widget to inline code within text.";
        }
    }

    DocCode {
        code: "HorizontalLayout {\n    UText {\n        text: \"Use the\";\n    }\n\n    UInlineCode {\n        code: \"UInlineCode\";\n    }\n\n    UText {\n        text: \"widget to inline code within text.\";\n    }\n}";
    }
}
