import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import { UTitle, UInput } from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { AppLogic } from "../../app-logic.slint";


export component InputPage inherits PageBase {
    UTitle {
        level: 3;
        text: "Input";
    }

    DocDescription {
        text: "A text input that can be of different types (text, password, decimal).";
    }

    DocSection {
        title: "Basic usage";
    }

    WidgetPresentation {
        UInput { }
    }

    DocCode {
        code: "UInput {\n    accepted => {\n        debug(self.text);\n    }\n}";
    }

    DocSection {
        title: "Read only input";
        description: @markdown("Use the `read-only` property to make the input read-only.");
    }

    WidgetPresentation {
        UInput {
            text: "This input is read only";
            read-only: true;
        }
    }

    DocCode {
        code: "UInput {\n    read-only: true;\n}";
    }

    DocSection {
        title: "Displaying a placeholder";
        description: @markdown("Set the `placeholder` property to display a temporary text.");
    }

    WidgetPresentation {
        UInput {
            placeholder: "Email";
        }
    }

    DocCode {
        code: "UInput {\n    placeholder: \"Email\";\n}";
    }

    DocSection {
        title: "Errored input";
        description: @markdown("You can set the input to an error state with the `error` property.\n");
    }

    WidgetPresentation {
        UInput {
            error: true;
        }
    }

    DocCode {
        code: "UInput {\n    error: true;\n}";
    }

    DocSection {
        title: "Clearable input";
        description: @markdown("You can toggle a clear button with the `clearable` property.");
    }

    WidgetPresentation {
        UInput {
            clearable: true;
        }
    }

    DocCode {
        code: "UInput {\n    clearable: true;\n}";
    }

    DocSection {
        title: "Input type";
        description: @markdown(
			"You can change the input's type with the `input-type` property.\n"
			"This property is of type `InputType` and defaults to `text`."
		);
    }

    WidgetPresentation {
        spacing: UAppTheme.spacing-base;
        UInput {
            input-type: password;
        }

        UInput {
            input-type: decimal;
            placeholder: "Decimal";
        }
    }

    DocCode {
        code: "UInput {\n    input-type: password;\n}\n\nUInput {\n    input-type: decimal;\n}";
    }

    DocSection {
        title: "TextInput properties, functions and callbacks";
        description: @markdown(
			"Almost all the properties of `TextInput` are available on the widget with the exception of a few that are not compatible with the widget's use.\n"
			"With the exception of both `focus()` and `clear-focus()`, all of the `TextInput` functions and callbacks are available."
		);
    }

    DocCode {
        code: "UInput {\n    accepted => {\n        // Your code\n    }\n    edited => {\n        // Your code\n    }\n}";
    }
}
