import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import { UTitle, UInputNumber } from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { AppLogic } from "../../app-logic.slint";


export component InputNumberPage inherits PageBase {
    private property <length> input-width: 150px;
    UTitle {
        level: 3;
        text: "InputNumber";
    }

    DocDescription {
        text: "A basic number input.";
    }

    DocSection {
        title: "Basic usage";
    }

    WidgetPresentation {
        UInputNumber {
            width: input-width;
        }
    }

    DocCode {
        code: "UInputNumber {\n    accepted => {\n        debug(self.text);\n    }\n}";
    }

    DocSection {
        title: "Disabled input";
        description-md: @markdown("Use the `enabled` property to enable/disable the input.");
    }

    WidgetPresentation {
        UInputNumber {
            width: input-width;
            enabled: false;
        }
    }

    DocCode {
        code: "UInputNumber {\n    enabled: false;\n}";
    }

    DocSection {
        title: "Define the step";
        description-md: @markdown(
			"You can set the step with the `step` property.\n"
			"The users can use the up/down arrow keys to increase/decrease the value."
		);
    }

    WidgetPresentation {
        UInputNumber {
            step: 10;
            width: 150px;
        }
    }

    DocCode {
        code: "UInputNumber {\n    step: 10;\n}";
    }

    DocSection {
        title: "Minimum and maximum values";
        description-md: @markdown(
			"Enable the minimum and maximum values by setting the `enable-min-max` property to `true`.\n"
			"You can then define the range using the `min` and `max` properties.\n"
		);
    }

    WidgetPresentation {
        UInputNumber {
            min-value: 10;
            max-value: 20;
        }
    }

    DocCode {
        code: "UInputNumber {\n    enable-min-max: true;\n    min: 10;\n    max: 20;\n}";
    }

    DocSection {
        title: "Errored input";
        description-md: @markdown("You can set the input to an error state with the `error` property.\n");
    }

    WidgetPresentation {
        UInputNumber {
            error: true;
        }
    }

    DocCode {
        code: "UInputNumber {\n    error: true;\n}";
    }

    DocSection {
        title: "Functions and callbacks";
        description-md: @markdown(
			"With the exception of both `focus()` and `clear-focus()`, all of the `TextInput` functions and callbacks are available.\n"
		);
    }

    DocCode {
        code: "UInputNumber {\n    accepted => {\n        // Your code\n    }\n    edited => {\n        // Your code\n    }\n}";
    }
}
