import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import { UTitle, UInputNumber } from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { DocumentationLogic } from "../../logic/documentation-logic.slint";


export component InputNumberPage inherits PageBase {
    private property <length> input-width: 150px;
    UTitle {
        level: 3;
        text: "InputNumber";
    }

    DocDescription {
        text: "A basic number input.";
    }

    DocSection {
        title: "Basic usage";
    }

    WidgetPresentation {
        UInputNumber {
            width: input-width;
        }
    }

    DocCode {
        code: "UInputNumber {\n    accepted => {\n        debug(self.text);\n    }\n}";
    }

    DocSection {
        title: "Disabled input";
        description: [[{ text: "Use the " }, { code: "enabled" }, { text:" property to disable the input." }]];
    }

    WidgetPresentation {
        UInputNumber {
            width: input-width;
            enabled: false;
        }
    }

    DocCode {
        code: "UInputNumber {\n    enabled: false;\n}";
    }

    DocSection {
        title: "Define the step";
        description: [
            [{ text:"You can set the step with the " }, { code: "step" }, { text:" property" }],
            [{ text:"You can use the up/down arrow keys to increase/decrease the value." }]
        ];
    }

    WidgetPresentation {
        UInputNumber {
            step: 10;
            width: 150px;
        }
    }

    DocCode {
        code: "UInputNumber {\n    step: 10;\n}";
    }

    DocSection {
        title: "Minimum and maximum values";
        description: [
            [
                { text: "Enable the minimum and maximum values by setting the " },
                { code:"enable-min-max" },
                { text: " property to " },
                { code:"true" },
                { text:"." }
            ],
            [
                { text: "You can then set the " },
                { code: "min" },
                { text:" and " },
                { code: "max" },
                { text: " properties." }
            ]
        ];
    }

    WidgetPresentation {
        UInputNumber {
            enable-min-max: true;
            min-value: 10;
            max-value: 20;
        }
    }

    DocCode {
        code: "UInputNumber {\n    enable-min-max: true;\n    min: 10\n    max: 20;\n}";
    }

    DocSection {
        title: "Errored input";
        description: [
            [
                { text: "You can set the input to an error state with the " },
                { code:"error" },
                { text: " properties." }
            ]
        ];
    }

    WidgetPresentation {
        UInputNumber {
            error: true;
        }
    }

    DocCode {
        code: "UInputNumber {\n    error: true;\n}";
    }

    DocSection {
        title: "Functions and callbacks";
        description: [
            [
                { text: "With the exception of both " },
                { code: "focus()" },
                { text: " and " },
                { code:"clear-focus()" },
                { text:" , all of " },
                { code: "TextInput" },
                { text: " functions and callbacks are available." }
            ]
        ];
    }

    DocCode {
        code: "UInputNumber {\n    accepted => {\n        // Your code\n    }\n    edited => {\n        // Your code\n    }\n}";
    }
}
