import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import { UTitle, UInput } from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { AppLogic } from "../../app-logic.slint";


export component InputPage inherits PageBase {
    UTitle {
        level: 3;
        text: "Input";
    }

    DocDescription {
        text: "A text input that can be of different types (text, password, decimal).";
    }

    DocSection {
        title: "Basic usage";
        description: [];
    }

    WidgetPresentation {
        UInput { }
    }

    DocCode {
        code: "UInput {\n    accepted => {\n        debug(self.text);\n    }\n}";
    }

    DocSection {
        title: "Disabled input";
        description: [[{ text: "Use the " }, { code: "enabled" }, { text:" property to disable the input." }]];
    }

    WidgetPresentation {
        UInput {
            enabled: false;
        }
    }

    DocCode {
        code: "UInput {\n    enabled: false;\n}";
    }

    DocSection {
        title: "Displaying a placeholder";
        description: [[{ text: "Set the " }, { code: "placeholder" }, { text: " property to display one." }]];
    }

    WidgetPresentation {
        UInput {
            placeholder: "Email";
        }
    }

    DocCode {
        code: "UInput {\n    placeholder: \"Email\";\n}";
    }

    DocSection {
        title: "Errored input";
        description: [
            [
                { text: "You can set the input to an error state with the " },
                { code:"error" },
                { text:" property." }
            ]
        ];
    }

    WidgetPresentation {
        UInput {
            error: true;
        }
    }

    DocCode {
        code: "UInput {\n    error: true;\n}";
    }

    DocSection {
        title: "Clearable input";
        description: [
            [
                { text: "You can display a clear button with the " },
                { code:"clearable" },
                { text:" property." }
            ]
        ];
    }

    WidgetPresentation {
        UInput {
            clearable: true;
        }
    }

    DocCode {
        code: "UInput {\n    clearable: true;\n}";
    }

    DocSection {
        title: "Input type";
        description: [
            [
                { text: "You can change the input's type with the " },
                { code:"input-type" },
                { text:" property." }
            ],
            [
                { text: "This property is of type " },
                { code: "InputType" },
                { text: " and defaults to " },
                { code:"text" },
                { text:"." }
            ]
        ];
    }

    WidgetPresentation {
        spacing: UAppTheme.spacing-base;
        UInput {
            input-type: password;
        }

        UInput {
            input-type: decimal;
            placeholder: "Decimal";
        }
    }

    DocCode {
        code: "UInput {\n    input-type: password;\n}\n\nUInput {\n    input-type: decimal;\n}";
    }

    DocSection {
        title: "Functions and callbacks";
        description: [
            [
                { text: "With the exception of both " },
                { code: "focus()" },
                { text: " and " },
                { code:"clear-focus()" },
                { text:" , all of " },
                { code: "TextInput" },
                { text: " functions and callbacks are available." }
            ]
        ];
    }

    DocCode {
        code: "UInput {\n    accepted => {\n        // Your code\n    }\n    edited => {\n        // Your code\n    }\n}";
    }
}
