import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import { UTitle, ULinearProgress } from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { AppLogic } from "../../app-logic.slint";


export component LinearProgressPage inherits PageBase {
    UTitle {
        level: 3;
        text: "Linear progress";
    }

    DocDescription {
        text: "A linear progress bar.";
    }

    DocSection {
        title: "Basic usage";
        description-md: @markdown(
			"Define the current progress with the `progress` property. "
			"Do not forget to set the width or height depending on the orientation."
		);
    }

    WidgetPresentation {
        ULinearProgress {
            width: 300px;
            progress: 40%;
        }
    }

    DocCode {
        code: "ULinearProgress {\n    width: 300px;\n    progress: 40%;\n}";
    }

    DocSection {
        title: "Orientation and direction";
        description-md: @markdown(
			"Use the `orientation` property to choose the progress' orientation.\n"
			"Use the `direction` property to choose whether the progress starts from the start or the end."
		);
    }

    WidgetPresentation {
        spacing: UAppTheme.spacing-base;
        ULinearProgress {
            height: 100px;
            orientation: vertical;
            direction: start;
            progress: 40%;
        }

        ULinearProgress {
            height: 100px;
            orientation: vertical;
            direction: end;
            progress: 40%;
        }
    }

    DocCode {
        code: "ULinearProgress {\n    height: 300px;\n    orientation: vertical;\n    direction: end;\n    progress: 40%;\n}";
    }

    DocSection {
        title: "Indeterminate progress";
        description-md: @markdown(
			"Set the `indeterminate` property to `true` to set the progress in a loading state."
		);
    }

    WidgetPresentation {
        ULinearProgress {
            width: 300px;
            indeterminate: true;
        }
    }

    DocCode {
        code: "ULinearProgress {\n    width: 300px;\n    indeterminate: true;\n}";
    }

    DocSection {
        title: "Default size and radius";
        description-md: @markdown(
			"You can manage the size and radius of the progress with the `default-size` and `default-radius` properties."
		);
    }

    WidgetPresentation {
        ULinearProgress {
            width: 300px;
            default-size: 30px;
            default-radius: UAppTheme.radius-base;
            progress: 40%;
        }
    }

    DocCode {
        code: "ULinearProgress {\n    width: 300px;\n    default-size: 30px;\n    default-radius: UAppTheme.radius-base;\n    progress: 40%;\n}";
    }
}
