import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import { UTitle, ULineProgress } from "../../sleek-ui/widgets.slint";
import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { AppLogic } from "../../app-logic.slint";


export component LineProgressPage inherits PageBase {
    UTitle {
        level: 3;
        text: "Line progress";
    }

    DocDescription {
        text: "A linear progress bar.";
    }

    DocSection {
        title: "Basic usage";
        description: @markdown("Define the current progress with the `progress` property and change its color using the `progress-color` property.");
    }

    WidgetPresentation {
        VerticalLayout {
            spacing: UAppTheme.spacing-base;
            ULineProgress {
                width: 300px;
                progress: 40%;
            }

            ULineProgress {
                progress-color: UAppTheme.warning.base;
                width: 300px;
                progress: 60%;
            }

            ULineProgress {
                progress-color: UAppTheme.golden-purple.base;
                width: 300px;
                progress: 25%;
            }
        }
    }

    DocCode {
        code: "ULineProgress {\n    width: 300px;\n    progress: 40%;\n}\n\nULineProgress {\n    progress-color: UAppTheme.warning.base;\n    width: 300px;\n    progress: 60%;\n}\n\nULineProgress {\n    progress-color: UAppTheme.golden-purple.base;\n    width: 300px;\n    progress: 25%;\n}";
    }

    DocSection {
        title: "Orientation and direction";
        description: @markdown(
			"Use the `orientation` property to choose the progress' orientation.\n"
			"Use the `direction` property to choose whether the progress starts from the start or the end."
		);
    }

    WidgetPresentation {
        spacing: UAppTheme.spacing-base;
        ULineProgress {
            height: 100px;
            orientation: vertical;
            direction: start;
            progress: 40%;
        }

        ULineProgress {
            height: 100px;
            orientation: vertical;
            direction: end;
            progress: 40%;
        }
    }

    DocCode {
        code: "ULineProgress {\n    height: 300px;\n    orientation: vertical;\n    direction: end;\n    progress: 40%;\n}";
    }

    DocSection {
        title: "Indeterminate progress";
        description: @markdown(
			"Set the `indeterminate` property to `true` to set the progress in a loading state."
		);
    }

    WidgetPresentation {
        ULineProgress {
            width: 300px;
            indeterminate: true;
        }
    }

    DocCode {
        code: "ULineProgress {\n    width: 300px;\n    indeterminate: true;\n}";
    }

    DocSection {
        title: "Default size and radius";
        description: @markdown(
			"You can manage the size and radius of the progress with the `default-size` and `default-radius` properties."
		);
    }

    WidgetPresentation {
        ULineProgress {
            width: 300px;
            default-size: 30px;
            default-radius: UAppTheme.radius-base;
            progress: 40%;
        }
    }

    DocCode {
        code: "ULineProgress {\n    width: 300px;\n    default-size: 30px;\n    default-radius: UAppTheme.radius-base;\n    progress: 40%;\n}";
    }
}
