import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import {
    UTitle,
    ULink,
    UMenuLogic,
} from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { AppLogic } from "../../app-logic.slint";


export component LinkPage inherits PageBase {
    UTitle {
        level: 3;
        text: "Link";
    }

    DocDescription {
        text: "A simple text displayed as a link. The logic must be implemented by your source code as opening URLs is not (yet) supported by Slint.";
    }

    DocSection {
        title: "Example";
        description: [
            [
                { text: "The link widget comes with a " },
                { code: "clicked" },
                { text: " callback." },
            ]
        ];
        link-clicked(id) => {
            UMenuLogic.current-link = "button-interface";
        }
    }

    WidgetPresentation {
        ULink {
            text: "Slint source";
            clicked => {
                AppLogic.open-url("https://github.com/slint-ui/slint");
            }
        }
    }

    DocCode {
        code: "ULink {\n    text: \"Source\";\n    clicked => {\n        // Your logic to open URLs.\n    }\n}";
    }

    DocSection {
        title: "External link icon";
        description: [
            [
                {
                    text: "You can display an icon showing that the link is an external one by enabling the "
                },
                { code: "icon-placement" },
                { text: " property." }
            ]
        ];
    }

    WidgetPresentation {
        spacing: UAppTheme.spacing-big;
        ULink {
            text: "External link";
            icon-placement: start;
        }

        ULink {
            text: "External link";
            icon-placement: end;
        }
    }

    DocCode {
        code: "ULink {\n    text: \"External link\";\n    icon-placement: start;\n}\n\nULink {\n    text: \"External link\";\n    icon-placement: end;\n}";
    }

    DocSection {
        title: "Disable the underline";
        description: [
            [
                { text: "You can disable the underline by setting the " },
                { code: "disable-underline" },
                { text: " to " },
                { code: "true" },
                { text: "." }
            ]
        ];
    }

    WidgetPresentation {
        spacing: UAppTheme.spacing-big;
        ULink {
            text: "Underline disabled";
            disable-underline: true;
        }

        ULink {
            text: "Underline disabled";
            disable-underline: true;
            icon-placement: start;
        }
    }

    DocCode {
        code: "ULink {\n    text: \"Disabled underline\";\n    disable-underline: true;\n}\n\nULink {\n    text: \"Disabled underline\";\n    disable-underline: true;\n    icon-placement: start;\n}";
    }
}
