import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import {
    UTitle,
    UText,
    UCode,
    ULink,
    UMenuLogic,
} from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { DocumentationLogic } from "../../logic/documentation-logic.slint";


export component LinkPage inherits PageBase {
    UTitle {
        level: 3;
        text: "Link";
    }

    DocDescription {
        text: "A simple text displayed as a link. The logic must be implemented by your source code as opening URLs is not supported by Slint.";
    }

    DocSection {
        title: "Example";
        description: [
            { text: "The link widget comes with all the callbacks from " },
            { link: "ButtonInterface" },
            { text: ", but only the " },
            { code: "clicked" },
            { text: " callback should be useful." }
        ];
        link-clicked(id) => {
            UMenuLogic.current-link = "button-interface";
        }
    }

    WidgetPresentation {
        ULink {
            text: "Slint source";
            clicked => {
                DocumentationLogic.open-url("https://github.com/slint-ui/slint");
            }
        }
    }

    UCode {
        code: "import { ULink } from \"@sleek-ui/widgets.slint\";\n\nULink {\n    text: \"Source\";\n    clicked => {\n        // Your logic to open URLs.\n    }\n}";
    }
}
