import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import {
    UTitle,
    ULink,
    UMenuLogic,
    UAlert,
} from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { AppLogic } from "../../app-logic.slint";


export component LinkPage inherits PageBase {
    UTitle {
        level: 3;
        text: "Link";
    }

    DocDescription {
        text: "A simple text displayed as a link.";
    }

    HorizontalLayout {
        padding-top: UAppTheme.padding-base;
        padding-bottom: UAppTheme.padding-base;
        UAlert {
            message: @markdown("You an also use the StyledText widget to display a link using markdown syntax.");
        }
    }

    DocSection {
        title: "Example";
        description: [
            [
                {
                    text: "The link widget doesn't automatically open URLs but instead triggers the "
                },
                { code: "clicked" },
                { text: " callback." },
            ],
            [
                {
                    text: "This allows you to implement your own logic to open URLs, for example using the "
                },
                { code: "Platform.open-url()" },
                { text: " function or linking to another part in your application." }
            ],
        ];
        link-clicked(id) => {
            UMenuLogic.current-link = "button-interface";
        }
    }

    WidgetPresentation {
        ULink {
            text: "Slint source";
            clicked => {
                Platform.open-url("https://github.com/slint-ui/slint");
            }
        }
    }

    DocCode {
        code: "ULink {\n    text: \"Source\";\n    clicked => {\n        // Your logic to open URLs.\n    }\n}";
    }

    DocSection {
        title: "External link icon";
        description: [
            [
                {
                    text: "You can display an icon showing that the link is an external one by enabling the "
                },
                { code: "icon-placement" },
                { text: " property." }
            ]
        ];
    }

    WidgetPresentation {
        spacing: UAppTheme.spacing-big;
        ULink {
            text: "External link";
            icon-placement: start;
        }

        ULink {
            text: "External link";
            icon-placement: end;
        }
    }

    DocCode {
        code: "ULink {\n    text: \"External link\";\n    icon-placement: start;\n}\n\nULink {\n    text: \"External link\";\n    icon-placement: end;\n}";
    }

    DocSection {
        title: "Wrapping";
        description: [
            [
                { text: "By default, the link will wrap using the " },
                { code: "TextWrap.char-wrap" },
                { text: " value. You can change it using the " },
                { code: "wrap" },
                { text: " property." }
            ]
        ];
    }

    WidgetPresentation {
        spacing: UAppTheme.spacing-big;
        HorizontalLayout {
            width: 200px;
            ULink {
                text: "Very long link that will wrap on multiple lines using the word-wrap value.";
                wrap: word-wrap;
            }
        }
    }

    DocCode {
        code: "ULink {\n    text: \"Very long link that will wrap on multiple lines using the word-wrap value.\";\n    wrap: word-wrap;\n}";
    }
}
