import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import {
    UTitle,
    UText,
    UCode,
} from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { DocumentationLogic } from "../../logic/documentation-logic.slint";


export component MenuPageLink inherits PageBase {
    UTitle {
        level: 3;
        text: "Menu link";
    }

    DocDescription {
        text: "A link to use in the menu or submenu widget.";
    }

    DocSection {
        title: "Basic usage";
        description: [
            [
                { text: "Add a link to a menu by setting the " },
                { code: "id" },
                { text: " and " },
                { code: "name" },
                { text: "." },
            ]
        ];
    }

    DocCode {
        code: "UMenuLink {\n    id: \"first-page\";\n    name: \"First page\";\n}";
    }

    DocSection {
        title: "Disabled link";
        description: [
            [
                { text: "You can disable a link by setting the " },
                { code: "enabled" },
                { text:" property to false." }
            ]
        ];
    }

    DocCode {
        code: "UMenuLink {\n    id: \"first-page\";\n    name: \"First page\";\n}";
    }

    // TODO Present properties
}
