import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import { UTitle } from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { DocumentationLogic } from "../../logic/documentation-logic.slint";


export component MenuPageSubmenu inherits PageBase {
    UTitle {
        level: 3;
        text: "Menu submenu";
    }

    DocDescription {
        text: "A submenu to use in the menu widget.";
    }

    DocSection {
        title: "Basic usage";
        description: [
            [
                { text: "To use a submenu, you only need to set the " },
                { code: "name" },
                { text: " property." }
            ]
        ];
    }

    DocCode {
        code: "UMenuSubmenu {\n    name: \"Settings\";\n}";
    }

    DocSection {
        title: "Disabled menu";
        description: [
            [
                { text: "You can disable a menu with the " },
                { code: "enabled" },
                { text: " property." }
            ]
        ];
    }

    DocCode {
        code: "UMenuSubmenu {\n    enabled: false;\n}";
    }

    DocSection {
        title: "Programmatically open a submenu";
        description: [
            [
                { text: "You can open a submenu using the " },
                { code: "opened" },
                { text: " property." }
            ]
        ];
    }

    DocCode {
        code: "UMenuSubmenu {\n    opened: true;\n}";
    }

    DocSection {
        title: "Parent submenus";
        description: [
            [
                { text: "When using submenus, you can use the " },
                { code: "parent-child-opened" },
                { text: " and " },
                { code: "child-opened" },
                { text: " properties to display the current path." },
            ],
            [
                {
                    text: "This will allow the parents submenus of the currently selected link to be highlighted."
                }
            ],
        ];
    }

    DocCode {
        code: "UMenuSubmenu {\n    UMenuSubmenu {\n        parent-child-opened <=> parent.child-opened;\n        UMenuLink {\n            parent-child-opened <=> parent.child-opened;\n        }\n    }\n}";
    }
}
