import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import {
    UTitle,
    UText,
} from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { DocumentationLogic } from "../../logic/documentation-logic.slint";
import { UAlert } from "../../sleek-ui/widgets/alert.slint";


export component MenuPageHowTo inherits PageBase {
    UTitle {
        level: 3;
        text: "Menu";
    }

    DocDescription {
        text: "A versatile menu for navigation.";
    }

    HorizontalLayout {
        padding-top: UAppTheme.padding-base;
        padding-bottom: UAppTheme.padding-base;
        UAlert {
            variant: danger;
            message: "As the menu uses a global to store the current link, only one menu can be displayed at the same time.";
        }
    }

    DocSection {
        title: "Example";
        description: [
            [
                { text: "The menu is made from several subwidgets: " },
                { code: "UMenu" },
                { text: ", " },
                { code: "UMenuLink" },
                { text: ", " },
                { code: "UMenuSubmenu" },
                { text: ", " },
                { code: "UMenuGroupTitle" },
                { text: ", each widget having its own properties." },
            ]
        ];
    }

    HorizontalLayout {
        padding-top: UAppTheme.padding-base;
        padding-bottom: UAppTheme.padding-base;
        UAlert {
            variant: info;
            message: "Check out the sidebar for a running example of a menu.";
        }
    }

    DocCode {
        code: "UMenu {\n    UMenuLink {\n        id: \"first-page\";\n        name: \"First page\";\n    }\n\n    UMenuSubmenu {\n        name: \"Sub-pages\";\n        UMenuLink {\n            id: \"Subpage\";\n            name: \"Subpage\";\n        }\n    }\n\n    UMenuGroupTitle {\n        title: \"Settings pages\";\n    }\n\n    UMenuLink {\n        id: \"settings-page\";\n        name: \"Settings\";\n    }\n}";
    }

    DocSection {
        title: "Theming";
        description: [
            [
                { text: "The " },
                { code: "UMenu" },
                { text: " widget comes with a " },
                { code: "variant" },
                { text: " property that can be one of the following choices: " },
                { code: "default" },
                { text: ", " },
                { code: "light" },
                { text: ", " },
                { code: "dark" },
                { text: "." },
            ],
            [
                {
                    text: "Using the default variant will give you a menu that follows the current coor scheme, meanwhile the light and dark variants will force their equivalent color schemes.",
                }
            ]
        ];
    }

    DocCode {
        code: "UMenu {\n    variant: light;\n}";
    }
}
