import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import { UTitle } from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { AppLogic } from "../../app-logic.slint";


export component MenuPageSubmenu inherits PageBase {
    UTitle {
        level: 3;
        text: "Menu submenu";
    }

    DocDescription {
        text: "A submenu to use in the menu widget.";
    }

    DocSection {
        title: "Basic usage";
        description: @markdown("You only need to set the `name` property to use a submenu.");
    }

    DocCode {
        code: "UMenuSubmenu {\n    name: \"Settings\";\n}";
    }

    DocSection {
        title: "Disabled menu";
        description: @markdown("You can disable a menu by setting the `enabled` property to false.");
    }

    DocCode {
        code: "UMenuSubmenu {\n    enabled: false;\n}";
    }

    DocSection {
        title: "Programmatically open a submenu";
        description: @markdown("You can open/close a submenu using the `opened` boolean property.");
    }

    DocCode {
        code: "UMenuSubmenu {\n    opened: true;\n}";
    }

    DocSection {
        title: "Parent submenus";
        description: @markdown(
			"When using submenus, you can use the `parent-child-opened` and `child-opened` properties to display the current path.\n"
			"This will allow the parent submenus of the currently selected link to be highlighted."
		);
    }

    DocCode {
        code: "UMenuSubmenu {\n    UMenuSubmenu {\n        parent-child-opened <=> parent.child-opened;\n        UMenuLink {\n            parent-child-opened <=> parent.child-opened;\n        }\n    }\n}";
    }
}
