import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import { UTitle } from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { AppLogic } from "../../app-logic.slint";


export component MenuPageGroupTitle inherits PageBase {
    UTitle {
        level: 3;
        text: "Menu group title";
    }

    DocDescription {
        text: "A title to separate links and submenus from different groups in a menu or submenu.";
    }

    DocSection {
        title: "Basic usage";
        description: @markdown("You only need to set the `title` property to use the widget.");
    }

    DocCode {
        code: "UMenuGroupTitle {\n    title: \"User settings\";\n}";
    }

    DocSection {
        title: "Change the title level";
        description: @markdown("You can change the title's level with the `level` property.");
    }

    DocCode {
        code: "UMenuGroupTitle {\n    level: 1;\n    title:\"User settings\";\n}";
    }
}
