import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import {
    UTitle,
    UText,
    UCode,
    UMenu,
    UMenuLink,
} from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { DocumentationLogic } from "../../logic/documentation-logic.slint";
import { UAlert } from "../../sleek-ui/widgets/alert.slint";


export component MenuPage inherits PageBase {
    UTitle {
        level: 3;
        text: "Menu";
    }

    DocDescription {
        text: "A versatile menu for navigation.";
    }

    HorizontalLayout {
        padding-top: UAppTheme.padding-base;
        padding-bottom: UAppTheme.padding-base;
        UAlert {
            variant: danger;
            message: "As the menu uses a global to store the current link, only one menu can be displayed at the same time.";
        }
    }

    DocSection {
        title: "Example";
        description: [
            [
                { text: "The menu is made from several subwidgets: " },
                { code: "UMenu" },
                { text: ", " },
                { code: "UMenuLink" },
                { text: ", " },
                { code: "UMenuSubmenu" },
                { text: ", " },
                { code: "UMenuGroupTitle" },
                { text: ", each widget having its own properties." },
            ]
        ];
    }

    HorizontalLayout {
        padding-top: UAppTheme.padding-base;
        UCode {
            code: "import { UMenu, UMenuLink, UMenuSubmenu, UMenuGroupTitle } from \"@sleek-ui/widgets.slint\";\n\nUMenu {\n    UMenuLink {\n        id: \"first-page\";\n        name: \"First page\";\n    }\n\n    UMenuSubmenu {\n        name: \"Sub-pages\";\n        UMenuLink {\n            id: \"Subpage\";\n            name: \"Subpage\";\n        }\n    }\n\n    UMenuGroupTitle {\n        title: \"Settings pages\";\n    }\n\n    UMenuLink {\n        id: \"settings-page\";\n        name: \"Settings\";\n    }\n}";
        }
    }

    DocSection {
        title: "Theming";
        description: [
            [
                { text: "The " },
                { code: "UMenu" },
                { text: " widget comes with a " },
                { code: "variant" },
                { text: " property that can be one of the following choices: " },
                { code: "default" },
                { text: ", " },
                { code: "light" },
                { text: ", " },
                { code: "dark" },
                { text: "." },
            ],
            [
                {
                    text: "Using the default variant will give you a menu that follows the current coor scheme, meanwhile the light and dark variants will force their equivalent color schemes.",
                }
            ]
        ];
    }

    HorizontalLayout {
        padding-top: UAppTheme.padding-base;
        UCode {
            code: "import { UMenu } from \"@sleek-ui/widgets.slint\";\n\nUMenu {\n    variant: light;\n}";
        }
    }

    DocSection {
        title: "Parent submenus";
        description: [
            [
                { text: "When using submenus, you can use the " },
                { code: "parent-child-opened" },
                { text: " and " },
                { code: "child-opened" },
                { text: " properties to display the current path." },
            ],
            [
                {
                    text: "This will allow the parents submenus of the currently selected link to be highlighted."
                }
            ]
        ];
    }

    HorizontalLayout {
        padding-top: UAppTheme.padding-base;
        UCode {
            code: "import { UMenu, UMenuSubmenu, UMenuLink } from \"@sleek-ui/widgets.slint\";\n\nUMenu {\n    UMenuSubmenu {\n        name: \"Settings\";\n        UMenuSubmenu {\n            parent-child-opened <=> parent.child-opened;\n            name: \"Inner\";\n            UMenuLink {\n                parent-child-opened <=> parent.child-opened;\n                id: \"settings\";\n                name: \"Settings\";\n            }\n        }\n    }\n}";
        }
    }

    DocSection {
        title: "";
    }

	// TODO Present each subwidget.
}
