import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import {
    UTitle,
    UText,
} from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { DocumentationLogic } from "../../logic/documentation-logic.slint";


export component MenuPageSubmenu inherits PageBase {
    UTitle {
        level: 3;
        text: "Menu submenu";
    }

    DocDescription {
        text: "A submenu to use in the menu widget.";
    }

    // TODO Present properties

    DocSection {
        title: "Parent submenus";
        description: [
            [
                { text: "When using submenus, you can use the " },
                { code: "parent-child-opened" },
                { text: " and " },
                { code: "child-opened" },
                { text: " properties to display the current path." },
            ],
            [
                {
                    text: "This will allow the parents submenus of the currently selected link to be highlighted."
                }
            ]
        ];
    }

    DocCode {
        code: "";
    }
}
