import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import { UTitle } from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { AppLogic } from "../../app-logic.slint";


export component ModalPage inherits PageBase {
    UTitle {
        level: 3;
        text: "Modal";
    }

    DocDescription {
        text: "A modal that takes the whole screen that contains custom code.";
    }

    DocSection {
        title: "How to use";
        description: [];
    }

    DocCode {
        code: "";
    }
}
