import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import { UTitle, UButton, UModalLogic } from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";


export component ModalPage inherits PageBase {
    UTitle {
        level: 3;
        text: "Modal";
    }

    DocDescription {
        text: "A modal that takes the whole screen that contains custom code.";
    }

    DocSection {
        title: "How to use";
        description-md: @markdown(
			"The modal is a complex widget that, like the tooltip, must be placed at the root of the project / page to be rendered above all the content.\n"
			"It comes with a `@children` slot to allow you to put anything in its body. Its title is set throught the `title` property.\n"
			"To open a modal, you must set its `id` property, and then call the `UModalLogic.open-modal(id: string)` global function.\n"
			"You can close the modal with its button, or call the `UModalLogic.close-modal()` function."
		);
    }

    WidgetPresentation {
        UButton {
            text: "Open modal";
            clicked => {
                UModalLogic.open-modal("modal-base");
            }
        }
    }

    DocCode {
        code: "// Your button to open the modal somewhere in your app.\nUButton {\n    text: \"Open modal\";\n    clicked => {\n        UModalLogic.open-modal(\"form-modal\");\n    }\n}\n\n// Your modal in your window.\nexport component AppWindow inherits Window {\n    // Your app's code.\n\n    UModal {\n        id: \"form-modal\";\n        title: \"Add a user\";\n        // Your modal's code.\n    }\n}";
    }

    DocSection {
        title: "Callbacks";
        description-md: @markdown(
			"The modal comes with four callbacks: `showed`, `closed`, `accepted` and `rejected`.\n"
			"The `accepted` and `rejected` callbacks are linked to the accept and cancel buttons.\n"
			"The `showed` and `closed` callbacks are always called, even when the accepted/rejected callbacks are called."
		);
    }

    DocSection {
        title: "Modal width and height";
        description-md: @markdown(
			"The modal's width and height are computed based on its content, but you can use the `modal-min/max-*` properties to customize them.\n"
			"The max values are by default `600px`, the minimum width is set by default to `300px` and there is no default value for the minimum height."
		);
    }

    WidgetPresentation {
        UButton {
            text: "Open modal";
            clicked => {
                UModalLogic.open-modal("modal-dimensions");
            }
        }
    }

    DocCode {
        code: "UModal {\n    id: \"dimensions-modal\";\n    title: \"Custom limits on width and height\";\n    modal-min-width: 200px;\n    modal-min-height: 200px;\n    modal-max-width: 400px;\n    modal-max-height: 400px;\n    // Your modal's code.\n}";
    }

    DocSection {
        title: "Close comportment";
        description-md: @markdown(
			"By default, the modal will only close when clicking on the close button or the Accept/Cancel buttons.\n"
			"You can change this by settings the `close-on-accept` and `close-on-cancel` boolean properties.\n"
			"You can also close the modal when clicking on the greyed background when enabling the `close-on-click-outside` property."
		);
    }

    WidgetPresentation {
        UButton {
            text: "Open modal";
            clicked => {
                UModalLogic.open-modal("modal-close");
            }
        }
    }

    DocCode {
        code: "UModal {\n    id: \"close-modal\";\n    title: \"Custom close comportment\";\n    close-on-click-outside: true;\n    close-on-accept: false;\n    close-on-cancel: false;\n    // Your modal's code.\n}";
    }

    DocSection {
        title: "Content dividers";
        description-md: @markdown(
			"You can display dividers to have a clear separation between the content and the top and bottom spaces.\n"
			"Use the `top-divider` and `bottom-divider` properties to enable them."
		);
    }

    WidgetPresentation {
        UButton {
            text: "Open modal";
            clicked => {
                UModalLogic.open-modal("modal-dividers");
            }
        }
    }

    DocCode {
        code: "UModal {\n    id: \"dividers-modal\";\n    title: \"Display content dividers\";\n    top-divider: true;\n    bottom-divider: true;\n    // Your modal's code.\n}";
    }

    DocSection {
        title: "Buttons style";
        description-md: @markdown("You can manage the buttons' variants, danger state and text with the `accept/cancel-btn-*` properties.");
        description: [
            [
                { text: "You can manage the buttons' variants, danger state and text with the " },
                { code: "accept/cancel-btn-*" },
                { text: " properties." }
            ]
        ];
    }

    WidgetPresentation {
        UButton {
            text: "Open modal";
            clicked => {
                UModalLogic.open-modal("modal-buttons-style");
            }
        }
    }

    DocCode {
        code: "UModal {\n    id: \"buttons-style-modal\";\n    title: \"Custom buttons\";\n    cancel-btn-variant: filled;\n    accept-btn-text: \"Delete\";\n    accept-btn-danger: true;\n    // Your modal's code.\n}";
    }

    DocSection {
        title: "Buttons enabled status and toggle";
        description-md: @markdown(
			"You can disable the accept and cancel buttons with the `accept/cancel-btn-enabled` properties.\n"
			"You can hide the buttons with the `accept/cancel-btn-toggle` properties."
		);
    }

    WidgetPresentation {
        UButton {
            text: "Open modal";
            clicked => {
                UModalLogic.open-modal("modal-buttons-toggles");
            }
        }
    }

    DocCode {
        code: "UModal {\n    id: \"buttons-toggles-modal\";\n    title: \"Disabled and hidden buttons\";\n    accept-btn-enabled: false;\n    cancel-btn-toggle: false;\n    // Your modal's code.\n}";
    }
}
