import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import { UTitle, UNotification } from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { AppLogic } from "../../app-logic.slint";


export component NotificationPage inherits PageBase {
    UTitle {
        level: 3;
        text: "Notification";
    }

    DocDescription {
        text: "A notification widget to be used inside the application.";
    }

    DocSection {
        title: "Example";
        description: [
            [
                {
                    text: "As the notification widget doesn't implement any logic, you must use it in a custom notification system like "
                },
                {
                    link: "this one",
                    url: "https://github.com/uAtomicBoolean/scriptboard/blob/main/ui/components/notifications-overlay.slint"
                },
                { text: "." }
            ],
            [
                { text: "To help with the implementation, it comes with two callbacks: " },
                { code: "close" },
                { text: " and " },
                { code: "clicked" },
                { text: "." }
            ],
            [
                { text: "The " },
                { code: "close" },
                { text: " callback is fired when clicking on the close button, and the " },
                { code: "clicked" },
                { text: " when clicking anywhere else in the notification." }
            ],
        ];
        link-clicked(url) => {
            AppLogic.open-url(url);
        }
    }

    WidgetPresentation {
        UNotification {
            title: "Simple notification";
        }
    }

    DocCode {
        code: "UNotification {\n    title: \"Simple notification\";\n}";
    }

    DocSection {
        title: "Notification content";
        description: [
            [
                { text: "You can add a message in the notification using the " },
                { code: "message" },
                { text: " property." }
            ],
            [
                {
                    text: "The message will be, by default, displayed on one line. But you change change that by setting "
                },
                { code: "single-line-message" },
                { text: " to " },
                { code: "false" },
                { text: "." }
            ],
            [
                { text: "Please note that the notification has a fixed width of " },
                { code: "300px" },
                { text: ". You are free to change that with the regular " },
                { code: "Rectangle" },
                { text: " properties." }
            ]
        ];
    }

    WidgetPresentation {
        HorizontalLayout {
            spacing: UAppTheme.spacing-bigger;
            VerticalLayout {
                alignment: start;
                UNotification {
                    title: "Single line message";
                    message: "This message is displayed only on one line to keep the notification with a small size.";
                }
            }

            UNotification {
                title: "Multi-line message";
                single-line-message: false;
                message: "This message is displayed on multiple lines to be fully visible.";
            }
        }
    }

    DocCode {
        code: "UNotification {\n    title: \"Single line message\";\n    message: \"This message is displayed only on one line to keep the notification with a small size.\";\n}\n\nUNotification {\n    title: \"Multi-line message\";\n    single-line-message: false;\n    message: \"This message is displayed on multiple lines to be fully visible.\";\n}";
    }

    DocSection {
        title: "Notification variants";
        description: [
            [
                { text: "The notification widget comes with four different variants: " },
                { code: "info" },
                { text: ", " },
                { code: "success" },
                { text: ", " },
                { code: "warning" },
                { text: " and " },
                { code: "danger" },
                { text: "." }
            ],
            [{ text: "The default variant is " }, { code: "info" }, { text:"." }]
        ];
    }

    WidgetPresentation {
        spacing: UAppTheme.spacing-bigger;
        VerticalLayout {
            spacing: UAppTheme.spacing-bigger;
            UNotification {
                title: "Info variant";
            }

            UNotification {
                variant: warning;
                title: "Warning variant";
            }
        }

        VerticalLayout {
            spacing: UAppTheme.spacing-bigger;
            UNotification {
                variant: success;
                title: "Success variant";
            }

            UNotification {
                variant: danger;
                title: "Danger variant";
            }
        }
    }

    DocCode {
        code: "UNotification {\n    title: \"Info variant\";\n}\n\nUNotification {\n    variant: success;\n    title: \"Success variant\";\n}\n\nUNotification {\n    variant: warning;\n    title: \"Warning variant\";\n}\n\nUNotification {\n    variant: danger;\n    title: \"Danger variant\";\n}";
    }

    DocSection {
        title: "Custom icon";
        description: [
            [
                { text: "You can change the icon and its color with the " },
                { code: "notif-icon" },
                { text: " and " },
                { code: "notif-icon-color" },
                { text: " properties." }
            ]
        ];
    }

    WidgetPresentation {
        UNotification {
            title: "Custom icon";
            notif-icon: @image-url("../../assets/images/rocket.svg");
            notif-icon-color: purple;
        }
    }
}
