import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import { UTitle, UNotification } from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { AppLogic } from "../../app-logic.slint";


export component NotificationPage inherits PageBase {
    UTitle {
        level: 3;
        text: "Notification";
    }

    DocDescription {
        text: "A notification widget to be used inside the application.";
    }

    DocSection {
        title: "Example";
        description: @markdown(
			"As the notification widget doesn't implement any logic, you must use it in a custom notification "
			"system like [this one](https://github.com/uAtomicBoolean/scriptboard/blob/main/ui/components/notifications-overlay.slint).\n"
			"To help with the implementation, it comes with two callbacks: `close` and `clicked`. The close "
			"callback is fired when clicking on the close button, and the clicked when clicking anywhere else in the notification."
		);
        link-clicked(url) => {
            Platform.open-url(url);
        }
    }

    WidgetPresentation {
        UNotification {
            title: "Simple notification";
        }
    }

    DocCode {
        code: "UNotification {\n    title: \"Simple notification\";\n}";
    }

    DocSection {
        title: "Notification content";
        description: @markdown(
			"You can add a message in the notification using the `message` property. The message "
			"will, by default, be displayed on one line. But you can change that by setting `single-line-message` "
			"to `false`.\nPlease note that the notification has a fixed width of `300px`. You are free to change "
			"that with the regular `Rectangle` properties."
		);
    }

    WidgetPresentation {
        HorizontalLayout {
            spacing: UAppTheme.spacing-bigger;
            VerticalLayout {
                alignment: start;
                UNotification {
                    title: "Single line message";
                    message: "This message is displayed only on one line to keep the notification with a small size.";
                }
            }

            UNotification {
                title: "Multi-line message";
                single-line-message: false;
                message: "This message is displayed on multiple lines to be fully visible.";
            }
        }
    }

    DocCode {
        code: "UNotification {\n    title: \"Single line message\";\n    message: \"This message is displayed only on one line to keep the notification with a small size.\";\n}\n\nUNotification {\n    title: \"Multi-line message\";\n    single-line-message: false;\n    message: \"This message is displayed on multiple lines to be fully visible.\";\n}";
    }

    DocSection {
        title: "Notification variants";
        description: @markdown(
			"The notification widget comes with four different variants: `info`, `success`, `warning` and `danger`. The default variant is `info`."
		);
    }

    WidgetPresentation {
        spacing: UAppTheme.spacing-bigger;
        VerticalLayout {
            spacing: UAppTheme.spacing-bigger;
            UNotification {
                title: "Info variant";
            }

            UNotification {
                variant: warning;
                title: "Warning variant";
            }
        }

        VerticalLayout {
            spacing: UAppTheme.spacing-bigger;
            UNotification {
                variant: success;
                title: "Success variant";
            }

            UNotification {
                variant: danger;
                title: "Danger variant";
            }
        }
    }

    DocCode {
        code: "UNotification {\n    title: \"Info variant\";\n}\n\nUNotification {\n    variant: success;\n    title: \"Success variant\";\n}\n\nUNotification {\n    variant: warning;\n    title: \"Warning variant\";\n}\n\nUNotification {\n    variant: danger;\n    title: \"Danger variant\";\n}";
    }

    DocSection {
        title: "Custom icon";
        description: @markdown(
			"You can change the icon and its color with the `notif-icon` and `notif-icon-color` properties."
		);
    }

    WidgetPresentation {
        UNotification {
            title: "Custom icon";
            icon: @image-url("../../assets/images/rocket.svg");
            icon-color: purple;
        }
    }

    DocCode {
        code: "UNotification {\n    title: \"Custom icon\";\n    icon: @image-url(your-path);\n    icon-color: purple;\n}";
    }
}
