import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import { UTitle, UPopover, UText, UButton } from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { AppLogic } from "../../app-logic.slint";


export component PopoverPage inherits PageBase {
    UTitle {
        level: 3;
        text: "Popover";
    }

    DocDescription {
        text: "A popover is a simple PopupWindow with a UCard as a background.";
    }

    DocSection {
        title: "How to use";
        description: [
            [
                { text: "This widget is used as a container with children." },
            ],
            [
                { text: "As it inherits from " },
                { link: "PopupWindow" },
                { text: ", you can configure the popover with the official properties." }
            ]
        ];
        link-clicked(id) => {
            AppLogic.open-url("https://docs.slint.dev/latest/docs/slint/reference/window/popupwindow/");
        }
    }

    WidgetPresentation {
        UButton {
            text: "Display popover";
            clicked => {
                popover.show();
            }
        }

        popover := UPopover {
            VerticalLayout {
                padding: UAppTheme.padding-base;
                spacing: UAppTheme.spacing-base;
                UText {
                    text: "A simple text contained in the popover.";
                }

                UButton {
                    variant: primary;
                    text: "Click me";
                }
            }
        }
    }

    DocCode {
        code: "UPopover {\n    VerticalLayout {\n        padding: 4px;\n        spacing: 4px;\n        UText {\n            text: \"Some simple text.\";\n\n        UButton {\n            variant: primary;\n            text: \"Click me\";\n        }\n    }\n}";
    }
}
