import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import {
    UText,
    UTitle,
    URadio,
} from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { AppLogic } from "../../app-logic.slint";
import { UMenuLogic } from "../../sleek-ui/widgets.slint";


export component RadioPage inherits PageBase {
    UTitle {
        level: 3;
        text: "Radio";
    }

    DocDescription {
        text: "A radio input allowing only one choice from a selection.";
    }

    DocSection {
        title: "Example";
        description-md: @markdown(
			"A radio takes a list of [UOptionData](option-data) and returns the currently "
			"selected value with the `selected-value` property."
		);
        link-clicked(url) => {
            UMenuLogic.current-link = url;
        }
    }

    WidgetPresentation {
        spacing: UAppTheme.spacing-bigger;
        radio := URadio {
            options: [
                { text: "Option 1", value:"option1", enabled: true },
                { text: "Option 2", value:"option2", enabled: true },
                { text: "Option 3", value:"option3", enabled: false },
            ];
        }

        UText {
            text: "Selected value: \{radio.selected-value}";
        }
    }

    DocCode {
        code: "URadio {\n    options: [\n        {text: \"Option 1\", value: \"option1\", enabled: true},\n        {text: \"Option 2\", value: \"option2\", enabled: true},\n        {text: \"Option 3\", value: \"option3\", enabled: false},\n    ]\n};";
    }

    DocSection {
        title: "Orientation";
        description-md: @markdown(
			"Use the `orientation` property to set the widget to a vertical or horizontal orientation."
		);
    }

    WidgetPresentation {
        URadio {
            orientation: horizontal;
            options: [
                { text: "Option 1", value:"option1", enabled: true },
                { text: "Option 2", value:"option2", enabled: true },
                { text: "Option 3", value:"option3", enabled: false },
            ];
        }
    }

    DocCode {
        code: "URadio {\n    orientation: horizontal;\n    // Your code\n};";
    }

    DocSection {
        title: "Disable the whole widget";
        description-md: @markdown("You can disable all the options with the `enabled` property.");
    }

    WidgetPresentation {
        URadio {
            enabled: false;
            options: [
                { text: "Option 1", value:"option1", enabled: true },
                { text: "Option 2", value:"option2", enabled: true },
                { text: "Option 3", value:"option3", enabled: false },
            ];
        }
    }

    DocCode {
        code: "URadio {\n    enabled: false;\n    // Your code\n};";
    }
}
