import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import {
    UText,
    UTitle,
    URadio,
    UCenter,
} from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { DocumentationLogic } from "../../logic/documentation-logic.slint";
import { UMenuLogic } from "../../sleek-ui/widgets.slint";


export component RadioPage inherits PageBase {
    UTitle {
        level: 3;
        text: "Radio";
    }

    DocDescription {
        text: "A radio input allowing only one choice from a selection.";
    }

    DocSection {
        title: "Example";
        description: [
            [
                { text: "A radio takes a list of " },
                { link:"OptionData", id: "option-data" },
                { text: " and return the currently selected value with the " },
                { code: "selected-value" },
                { text:" property." }
            ]
        ];
        link-clicked(id) => {
            if id == "option-data" {
                UMenuLogic.current-link = "option-data";
            }
        }
    }

    WidgetPresentation {
        spacing: UAppTheme.spacing-bigger;
        radio := URadio {
            options: [
                { text: "Option 1", value:"option1", enabled: true },
                { text: "Option 2", value:"option2", enabled: true },
                { text: "Option 3", value:"option3", enabled: false },
            ];
        }

        UText {
            text: "Selected value: \{radio.selected-value}";
        }
    }

    DocCode {
        code: "URadio {\n    options: [\n        {text: \"Option 1\", value: \"option1\", enabled: true},\n        {text: \"Option 2\", value: \"option2\", enabled: true},\n        {text: \"Option 3\", value: \"option3\", enabled: false},\n    ]\n};";
    }

    DocSection {
        title: "Orientation";
        description: [
            [
                { text: "You can choose the orientation with the " },
                { code: "orientation" },
                { text: " property, which is of type " },
                { code: "Orientation" },
                { text: "." }
            ]
        ];
    }

    WidgetPresentation {
        URadio {
            orientation: horizontal;
            options: [
                { text: "Option 1", value:"option1", enabled: true },
                { text: "Option 2", value:"option2", enabled: true },
                { text: "Option 3", value:"option3", enabled: false },
            ];
        }
    }

    DocCode {
        code: "URadio {\n    orientation: horizontal;\n    // Your code\n};";
    }

    DocSection {
        title: "Disable the whole widget";
        description: [
            [
                { text: "You can disable all the options with the " },
                { code: "enabled" },
                { text: " property." }
            ]
        ];
    }

    WidgetPresentation {
        URadio {
            enabled: false;
            options: [
                { text: "Option 1", value:"option1", enabled: true },
                { text: "Option 2", value:"option2", enabled: true },
                { text: "Option 3", value:"option3", enabled: false },
            ];
        }
    }

    DocCode {
        code: "URadio {\n    enabled: false;\n    // Your code\n};";
    }
}
