import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import {
    UText,
    UTitle,
    URadioButton,
} from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { AppLogic } from "../../app-logic.slint";
import { UMenuLogic } from "../../sleek-ui/widgets.slint";


export component RadioButtonPage inherits PageBase {
    UTitle {
        level: 3;
        text: "RadioButton";
    }

    DocDescription {
        text: "A radio but displayed as a group of buttons.";
    }

    DocSection {
        title: "Example";
        description: [
            [
                { text: "A radio button takes a list of " },
                { link:"UOptionData", url: "option-data" },
                { text: " and return the currently selected value with the " },
                { code: "selected-value" },
                { text:" property." }
            ],
            [
                { text:"Please note that you can't disable a single option, hence the " },
                { code:"UOptionData.enabled" },
                { text: " property is useless for this widget." }
            ]
        ];
        link-clicked(url) => {
            UMenuLogic.current-link = url;
        }
    }

    WidgetPresentation {
        spacing: UAppTheme.spacing-bigger;
        radio := URadioButton {
            options: [
                { text: "Option 1", value:"option1" },
                { text: "Option 2", value:"option2" },
                { text: "Option 3", value:"option3" },
                { text: "Option 4", value:"option4" },
            ];
        }

        UText {
            text: "Selected value: \{radio.selected-value}";
        }
    }

    DocCode {
        code: "URadioButton {\n    options: [\n        {text: \"Option 1\", value: \"option1\"},\n        {text: \"Option 2\", value: \"option2\"},\n        {text: \"Option 3\", value: \"option3\"},\n    ]\n};";
    }

    DocSection {
        title: "Primary variant";
        description: [
            [
                { text: "You can change the style of the widget by switching the " },
                { code: "variant" },
                { text: " property to " },
                { code: "primary" },
                { text: "." }
            ]
        ];
    }

    WidgetPresentation {
        URadioButton {
            variant: primary;
            options: [
                { text: "Option 1", value:"option1" },
                { text: "Option 2", value:"option2" },
                { text: "Option 3", value:"option3" },
            ];
        }
    }

    DocCode {
        code: "URadioButton {\n    variant: primary;\n    // Your code\n};";
    }

    DocSection {
        title: "Disable the whole widget";
        description: [
            [
                { text: "You can disable all the options with the " },
                { code: "enabled" },
                { text: " property." }
            ]
        ];
    }

    WidgetPresentation {
        URadioButton {
            enabled: false;
            options: [
                { text: "Option 1", value:"option1" },
                { text: "Option 2", value:"option2" },
                { text: "Option 3", value:"option3" },
            ];
        }
    }

    DocCode {
        code: "URadioButton {\n    enabled: false;\n    // Your code\n};";
    }
}
