import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import {
    UText,
    UTitle,
    URadioButton,
} from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { AppLogic } from "../../app-logic.slint";
import { UMenuLogic } from "../../sleek-ui/widgets.slint";


export component RadioButtonPage inherits PageBase {
    UTitle {
        level: 3;
        text: "RadioButton";
    }

    DocDescription {
        text: "A radio, but displayed as a group of buttons.";
    }

    DocSection {
        title: "Example";
        description-md: @markdown(
			"A radio button takes a list of [UOptionData](option-data) and returns the currently "
			"selected value with the `selected-value` property."
		);
        link-clicked(url) => {
            UMenuLogic.current-link = url;
        }
    }

    WidgetPresentation {
        spacing: UAppTheme.spacing-bigger;
        radio := URadioButton {
            options: [
                { text: "Option 1", value:"option1" },
                { text: "Option 2", value:"option2" },
                { text: "Option 3", value:"option3" },
                { text: "Option 4", value:"option4" },
            ];
        }

        UText {
            text: "Selected value: \{radio.selected-value}";
        }
    }

    DocCode {
        code: "URadioButton {\n    options: [\n        {text: \"Option 1\", value: \"option1\"},\n        {text: \"Option 2\", value: \"option2\"},\n        {text: \"Option 3\", value: \"option3\"},\n    ]\n};";
    }

    DocSection {
        title: "Primary variant";
        description-md: @markdown(
			"You can change the style of the widget by switching the `variant` property to `primary`."
		);
    }

    WidgetPresentation {
        URadioButton {
            variant: primary;
            selected-value: "option1";
            options: [
                { text: "Option 1", value:"option1" },
                { text: "Option 2", value:"option2" },
                { text: "Option 3", value:"option3" },
            ];
        }
    }

    DocCode {
        code: "URadioButton {\n    variant: primary;\n    // Your code\n};";
    }

    DocSection {
        title: "Disable the whole widget";
        description-md: @markdown("You can disable all the options with the `enabled` property.");
    }

    WidgetPresentation {
        URadioButton {
            enabled: false;
            options: [
                { text: "Option 1", value:"option1" },
                { text: "Option 2", value:"option2" },
                { text: "Option 3", value:"option3" },
            ];
        }
    }

    DocCode {
        code: "URadioButton {\n    enabled: false;\n    // Your code\n};";
    }
}
