import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import { UTitle, USelect } from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { AppLogic } from "../../app-logic.slint";
import { UMenuLogic } from "../../sleek-ui/widgets.slint";


export component SelectPage inherits PageBase {
    UTitle {
        level: 3;
        text: "Select";
    }

    DocDescription {
        text: "A simple select field to choose a value from a list.";
    }

    DocSection {
        title: "Basic usage";
        description-md: @markdown(
			"You can set the options with the `options` property of type [UOptionData](option-data).\n"
			"The `current-index` property defaults to `-1` until the user selects a value or you change it."
		);
        link-clicked(url) => {
            UMenuLogic.current-link = url;
        }
    }

    WidgetPresentation {
        USelect {
            options: [
                { text: "Option 1", value: "option1", enabled:true },
                { text: "Option 2", value: "option2", enabled:true },
                { text: "Option 3", value: "option3", enabled:true },
                { text: "Option 4", value: "option4", enabled:true },
                { text: "Option 5", value: "option5", enabled:true },
                { text: "Option 6", value: "option6", enabled:true },
                { text: "Option 7", value: "option7", enabled:true },
                { text: "Option 8", value: "option8", enabled:true },
            ];
        }
    }

    DocCode {
        code: "USelect {\n options: [\n        { text: \"French\", value: \"fr\", enabled: true },\n        { text: \"German\", value: \"de\", enabled: true },\n        { text: \"Italian\", value: \"it\", enabled: true },\n    ];\n}";
    }

    DocSection {
        title: "Current text and current value";
        description-md: @markdown(
			"Both `selected-text` and `selected-value` are available as `out` properties to directly get the selected values."
		);
    }

    DocCode {
        code: "USelect {\n    clicked => {\n        debug(self.selected-text);\n        debug(self.selected-value);\n    };\n}";
    }

    DocSection {
        title: "Selected changed callback";
        description-md: @markdown("The `selected-changed(new-index: int)` callback will be fired when the user selects a new value.");
    }

    DocCode {
        code: "USelect {\n    selected-changed(new-index) => {\n        debug(new-index);\n    }\n}";
    }

    DocSection {
        title: "Change the number of visible options";
        description-md: @markdown(
			"The widget will show, by default, at most 5 options. You can change this with the `max-visible-options` property."
		);
    }

    WidgetPresentation {
        USelect {
            max-visible-options: 2;
            options: [
                { text: "Option 1", value: "option1", enabled:true },
                { text: "Option 2", value: "option2", enabled:true },
                { text: "Option 3", value: "option3", enabled:true },
                { text: "Option 4", value: "option4", enabled:true },
                { text: "Option 5", value: "option5", enabled:true },
                { text: "Option 6", value: "option6", enabled:true },
                { text: "Option 7", value: "option7", enabled:true },
                { text: "Option 8", value: "option8", enabled:true },
            ];
        }
    }

    DocCode {
        code: "USelect {\n    max-visible-options: 2;\n    options: [// Your options here];\n}";
    }

    DocSection {
        title: "Display all options";
        description-md: @markdown(
			"You can display all the options with the `display-all-options` boolean property."
		);
    }

    WidgetPresentation {

        USelect {
            display-all-options: true;
            options: [
                { text: "Option 1", value: "option1", enabled:true },
                { text: "Option 2", value: "option2", enabled:true },
                { text: "Option 3", value: "option3", enabled:true },
                { text: "Option 4", value: "option4", enabled:true },
                { text: "Option 5", value: "option5", enabled:true },
                { text: "Option 6", value: "option6", enabled:true },
                { text: "Option 7", value: "option7", enabled:true },
                { text: "Option 8", value: "option8", enabled:true },
            ];
        }
    }

    DocCode {
        code: "USelect {\n    display-all-options: true;\n    options: [// Your options here];\n}";
    }
}
