import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import {
    UText,
    UTitle,
    USlider,
} from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { AppLogic } from "../../app-logic.slint";
import { Slider } from "std-widgets.slint";


export component SliderPage inherits PageBase {
    UTitle {
        level: 3;
        text: "Slider";
    }

    DocDescription {
        text: "A slider to select a value in a specified range.";
    }

    DocSection {
        title: "Example";
        description: @markdown(
			"Define the width of the slider and get its value with the `value` float property."
		);
    }

    WidgetPresentation {
        spacing: UAppTheme.spacing-bigger;
        slider := USlider {
            width: 300px;
            value: 50;
        }

        UText {
            text: "Value: \{slider.value}";
        }
    }

    DocCode {
        code: "USlider {\n    width: 300px;\n}";
    }

    DocSection {
        title: "Step and boundaries";
        description: @markdown(
			"Use the `step` property to change the slider's step.\n"
			"The `display-steps` property allows you to display dots "
			"representing the steps in the slider.\n"
			"Use the `min-value` and `max-value` to update the slider's range."
		);
    }

    WidgetPresentation {
        spacing: UAppTheme.spacing-bigger;
        slider-step := USlider {
            width: 300px;
            step: 10;
            display-steps: true;
            min-value: -30;
            max-value: 50;
        }

        UText {
            text: "Value: \{slider-step.value}";
        }
    }

    DocCode {
        code: "USlider {\n    width: 300px;\n    step: 0.5;\n    min-value: -30;\n    max-value: 50;\n}";
    }

    DocSection {
        title: "Handle position and released callback";
        description: @markdown(
			"The handle's position is available with the `handle-pos` property.\n"
			"The `release(value: float)` callback will be fired when the slider is "
			"clicked or a dragging action ended."
		);
    }

    DocCode {
        code: "slider := USlider {\n    width: 300px;\n    released(value) => {\n        debug(value);\n    }\n}\n\nUText {\n    text: \"\\{slider.handle-pos}\";\n}";
    }

    DocSection {
        title: "Orientation";
        description: @markdown(
			"Use the `orientation` property to set the slider to the vertical or horizontal (default).\n"
			"Remember to set the height or width depending on the chosen orientation."
		);
    }

    WidgetPresentation {
        USlider {
            height: 300px;
            orientation: vertical;
        }
    }

    DocCode {
        code: "USlider {\n    height: 300px;\n    orientation: vertical;\n}";
    }
}
