import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import {
    UTitle,
    USpinner,
    UCenter,
} from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { DocumentationLogic } from "../../logic/documentation-logic.slint";


export component SpinnerPage inherits PageBase {
    UTitle {
        level: 3;
        text: "Spinner";
    }

    DocDescription {
        text: "A simple spinner used to warn the user that something is loading.";
    }

    DocSection {
        title: "Example";
    }

    WidgetPresentation {
        USpinner { }
    }

    DocCode {
        code: "USpinner { }";
    }

    DocSection {
        title: "Customization";
        description: [
            [
                { text: "The spinner is easily customizable as it inherits from the " },
                { code: "Image" },
                { text: " standard widget. Moreover, a " },
                { code: "size" },
                { text: " property is available to change the spinner's size." }
            ]
        ];
    }

    WidgetPresentation {
        UCenter {
            USpinner {
                size: 16px;
            }
        }

        UCenter {
            USpinner {
                size: 24px;
                colorize: UAppTheme.success.base;
            }
        }

        UCenter {
            USpinner {
                size: 32px;
                colorize: UAppTheme.warning.base;
            }
        }

        UCenter {
            USpinner {
                size: 48px;
                colorize: UAppTheme.danger.base;
            }
        }

        UCenter {
            USpinner {
                size: 64px;
                colorize: UAppTheme.text;
            }
        }
    }

    DocCode {
        code: "USpinner {\n    size: 16px;\n}\n\nUSpinner {\n    size: 24px;\n    colorize: UAppTheme.success.base;\n}\n\nUSpinner {\n    size: 32px;\n    colorize: UAppTheme.warning.base;\n}\n\nUSpinner {\n    size: 48px;\n    colorize: UAppTheme.danger.base;\n}\n\nUSpinner {\n    size: 64px;\n    colorize: UAppTheme.text;\n}";
    }
}
