import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import { UTitle, UTabs } from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { AppLogic } from "../../app-logic.slint";
import { UText } from "../../sleek-ui/widgets/text.slint";


export component TabsPage inherits PageBase {
    UTitle {
        level: 3;
        text: "Tabs";
    }

    DocDescription {
        text: "An interactive widget to switch between different views.";
    }

    DocSection {
        title: "Default tabs";
        description-md: @markdown(
			"The widget takes a list of strings with the `tabs` property and "
			"updates the `current-index` property when a tab is selected."
		);
    }

    WidgetPresentation {
        full-width: true;
        UTabs {
            tabs: ["First tab", "Second tab", "Third tab"];
            if self.current-index == 0: UText {
                text: "First tab content";
            }
            if self.current-index == 1: UText {
                text: "Second tab content";
            }
            if self.current-index == 2: UText {
                text: "Third tab content";
            }
        }
    }

    DocCode {
        code: "UTabs {\n    tabs: [\"First tab\", \"Second tab\", \"Third tab\"]\n    if self.current-index == 0: UText {\n        text: \"First tab content\";\n    }\n     if self.current-index == 1: UText {\n        text: \"Second tab content\";\n    }\n    if self.current-index == 2: UText {\n        text: \"Third tab content\";\n    }\n}";
    }

    DocSection {
        title: "Tabs alignment";
        description-md: @markdown(
			"You can set the `tabs-alignment` property to `start` to have "
			"tabs that take the minimum width to display their text.\n"
			"Otherwise, the property defaults to `stretch`."
		);
    }

    WidgetPresentation {
        full-width: true;
        UTabs {
            tabs: ["First tab", "Second tab", "Third tab"];
            tabs-alignment: start;
        }
    }

    DocCode {
        code: "UTabs {\n    tabs: [\"First tab\", \"Second tab\", \"Third tab\"]\n    tabs-alignment: stretch;\n}";
    }
}
