import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import { UTitle, UTabs } from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { AppLogic } from "../../app-logic.slint";
import { UText } from "../../sleek-ui/widgets/text.slint";


export component TabsPage inherits PageBase {
    UTitle {
        level: 3;
        text: "Tabs";
    }

    DocDescription {
        text: "An interactive widget to switch between different views.";
    }

    DocSection {
        title: "Default tabs";
        description: [
            [
                { text: "The widget takes a list of tabs as strings with the " },
                { code: "tabs" },
                { text: " property, and update the " },
                { code: "current-index" },
                { text: " property when switching tabs." }
            ]
        ];
    }

    WidgetPresentation {
        UTabs {
            tabs: ["First tab", "Second tab", "Third tab"];
            if self.current-index == 0: UText {
                text: "First tab content";
            }
            if self.current-index == 1: UText {
                text: "Second tab content";
            }
            if self.current-index == 2: UText {
                text: "Third tab content";
            }
        }
    }

    DocCode {
        code: "UTabs {\n    tabs: [\"First tab\", \"Second tab\", \"Third tab\"]\n    if self.current-index == 0: UText {\n        text: \"First tab content\";\n    }\n     if self.current-index == 1: UText {\n        text: \"Second tab content\";\n    }\n    if self.current-index == 2: UText {\n        text: \"Third tab content\";\n    }\n}";
    }

    DocSection {
        title: "Stretched tabs";
        description: [
            [
                { text: "You can use set the " },
                { code: "tabs-alignment" },
                { text: " property to " },
                { code: "stretch" },
                { text: " to have tabs that take the while width of the page (defaults to " },
                { code: "start" },
                { text: ")." }
            ]
        ];
    }

    WidgetPresentation {
        full-width: true;
        UTabs {
            tabs: ["First tab", "Second tab", "Third tab"];
            tabs-alignment: stretch;
        }
    }

    DocCode {
        code: "UTabs {\n    tabs: [\"First tab\", \"Second tab\", \"Third tab\"]\n    tabs-alignment: stretch;\n}";
    }
}
