import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import { UTitle, UText } from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { DocumentationLogic } from "../../logic/documentation-logic.slint";


export component TextPage inherits PageBase {
    UTitle {
        level: 3;
        text: "Text";
    }

    DocDescription {
        text: "A simple text widget with a pre-configured style.";
    }

    DocSection {
        title: "Usage";
        description: [
            [
                {
                    text: "This widget inherits from the standart Text widget and define a style. There is no additional properties."
                },
            ]
        ];
    }

    WidgetPresentation { }

    DocCode {
        code: "UText {\n    text: \"Some simple text\";\n}";
    }
}
