import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import { UTitle } from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { DocumentationLogic } from "../../logic/documentation-logic.slint";


export component TitlePage inherits PageBase {
    UTitle {
        level: 3;
        text: "Title";
    }

    DocDescription {
        text: "A simple title widget that comes with 6 defined levels.";
    }

    DocSection {
        title: "Usage";
        description: [
            [
                { text: "This widget inherits from the standart Text widget, but adds a new " },
                { code: "level" },
                { text: " property." }
            ],
            [
                { text: "The levels go from " },
                { code: "1" },
                { text: " to " },
                { code: "6" },
                { text: " , with " },
                { code: "1" },
                { text: " being the biggest title." }
            ]
        ];
    }

    WidgetPresentation {
        VerticalLayout {
            spacing: UAppTheme.spacing-base;
            UTitle {
                level: 1;
                text: "Title with a level of 1";
            }

            UTitle {
                level: 2;
                text: "Title with a level of 2";
            }

            UTitle {
                level: 3;
                text: "Title with a level of 3";
            }

            UTitle {
                level: 4;
                text: "Title with a level of 4";
            }

            UTitle {
                level: 5;
                text: "Title with a level of 5";
            }

            UTitle {
                level: 6;
                text: "Title with a level of 6";
            }
        }
    }

    DocCode {
        code: "UTitle {\n    level: 6;\n    text: \"Some simple text\";\n}";
    }
}
