import { UAppTheme } from "../../sleek-ui/app-theme.slint";
import {
    UAlert,
    UTitle,
    UText,
    UTooltip,
    UTooltipLogic,
} from "../../sleek-ui/widgets.slint";

import {
    DocTitle,
    DocDescription,
    WidgetPresentation,
    DocSection,
    DocCode,
} from "../../components/doc-widgets.slint";
import { PageBase } from "../../components/page-base.slint";
import { AppLogic } from "../../app-logic.slint";


export component TooltipPage inherits PageBase {
    UTitle {
        level: 3;
        text: "Tooltip";
    }

    DocDescription {
        text: "A widget to display some information with styled text when hovering something.";
    }

    HorizontalLayout {
        padding-top: UAppTheme.padding-base;
        padding-bottom: UAppTheme.padding-base;
        UAlert {
            message: @markdown("You can also use the official Tooltip widget from slint which allows you to have custom content.");
        }
    }

    DocSection {
        title: "How to use";
        description-md: @markdown(
			"You can use a tooltip by adding the `UTooltip` widget at the "
			"root of the window after your main elements. This ensures that "
			"the tooltip will be displayed above the other elements in your "
			"window.\nUse the `UTooltipLogic.display()` method to display "
			"a tooltip. This function takes all the following parameters: "
			"the tooltip's styled text, the display position, the absolute "
			"position and the width of the targeted element.\nThe full method's "
			"signature is the following:\n"
			"`display(text: styled-text, position: string, user_hovering: bool, target_pos: Point, target_width: length, target_height: length)`"
		);
    }

    WidgetPresentation {
        HorizontalLayout {
            Rectangle {
                border-width: 1px;
                border-color: UAppTheme.text;
                HorizontalLayout {
                    padding: UAppTheme.padding-base;
                    UText {
                        text: "Hover this text to display the tooltip.";
                    }
                }

                TouchArea {
                    changed has-hover => {
                        UTooltipLogic.display(@markdown("A simple tooltip to display some information."), "", self.has-hover, self.absolute-position, self.width, self.height);
                    }
                }
            }
        }
    }

    DocCode {
        code: "// This code is in a component or page somewhere in the window.\nUText {\n    text: \"Some simple text\";\n    TouchArea {\n        changed has-hover => {\n            UTooltipLogic.display(@markdown(\"The tooltip's text.\"), \"\", self.has-hover, self.absolute-position, self.width, self.height);\n        }\n    }\n}";
    }

    DocCode {
        code: "export component AppWindow inherits Window {\n    // Your elements...\n    UTooltip { }\n}";
    }

    DocSection {
        title: "Tooltip position";
        description-md: @markdown(
			"A tooltip can be placed at the following positions: `top`, `bottom`, "
			"`left` and `right`.\nIts position is defined in the second parameter of "
			"the `UTooltipLogic.display()` method.\nSending an empty string defaults to `top`."
		);
    }

    WidgetPresentation {
        HorizontalLayout {
            Rectangle {
                border-width: 1px;
                border-color: UAppTheme.text;
                HorizontalLayout {
                    padding: UAppTheme.padding-base;
                    UText {
                        text: "Hover this text to display the tooltip on the right.";
                    }
                }

                TouchArea {
                    changed has-hover => {
                        UTooltipLogic.display(@markdown("A simple tooltip to display some information."), "right", self.has-hover, self.absolute-position, self.width, self.height);
                    }
                }
            }
        }
    }

    DocCode {
        code: "UTooltipLogic.display(@markdown(\"The tooltip's text.\"), \"right\", ...);";
    }

    DocSection {
        title: "Tooltip configuration";
        description-md: @markdown(
			"You can modify the following settings on the tooltip: `delay`, "
			"`tooltip-max-width` and `tooltip-max-height`.\nAll three properties "
			"are declared in the tooltip's widget to allow application wide configuration "
			"and to reduce the amount of parameters in the display method."
		);
    }

    DocCode {
        code: "UTooltip {\n    delay: 1s;\n    tooltip-max-width: 200px;\n    tooltip-max-height: 200px;\n}";
    }
}
