export struct AppTheme {
    // Primary color.
    primary: brush,
    primary-hover: brush,
    primary-active: brush,
    primary-disabled: brush,
    primary-selected: brush,

    // Success color.
    success: brush,
    success-hover: brush,
    success-active: brush,
    success-disabled: brush,
    success-selected: brush,

    // Warning color.
    warning: brush,
    warning-hover: brush,
    warning-active: brush,
    warning-disabled: brush,
    warning-selected: brush,

    // Danger color.
    danger: brush,
    danger-hover: brush,
    danger-active: brush,
    danger-disabled: brush,
    danger-selected: brush,

    // Background color
    bg-container: brush,
    bg-elevated: brush,
    bg-layout: brush,
	bg-inverse: brush,

    // Color fill
    color-fill-plus: brush,
    color-fill: brush,
    color-fill-secondary: brush,
    color-fill-tertiary: brush,
    color-fill-quaternary: brush,

    // Shadow
    shadow-blur: length,
    shadow-color: brush,
    shadow-x-offset: length,
    shadow-y-offset: length,

    // Text color
    inverse-text: brush,
    text: brush,
    text-secondary: brush,
    text-heading: brush,
    text-disabled: brush,

	// Font size
	font-size-smaller: length,
    font-size-small: length,
    font-size-base: length,
    font-size-medium: length,
    font-size-big: length,
    font-size-bigger: length,

	// Focus display
    focus-color: brush,
	focus-border-width: length,

    // Borders
	border-width-base: length,
    border: brush,
    border-secondary: brush,
    separator: brush,

    // Icons
    icon-size-base: length,

    // Padding
    padding-vertical: length,
    padding-horizontal: length,
    padding-small: length,
    padding-base: length,
    padding-medium: length,
    padding-big: length,
    padding-bigger: length,

    // Spacing
    spacing-small: length,
    spacing-base: length,
    spacing-medium: length,
    spacing-big: length,
    spacing-bigger: length,

    // Radius
    radius-base: length,
    radius-small: length,
    radius-medium: length,
    radius-large: length,
    radius-round: length,
    radius-circle: length,
}
