import { AppTheme} from "app-theme-struct.slint";

export global GeekBlueTheme {
    out property <AppTheme> light-theme: {
        // Primary
        primary: #2f54eb,
        primary-hover: #597ef7,
        primary-active: #1d39c4,
        primary-disabled: #85a5ff,
        primary-selected: #f0f5ff,

        // Success
        success: #52c41a,
        success-hover: #73d13d,
        success-active: #389e0d,
        success-disabled: #95de64,
        success-selected: #f6ffed,

        // Warning
        warning: #faad14,
        warning-hover: #ffc53d,
        warning-active: #d48806,
        warning-disabled: #ffd666,
        warning-selected: #fffbe6,

        // Danger
        danger: #ff4d4f,
        danger-hover: #ff7875,
        danger-active: #d9363e,
        danger-disabled: #ff7875,
        danger-selected: #fff1f0,

        // Background color
        bg-layout: #F5F5F5,
        bg-container: Colors.white,
        bg-elevated: Colors.white,
        bg-inverse: #262626,

        // Color fill
        color-fill-plus: rgba(0, 0, 0, 0.25),
        color-fill: rgba(0, 0, 0, 0.15),
        color-fill-secondary: rgba(0, 0, 0, 0.06),
        color-fill-tertiary: rgba(0, 0, 0, 0.04),
        color-fill-quaternary: rgba(0, 0, 0, 0.02),

        // Shadow
        shadow-color: rgba(0, 0, 0, 0.12),
        shadow-blur: 16px,
        shadow-x-offset: 0px,
        shadow-y-offset: 6px,

        // Text color
        inverse-text: rgba(255,255,255,0.85),
        text: #000000E0,
        text-secondary: #000000A6,
        text-heading: #000000E0,
        text-disabled: #00000040,

        // Font size
        font-size-smaller: 10px,
        font-size-small: 12px,
        font-size-base: 14px,
        font-size-medium: 16px,
        font-size-big: 18px,
        font-size-bigger: 20px,
  
        // Focus display
        focus-color: Colors.black,
        focus-border-width: 2px,

        // Borders
        border-width-base: 1px,
        border: #D9D9D9,
        border-secondary: #f0f0f0,
        separator: #0505050F,

        // Icons
        icon-size-base: 16px,

        // Padding
        padding-vertical: 5px,
        padding-horizontal: 14px,
        padding-small: 2px,
        padding-base: 4px,
        padding-medium: 8px,
        padding-big: 12px,
        padding-bigger: 16px,

        // Spacing
        spacing-small: 2px,
        spacing-base: 4px,
        spacing-medium: 8px,
        spacing-big: 12px,
        spacing-bigger: 16px,

        // Radius
        radius-base: 4px,
        radius-small: 2px,
        radius-medium: 4px,
        radius-large: 8px,
        radius-round: 20px,
        radius-circle: 9999px,
    };
    out property <AppTheme> dark-theme: {
        // Primary
        primary: #2b4acb,
        primary-hover: #5273e0,
        primary-active: #263ea0,
        primary-disabled: #203175,
        primary-selected: #1c2755,

        // Success
        success: #49aa19,
        success-hover: #6abe39,
        success-active: #3c8618,
        success-disabled: #306317,
        success-selected: #162312,

        // Warning
        warning: #d89614,
        warning-hover: #e8b339,
        warning-active: #aa7714,
        warning-disabled: #7c5914,
        warning-selected: #2b2111,

        // Danger
        danger: #dc4446,
        danger-hover: #e86e6b,
        danger-active: #ad393a,
        danger-disabled: #791a1f,
        danger-selected: #2a1215,

        // Background color
        bg-layout: #000000,
        bg-container: #141414,
        bg-elevated: #1f1f1f,
        bg-inverse: #424242,

        // Color fill
        color-fill-plus: rgba(255,255,255, 0.28),
        color-fill: rgba(255,255,255,0.18),
        color-fill-secondary: rgba(255,255,255,0.12),
        color-fill-tertiary: rgba(255,255,255,0.08),
        color-fill-quaternary: rgba(255,255,255,0.04),

        // Shadow
        shadow-color: rgba(0, 0, 0, 0.12),
        shadow-blur: 16px,
        shadow-x-offset: 0px,
        shadow-y-offset: 6px,

        // Text color
        inverse-text: rgba(0,0,0,0.88),
        text: #FFFFFFD9,
        text-secondary: #FFFFFFA6,
        text-heading: #FFFFFFD9,
        text-disabled: #FFFFFF40,

        // Font size
        font-size-smaller: 10px,
        font-size-small: 12px,
        font-size-base: 14px,
        font-size-medium: 16px,
        font-size-big: 18px,
        font-size-bigger: 20px,

        // Focus display
        focus-color: Colors.white,
        focus-border-width: 2px,
            
        // Borders
        border-width-base: 1px,
        border: #424242,
        border-secondary: #303030,
        separator: #FDFDFD1F,

        // Icons
        icon-size-base: 16px,

        // Padding
        padding-vertical: 5px,
        padding-horizontal: 14px,
        padding-small: 2px,
        padding-base: 4px,
        padding-medium: 8px,
        padding-big: 12px,
        padding-bigger: 16px,

        // Spacing
        spacing-small: 2px,
        spacing-base: 4px,
        spacing-medium: 8px,
        spacing-big: 12px,
        spacing-bigger: 16px,

        // Radius
        radius-base: 4px,
        radius-small: 2px,
        radius-medium: 4px,
        radius-large: 8px,
        radius-round: 20px,
        radius-circle: 9999px,
    };
}
