// A simple component used to implement a button-like comportment.
// This is used to manage clicking with the left mouse button, with 
// the space and return keys and to manage focus.
import { UAppTheme } from "../app-theme.slint";
export component ButtonInterface inherits Rectangle {
    in-out property <bool> enabled: true;
    in-out property <MouseCursor> touch-mouse-cursor: pointer;
    out property <bool> has-focus <=> focus-scope.has-focus;
    out property <bool> has-hover <=> touch.has-hover;
    out property <bool> pressed <=> touch.pressed;
    out property <MouseCursor> mouse-cursor <=> touch.mouse-cursor;
    out property <length> mouse-x <=> touch.mouse-x;
    out property <length> mouse-y <=> touch.mouse-y;
    out property <length> pressed-x <=> touch.pressed-x;
    out property <length> pressed-y <=> touch.pressed-y;

    callback clicked();
	// TouchArea callbacks
    callback double-clicked();
    callback moved();
    callback pointer-event();
    callback scroll-event() -> EventResult;
	// FocusScope callbacks
	callback key-pressed <=> focus-scope.key-pressed;
    callback key-released <=> focus-scope.key-released;
    callback focus-changed-event <=> focus-scope.focus-changed-event;
    animate background, border-color { duration: UAppTheme.animation-duration; }
    focus-scope := FocusScope {
        enabled: root.enabled;
        key-pressed(event) => {
            if event.text == Key.Space || event.text == Key.Return {
                root.clicked();
                accept
            }
            if event.text == Key.Escape {
                self.clear-focus();
            }
            reject
        }
    }

    touch := TouchArea {
        mouse-cursor: root.enabled ? root.touch-mouse-cursor : not-allowed;
        clicked => {
            if root.enabled {
                focus-scope.focus();
                focus-scope.clear-focus();
                root.clicked();
            }
        }
        double-clicked => {
            if root.enabled {
                root.double-clicked();
            }
        }
        moved => {
            if root.enabled {
                root.moved();
            }
        }
        pointer-event => {
            if root.enabled {
                root.pointer-event();
            }
        }
        scroll-event => {
            if root.enabled {
                return root.scroll-event();
            }
            EventResult.reject
        }
    }
}
