import { UAppTheme } from "../app-theme.slint";

import { ButtonInterface } from "button-interface.slint";
import { IconTextPlacement } from "../structs/icon-placement.slint";

import { UIcon } from "icon.slint";
import { USpinner } from "spinner.slint";
import { UText } from "text.slint";


export struct UButtonThemeColor {
	base: brush,
	danger: brush,
}

export enum UButtonVariant {
	primary,
	default,
	filled,
	text,
	custom,
}

export component UButton inherits ButtonInterface {
	// Accessability properties
	accessible-role: button;
    accessible-label: self.text;
    accessible-action-default => {
        self.clicked()
    }
	// Theming properties
	in-out property <length> t-border-width;
    in-out property <length> t-border-radius: UAppTheme.radius-base;
    in-out property <length> t-content-spacing: UAppTheme.spacing-base;
    in-out property <length> t-padding-vertical: UAppTheme.padding-vertical;
    in-out property <length> t-padding-horizontal: UAppTheme.padding-horizontal;
    in-out property <length> t-font-size: UAppTheme.font-size-base;
    in-out property <length> t-icon-size: UAppTheme.icon-size-base;
    in-out property <UButtonThemeColor> t-background;
    in-out property <UButtonThemeColor> t-background-hover;
    in-out property <UButtonThemeColor> t-background-active;
    in-out property <UButtonThemeColor> t-background-checked;
    in-out property <UButtonThemeColor> t-background-disabled;
    in-out property <UButtonThemeColor> t-text-color;
    in-out property <UButtonThemeColor> t-text-color-hover;
    in-out property <UButtonThemeColor> t-text-color-active;
    in-out property <UButtonThemeColor> t-text-color-checked;
    in-out property <UButtonThemeColor> t-text-color-disabled;
    in-out property <UButtonThemeColor> t-border;
    in-out property <UButtonThemeColor> t-border-hover;
    in-out property <UButtonThemeColor> t-border-active;
    in-out property <UButtonThemeColor> t-border-checked;
    in-out property <UButtonThemeColor> t-border-disabled;
	// Regular properties
    in-out property <UButtonVariant> variant: default;
    in-out property <string> text <=> text-obj.text;
    in-out property <bool> danger: false;
    in-out property <bool> loading: false;
    in-out property <bool> checked: false;
    in-out property <image> icon;
    in-out property <bool> colorize-icon: true;
    in-out property <IconTextPlacement> icon-placement: IconTextPlacement.hidden;
    enabled: !loading;
    background: get-background();
    border-radius: t-border-radius;
    border-width: self.has-focus ? UAppTheme.focus-border-width : t-border-width;
    border-color: self.has-focus ? UAppTheme.focus-color : get-border-color();
    if loading: Rectangle {
        z: 10;
        width: parent.width;
        height: parent.height;
        border-radius: t-border-radius;
        border-width: t-border-width;
        border-color: get-color(t-border);
        HorizontalLayout {
            alignment: center;
            VerticalLayout {
                alignment: center;
                USpinner {
                    colorize: get-color(t-text-color);
                    states [
                        disabled when !root.enabled: {
                            colorize: get-color(t-text-color-disabled);
                        }
                    ]
                }
            }
        }
    }
    HorizontalLayout {
        alignment: center;
        spacing: t-content-spacing;
        padding-top: t-padding-vertical;
        padding-bottom: t-padding-vertical;
        padding-left: t-padding-horizontal;
        padding-right: t-padding-horizontal;
        if icon-placement == IconTextPlacement.start: VerticalLayout {
            alignment: center;
            icon-start := UIcon {
                visible: !loading;
                source: icon;
                colorize: colorize-icon ? get-color(t-text-color) : transparent;
                size: t-icon-size;
                animate colorize { duration: 200ms; }
                states [
                    loading when root.loading: {
                        colorize: transparent;
                    }
                    disabled when !root.enabled: {
                        colorize: colorize-icon ? get-color(t-text-color-disabled) : transparent;
                    }
                    checked when root.checked: {
                        colorize: colorize-icon ? get-color(t-text-color-checked) : transparent;
                    }
                    active when root.pressed: {
                        colorize: colorize-icon ? get-color(t-text-color-active) : transparent;
                    }
                    hover when root.has-hover: {
                        colorize: colorize-icon ? get-color(t-text-color-hover) : transparent;
                    }
                ]
            }
        }
        VerticalLayout {
            alignment: center;
            text-obj := UText {
                color: get-color(t-text-color);
                font-size: t-font-size;
                animate color { duration: 200ms; }
				// Managing the text's states here as the states' order is different from the
				// component.
				states [
                    loading when root.loading: {
                        color: transparent;
                    }
                    disabled when !root.enabled: {
                        color: !root.loading ? get-color(t-text-color-disabled) : transparent;
                    }
                    checked when root.checked: {
                        color: !root.loading ? get-color(t-text-color-checked) : transparent;
                    }
                    active when root.pressed: {
                        color: !root.loading ? get-color(t-text-color-active) : transparent;
                    }
                    hover when root.has-hover: {
                        color: !root.loading ? get-color(t-text-color-hover) : transparent;
                    }
                ]
            }
        }

        if icon-placement == IconTextPlacement.end: VerticalLayout {
            alignment: center;
            icon-end := UIcon {
                visible: !loading;
                source: icon;
                colorize: colorize-icon ? get-color(t-text-color) : transparent;
                size: t-icon-size;
                animate colorize { duration: 200ms; }
                states [
                    loading when root.loading: {
                        colorize: transparent;
                    }
                    disabled when !root.enabled: {
                        colorize: colorize-icon ? get-color(t-text-color-disabled) : transparent;
                    }
                    checked when root.checked: {
                        colorize: colorize-icon ? get-color(t-text-color-checked) : transparent;
                    }
                    active when root.pressed: {
                        colorize: colorize-icon ? get-color(t-text-color-active) : transparent;
                    }
                    hover when root.has-hover: {
                        colorize: colorize-icon ? get-color(t-text-color-hover) : transparent;
                    }
                ]
            }
        }
    }

    function get-color(c: UButtonThemeColor) -> brush {
        return self.danger ? c.danger : c.base;
    }

	// Managing the background and border colors with a function allows use to 
	// not use a states list for both properties.
	// Thanks to this, we can use a states list for the variants which remove
	// a bug in which the colors are not updated when switching color schemes 
	// while using an 'init' to instantiate the variants.
    function get-background() -> brush {
        if !self.enabled {
            return get-color(t-background-disabled);
        }
        if self.pressed {
            return get-color(t-background-active);
        }
        if self.has-hover {
            return get-color(t-background-hover);
        }
        if self.checked {
            return get-color(t-background-checked);
        }
        return get-color(t-background);
    }
    function get-border-color() -> brush {
        if !self.enabled {
            return get-color(t-border-disabled);
        }
        if self.pressed {
            return get-color(t-border-active);
        }
        if self.has-hover {
            return get-color(t-border-hover);
        }
        if self.checked {
            return get-color(t-border-checked);
        }
        return get-color(t-border);
    }
    states [
        primary when variant == UButtonVariant.primary: {
            t-border-width: UAppTheme.border-width-base;
            t-background: { base: UAppTheme.primary, danger: UAppTheme.danger };
            t-background-hover: { base: UAppTheme.primary-hover, danger: UAppTheme.danger-hover };
            t-background-active: { base: UAppTheme.primary-active, danger: UAppTheme.danger-active };
            t-background-checked: { base: UAppTheme.primary, danger: UAppTheme.danger };
            t-background-disabled: { base: UAppTheme.border-secondary, danger: UAppTheme.border-secondary };
            t-text-color: { base: Colors.white, danger: Colors.white };
            t-text-color-hover: { base: Colors.white, danger: Colors.white };
            t-text-color-active: { base: Colors.white, danger: Colors.white };
            t-text-color-checked: { base: Colors.white, danger: Colors.white };
            t-text-color-disabled: { base: UAppTheme.text-disabled, danger: UAppTheme.text-disabled };
            t-border-disabled: { base: UAppTheme.border, danger: UAppTheme.border };
        }
        default when variant == UButtonVariant.default: {
            t-border-width: UAppTheme.border-width-base;
            t-background-hover: { base: UAppTheme.color-fill-tertiary, danger: Colors.transparent };
            t-background-active: { base: UAppTheme.color-fill-secondary, danger: UAppTheme.danger-selected };
            t-background-checked: { base: UAppTheme.primary-selected, danger: UAppTheme.danger-selected };
            t-text-color: { base: UAppTheme.text, danger: UAppTheme.danger };
            t-text-color-hover: { base: UAppTheme.text, danger: UAppTheme.danger-hover };
            t-text-color-active: { base: UAppTheme.text, danger: UAppTheme.danger-active };
            t-text-color-checked: { base: UAppTheme.primary, danger: UAppTheme.danger };
            t-text-color-disabled: { base: UAppTheme.text-disabled, danger: UAppTheme.text-disabled };
            t-border: { base: UAppTheme.border, danger: UAppTheme.danger };
            t-border-hover: { base: UAppTheme.border, danger: UAppTheme.danger };
            t-border-active: { base: UAppTheme.border, danger: UAppTheme.danger };
            t-border-checked: { base: UAppTheme.primary, danger: UAppTheme.danger };
            t-border-disabled: { base: UAppTheme.border, danger: UAppTheme.border };
        }
        filled when variant == UButtonVariant.filled: {
            t-background: { base: UAppTheme.color-fill-tertiary, danger: UAppTheme.danger.with-alpha(0.1) };
            t-background-hover: {
                base: UAppTheme.color-fill-secondary,
                danger: UAppTheme.danger-hover.with-alpha(0.3)
            };
            t-background-active: { base: UAppTheme.color-fill, danger: UAppTheme.danger-active.with-alpha(0.4) };
            t-background-checked: { base: UAppTheme.primary-selected, danger: UAppTheme.danger-selected };
            t-text-color: { base: UAppTheme.text, danger: UAppTheme.danger };
            t-text-color-hover: { base: UAppTheme.text, danger: UAppTheme.danger-hover };
            t-text-color-active: { base: UAppTheme.text, danger: UAppTheme.danger-active };
            t-text-color-checked: { base: UAppTheme.primary, danger: UAppTheme.danger };
            t-text-color-disabled: { base: UAppTheme.text-disabled, danger: UAppTheme.text-disabled };
        }
        text when variant == UButtonVariant.text: {
            t-background-hover: {
                base: UAppTheme.color-fill-secondary,
                danger: UAppTheme.danger-hover.with-alpha(0.1)
            };
            t-background-active: { base: UAppTheme.color-fill, danger: UAppTheme.danger-active.with-alpha(0.3) };
            t-text-color: { base: UAppTheme.text, danger: UAppTheme.danger };
            t-text-color-hover: { base: UAppTheme.text, danger: UAppTheme.danger-hover };
            t-text-color-active: { base: UAppTheme.text, danger: UAppTheme.danger-active };
            t-text-color-checked: { base: UAppTheme.primary, danger: UAppTheme.danger };
            t-text-color-disabled: { base: UAppTheme.text-disabled, danger: UAppTheme.text-disabled };
        }
    ]
}
