import { UAppTheme } from "../app-theme.slint";

import {
    UButtonVariant,
    UButtonTheme,
    UButtonThemes,
} from "common/button.slint";

import { ButtonInterface } from "button-interface.slint";
import { IconTextPlacement } from "common/enums.slint";

import { UIcon } from "icon.slint";
import { USpinner } from "spinner.slint";
import { UText } from "text.slint";


export component UButton inherits ButtonInterface {
	// Accessibility properties
	accessible-role: button;
    accessible-label: self.text;
    accessible-action-default => {
        self.clicked()
    }
	// Regular properties
    in-out property <UButtonVariant> variant: default;
    private property <UButtonTheme> theme: {
        if variant == primary {
            return danger ? UButtonThemes.primary-danger : UButtonThemes.primary;
        }
        if variant == filled {
            return danger ? UButtonThemes.filled-danger : UButtonThemes.filled;
        }
        if variant == UButtonVariant.text {
            return danger ? UButtonThemes.text-danger : UButtonThemes.text;
        }
        return danger ? UButtonThemes.default-danger : UButtonThemes.default;
    };
    in-out property <string> text <=> text-obj.text;
    in-out property <bool> danger: false;
    in-out property <bool> loading: false;
    in-out property <bool> checked: false;
    in-out property <image> icon;
    in-out property <bool> colorize-icon: true;
    in-out property <IconTextPlacement> icon-placement: IconTextPlacement.hidden;
    changed enabled => {
        if root.loading && root.enabled {
            root.enabled = false;
        }
    }
    changed loading => {
        root.enabled = !root.loading;
    }
    init => {
        if variant == text-stripped {
            debug("The 'text-stripped' variant is not supported in the 'UButton' widget. Defaulting to 'default'.");
        }
        if root.loading {
            root.enabled = false;
        }
    }
    background: theme.bg;
    border-radius: UAppTheme.radius-base;
    border-width: self.has-tab-focus ? UAppTheme.focus-border-width : theme.border-width;
    border-color: self.has-tab-focus ? UAppTheme.focus-color : theme.border;
    if loading: Rectangle {
        z: 10;
        width: parent.width;
        height: parent.height;
        border-radius: UAppTheme.radius-base;
        border-width: theme.border-width;
        border-color: theme.border;
        VerticalLayout {
            alignment: center;
            cross-axis-alignment: center;
            USpinner {
                colorize: theme.text;
            }
        }
    }
    HorizontalLayout {
        alignment: center;
        cross-axis-alignment: center;
        spacing: UAppTheme.spacing-base;
        padding-top: UAppTheme.padding-vertical;
        padding-bottom: UAppTheme.padding-vertical;
        padding-left: UAppTheme.padding-horizontal;
        padding-right: UAppTheme.padding-horizontal;
        if icon-placement == IconTextPlacement.start: VerticalLayout {
            alignment: center;
            icon-start := UIcon {
                visible: !loading;
                source: icon;
                colorize: colorize-icon ? theme.text : transparent;
                size: UAppTheme.icon-size-base;
                animate colorize { duration: UAppTheme.animation-duration; }
                states [
                    loading when root.loading: {
                        colorize: transparent;
                    }
                    disabled when !root.enabled: {
                        colorize: colorize-icon ? theme.text-disabled : transparent;
                    }
                    checked when root.checked: {
                        colorize: colorize-icon ? theme.text-checked : transparent;
                    }
                    active when root.pressed: {
                        colorize: colorize-icon ? theme.text-active : transparent;
                    }
                    hover when root.has-hover: {
                        colorize: colorize-icon ? theme.text-hover : transparent;
                    }
                ]
            }
        }
        VerticalLayout {
            alignment: center;
            text-obj := UText {
                color: theme.text;
                font-size: UAppTheme.font-size-base;
                animate color { duration: UAppTheme.animation-duration; }
				// Managing the text's states here as the states' order is different from the
				// component.
				states [
                    loading when root.loading: {
                        color: transparent;
                    }
                    disabled when !root.enabled: {
                        color: !root.loading ? theme.text-disabled : transparent;
                    }
                    checked when root.checked: {
                        color: !root.loading ? theme.text-checked : transparent;
                    }
                    active when root.pressed: {
                        color: !root.loading ? theme.text-active : transparent;
                    }
                    hover when root.has-hover: {
                        color: !root.loading ? theme.text-hover : transparent;
                    }
                ]
            }
        }

        if icon-placement == IconTextPlacement.end: VerticalLayout {
            alignment: center;
            icon-end := UIcon {
                visible: !loading;
                source: icon;
                colorize: colorize-icon ? theme.text : transparent;
                size: UAppTheme.icon-size-base;
                animate colorize { duration: UAppTheme.animation-duration; }
                states [
                    loading when root.loading: {
                        colorize: transparent;
                    }
                    disabled when !root.enabled: {
                        colorize: colorize-icon ? theme.text-disabled : transparent;
                    }
                    checked when root.checked: {
                        colorize: colorize-icon ? theme.text-checked : transparent;
                    }
                    active when root.pressed: {
                        colorize: colorize-icon ? theme.text-active : transparent;
                    }
                    hover when root.has-hover: {
                        colorize: colorize-icon ? theme.text-hover : transparent;
                    }
                ]
            }
        }
    }

    states [
        loading when root.loading: {
            mouse-cursor: wait;
            background: theme.bg-loading;
            border-color: self.has-tab-focus ? UAppTheme.focus-color : theme.border;
        }
        disabled when !root.enabled: {
            background: theme.bg-disabled;
            border-color: self.has-tab-focus ? UAppTheme.focus-color : theme.border-disabled;
        }
        checked when root.checked: {
            background: theme.bg-checked;
            border-color: self.has-tab-focus ? UAppTheme.focus-color : theme.border-checked;
        }
        active when root.pressed && !root.loading: {
            background: theme.bg-active;
            border-color: self.has-tab-focus ? UAppTheme.focus-color : theme.border-active;
        }
        hover when root.has-hover && !root.loading: {
            background: theme.bg-hover;
            border-color: self.has-tab-focus ? UAppTheme.focus-color : theme.border-hover;
        }
    ]
}
