import { UAppTheme } from "../app-theme.slint";
import { UProgressVariant } from "linear-progress.slint";


export component UCircleProgress inherits Path {
	// Accessability properties
	accessible-role: progress-indicator;
    accessible-value-minimum: 0;
    accessible-value-maximum: 100;
	// Regular properties
    in-out property <brush> progress-color;
    in-out property <UProgressVariant> variant: primary;
    in property <length> default-size: 10px;
    in-out property <percent> progress: indeterminate ? 30% : 0%;
    in-out property <bool> indeterminate: false;
    width: 40px;
    height: 40px;
    stroke: progress-color;
    stroke-width: default-size;
    stroke-line-cap: round;
    viewbox-width: self.width / 1px;
    viewbox-height: self.height / 1px;
    changed progress => {
        if indeterminate {
            progress = 30%;
        }
    }
    changed indeterminate => {
        if indeterminate {
            progress = 30%;
        }
    }

	// Inner properties used for rendering.
    private property <float> start-x: self.width / 2px;
    private property <float> start-y: self.height / 2px;
    private property <float> radius: self.width / 2px;
    private property <angle> offset: 115deg;
    MoveTo {
        x: start-x + radius * cos(0deg + offset);
        y: start-y + radius * sin(0deg + offset);
    }

    ArcTo {
        x: start-x + radius * cos(310deg * progress + offset);
        y: start-y + radius * sin(310deg * progress + offset);
        large-arc: progress > 0.6666666;
        radius-x: radius;
        radius-y: radius;
        sweep: true;
    }

    states [
        primary when variant == UProgressVariant.primary: {
            progress-color: UAppTheme.primary.base;
        }
        success when variant == UProgressVariant.success: {
            progress-color: UAppTheme.success.base;
        }
        warning when variant == UProgressVariant.warning: {
            progress-color: UAppTheme.warning.base;
        }
        danger when variant == UProgressVariant.danger: {
            progress-color: UAppTheme.danger.base;
        }
    ]
}
