import { UAppTheme } from "../app-theme.slint";
import { UIcon } from "icon.slint";
import { UText } from "text.slint";


export component UCode inherits Rectangle {
    in-out property <string> code;
    in-out property <bool> enable-clipboard: false;
    callback copied(code: string);
    background: UAppTheme.color-fill-secondary;
    border-color: UAppTheme.border;
    border-width: UAppTheme.border-width-base;
    border-radius: UAppTheme.radius-small;
    HorizontalLayout {
        alignment: start;
        padding: UAppTheme.padding-medium;
        UText {
            font-size: UAppTheme.font-size-small;
            text: code;
        }
    }

    if enable-clipboard: VerticalLayout {
        alignment: start;
        HorizontalLayout {
            alignment: end;
            padding: UAppTheme.padding-medium;
            Rectangle {
                states [
                    focus when clipboard-focus.has-focus: {
                        border-color: UAppTheme.focus-color;
                        border-width: UAppTheme.focus-border-width;
                    }
                ]
                UIcon {
                    colorize: UAppTheme.color-fill-plus;
                    source: @image-url("../assets/icons/clipboard.svg");
                    clipboard-touch := TouchArea {
                        clicked => {
                            root.copied(code);
                        }
                    }

                    clipboard-focus := FocusScope { }

                    states [
                        hover when clipboard-touch.has-hover: {
                            colorize: UAppTheme.color-fill;
                        }
                    ]
                }
            }
        }
    }
}
