import { UAppTheme } from "../app-theme.slint";
import { UIcon } from "icon.slint";
import { UText } from "text.slint";
import { ButtonInterface } from "button-interface.slint";


enum UCodeType {
	inline,
	block,
}


export component UCode inherits VerticalLayout {
    in-out property <UCodeType> type: block;
    in-out property <string> code;
    in-out property <bool> enable-clipboard: false;
    callback copied(code: string);
    private property <brush> bg-color: UAppTheme.color-fill-secondary;
    private property <brush> bd-color: UAppTheme.border;
    private property <length> bd-width: UAppTheme.border-width-base;
    private property <length> bd-radius: UAppTheme.radius-small;
    if type == UCodeType.inline: Rectangle {
        Rectangle {
            background: bg-color;
            border-color: bd-color;
            border-width: bd-width;
            border-radius: bd-radius;
            HorizontalLayout {
                alignment: start;
                padding: UAppTheme.padding-small;
                UText {
                    font-size: UAppTheme.font-size-small;
                    text: code;
                }
            }
        }
    }
    if type == UCodeType.block: Rectangle {
        background: bg-color;
        border-color: bd-color;
        border-width: bd-width;
        border-radius: bd-radius;
        HorizontalLayout {
            alignment: start;
            padding: UAppTheme.padding-medium;
            UText {
                font-size: UAppTheme.font-size-small;
                text: code;
            }
        }

        if enable-clipboard: VerticalLayout {
            alignment: start;
            HorizontalLayout {
                alignment: end;
                padding: UAppTheme.padding-medium;
                Rectangle {
                    states [
                        focus when btn-interface.has-tab-focus: {
                            border-color: UAppTheme.focus-color;
                            border-width: UAppTheme.focus-border-width;
                        }
                    ]
                    UIcon {
                        colorize: UAppTheme.color-fill-plus;
                        source: @image-url("../assets/icons/clipboard.svg");
                        btn-interface := ButtonInterface {
                            clicked => {
                                root.copied(code);
                            }
                        }

                        states [
                            hover when btn-interface.has-hover: {
                                colorize: UAppTheme.color-fill;
                            }
                        ]
                    }
                }
            }
        }
    }
}
