import { UAppTheme } from "../app-theme.slint";


export component UDivider inherits Rectangle {
    in property <Orientation> orientation: horizontal;
    in-out property <length> thickness: UAppTheme.border-width-base;
    background: UAppTheme.separator;
    // Using init so that the divider takes all the space by default even though
    // we shouldn't according to the official documentation.
    init => {
        if orientation == Orientation.horizontal {
            root.height = root.thickness;
        } else {
            root.width = root.thickness;
        }
    }
}
