import { UButton, UButtonVariant, UButtonThemeColor } from "button.slint";
import { IconTextPlacement } from "../structs/icon-placement.slint";


export component UFloatingButton inherits VerticalLayout {
	// Layout placement
	in-out property <LayoutAlignment> vertical-alignment: start;
    in-out property <LayoutAlignment> horizontal-alignment: start;
    in-out property <length> layout-padding-top: 0px;
    in-out property <length> layout-padding-bottom: 0px;
    in-out property <length> layout-padding-left: 0px;
    in-out property <length> layout-padding-right: 0px;
	// Button's properties and callbacks
	in-out property <UButtonVariant> variant <=> btn.variant;
    in-out property <string> text <=> btn.text;
    in-out property <bool> enabled <=> btn.enabled;
    out property <bool> has-focus <=> btn.has-focus;
    out property <bool> has-hover <=> btn.has-hover;
    out property <bool> pressed <=> btn.pressed;
    in-out property <bool> loading <=> btn.loading;
    in-out property <image> icon <=> btn.icon;
    in-out property <IconTextPlacement> icon-placement <=> btn.icon-placement;
    callback clicked <=> btn.clicked;
	// Theming properties
	in-out property <length> t-border-width <=> btn.t-border-width;
    in-out property <length> t-border-radius <=> btn.t-border-radius;
    in-out property <length> t-content-spacing <=> btn.t-content-spacing;
    in-out property <length> t-padding-vertical <=> btn.t-padding-vertical;
    in-out property <length> t-padding-horizontal <=> btn.t-padding-horizontal;
    in-out property <length> t-font-size <=> btn.t-font-size;
    in-out property <length> t-icon-size <=> btn.t-icon-size;
    in-out property <UButtonThemeColor> t-background <=> btn.t-background;
    in-out property <UButtonThemeColor> t-background-hover <=> btn.t-background-hover;
    in-out property <UButtonThemeColor> t-background-active <=> btn.t-background-active;
    in-out property <UButtonThemeColor> t-background-checked <=> btn.t-background-checked;
    in-out property <UButtonThemeColor> t-background-disabled <=> btn.t-background-disabled;
    in-out property <UButtonThemeColor> t-text-color <=> btn.t-text-color;
    in-out property <UButtonThemeColor> t-text-color-hover <=> btn.t-text-color-hover;
    in-out property <UButtonThemeColor> t-text-color-active <=> btn.t-text-color-active;
    in-out property <UButtonThemeColor> t-text-color-checked <=> btn.t-text-color-checked;
    in-out property <UButtonThemeColor> t-text-color-disabled <=> btn.t-text-color-disabled;
    in-out property <UButtonThemeColor> t-border <=> btn.t-border;
    in-out property <UButtonThemeColor> t-border-hover <=> btn.t-border-hover;
    in-out property <UButtonThemeColor> t-border-active <=> btn.t-border-active;
    in-out property <UButtonThemeColor> t-border-checked <=> btn.t-border-checked;
    in-out property <UButtonThemeColor> t-border-disabled <=> btn.t-border-disabled;
	// TouchArea callbacks from UButton.
    callback double-clicked <=> btn.double-clicked;
    callback moved <=> btn.moved;
    callback pointer-event <=> btn.pointer-event;
    callback scroll-event <=> btn.scroll-event;
	// FocusScope callbacks from UButton.
	callback key-pressed <=> btn.key-pressed;
    callback key-released <=> btn.key-released;
    callback focus-changed-event <=> btn.focus-changed-event;
    alignment: vertical-alignment;
    HorizontalLayout {
        alignment: horizontal-alignment;
        padding-top: layout-padding-top;
        padding-bottom: layout-padding-bottom;
        padding-left: layout-padding-left;
        padding-right: layout-padding-right;
        btn := UButton { }
    }
}
