import { UAppTheme } from "../app-theme.slint";

import {
    UButtonVariant,
    UButtonTheme,
    UButtonThemes,
} from "common/button.slint";

import { ButtonInterface } from "button-interface.slint";

import { UIcon } from "icon.slint";
import { USpinner } from "spinner.slint";


export component UIconButton inherits ButtonInterface {
	// Accessibility properties
	accessible-role: button;
    accessible-action-default => {
        self.clicked()
    }	
	// Regular properties
    in-out property <UButtonVariant> variant: default;
    private property <UButtonTheme> theme: {
        if variant == primary {
            return danger ? UButtonThemes.primary-danger : UButtonThemes.primary;
        }
        if variant == filled {
            return danger ? UButtonThemes.filled-danger : UButtonThemes.filled;
        }
        if variant == UButtonVariant.text {
            return danger ? UButtonThemes.text-danger : UButtonThemes.text;
        }
        if variant == UButtonVariant.text-stripped {
            return UButtonThemes.text-stripped;
        }
        return danger ? UButtonThemes.default-danger : UButtonThemes.default;
    };
    in-out property <bool> danger: false;
    in-out property <bool> loading: false;
    in-out property <bool> checked: false;
    in-out property <image> icon;
    in-out property <bool> colorize-icon: true;
	// Using a custom size to have the same height as the Button.
	// When using 16px as the icon's size, there will be a difference
	// of 1px between the height of the IconButton and the Button.
	// This is due to the text in the Button that increases the height 
	// to 27px (26px for an icon button).
	private property <length> icon-size: 17px;
    changed enabled => {
        if root.loading && root.enabled {
            root.enabled = false;
        }
    }
    changed loading => {
        root.enabled = !root.loading;
    }
    init => {
        if root.loading {
            root.enabled = false;
        }
    }
    background: theme.bg;
    border-radius: UAppTheme.radius-circle;
    border-width: self.has-tab-focus ? UAppTheme.focus-border-width : theme.border-width;
    border-color: self.has-tab-focus ? UAppTheme.focus-color : theme.border;
    VerticalLayout {
        alignment: center;
        cross-axis-alignment: center;
        padding-top: UAppTheme.padding-vertical;
        padding-bottom: UAppTheme.padding-vertical;
        padding-left: UAppTheme.padding-vertical;
        padding-right: UAppTheme.padding-vertical;
        if !loading: UIcon {
            size: icon-size;
            source: icon;
            colorize: colorize-icon ? theme.text : transparent;
            animate colorize { duration: UAppTheme.animation-duration; }
            states [
                loading when root.loading: {
                    colorize: transparent;
                }
                disabled when !root.enabled: {
                    colorize: colorize-icon ? theme.text-disabled : transparent;
                }
                checked when root.checked: {
                    colorize: colorize-icon ? theme.text-checked : transparent;
                }
                active when root.pressed: {
                    colorize: colorize-icon ? theme.text-active : transparent;
                }
                hover when root.has-hover: {
                    colorize: colorize-icon ? theme.text-hover : transparent;
                }
            ]
        }
        if loading: USpinner {
            size: icon-size;
            colorize: theme.text;
        }
    }

    states [
        loading when root.loading: {
            mouse-cursor: wait;
            background: theme.bg-loading;
            border-color: self.has-tab-focus ? UAppTheme.focus-color : theme.border;
        }
        disabled when !root.enabled: {
            background: theme.bg-disabled;
            border-color: self.has-tab-focus ? UAppTheme.focus-color : theme.border-disabled;
        }
        checked when root.checked: {
            background: theme.bg-checked;
            border-color: self.has-tab-focus ? UAppTheme.focus-color : theme.border-checked;
        }
        active when root.pressed && !root.loading: {
            background: theme.bg-active;
            border-color: self.has-tab-focus ? UAppTheme.focus-color : theme.border-active;
        }
        hover when root.has-hover && !root.loading: {
            background: theme.bg-hover;
            border-color: self.has-tab-focus ? UAppTheme.focus-color : theme.border-hover;
        }
    ]
}
