import { UAppTheme } from "../app-theme.slint";

import { UIcon } from "icon.slint";
import { UText } from "text.slint";

import { UInputTheme, UInputThemes } from "../widget-themes/input.slint";


export component UInputNumber inherits Rectangle {
	// Accessability properties
	accessible-role: spinbox;
    accessible-read-only: input.read-only;
    accessible-value: self.value;
    accessible-value-step: self.step;
    accessible-action-default => {
        self.accepted()
    }
    accessible-action-set-value(value) => {
        input.text = value.to-float();
    }
    accessible-action-decrement => {
        btn-decrease.clicked();
    }
    accessible-action-increment => {
        btn-increase.clicked();
    }
	// Regular properties
    in-out property <UInputTheme> theme: UInputThemes.default;
    in-out property <float> value: 0;
    in-out property <bool> enabled <=> input.enabled;
    in-out property <float> step: 1;
    in-out property <bool> number: false;
    in-out property <bool> error: false;
    in-out property <bool> enable-min-max: false;
    in-out property <float> min-value: -100;
    in-out property <float> max-value: 100;
    init => {
        if self.enable-min-max {
            self.accessible-value-minimum = self.min-value;
            self.accessible-value-maximum = self.max-value;
        }
    }
    border-width: theme.border-width;
    border-radius: theme.border-radius;
    border-color: theme.border-color;
    background: theme.background;
    clip: true;
    HorizontalLayout {
        width: root.width;
        VerticalLayout {
            alignment: center;
            padding-left: UAppTheme.padding-small;
            Rectangle {
                height: 100%;
                width: theme.icon-size + theme.padding-horizontal;
                UIcon {
                    size: theme.icon-size;
                    colorize: theme.icon-color;
                    source: @image-url("../assets/icons/minus.svg");
                }

                btn-decrease := TouchArea {
                    accessible-role: button;
                    accessible-label: @tr("Decrease number input value.");
                    mouse-cursor: MouseCursor.pointer;
                    clicked => {
                        if !root.enabled {
                            return;
                        }
                        if root.enable-min-max && root.value < root.min-value {
                            root.value = root.min-value;
                        } else {
                            root.value = input.text.to-float() - root.step;
                        }
                        input.text = root.value;
                        input.focus();
                    }
                }
            }
        }

        HorizontalLayout {
            padding-left: theme.padding-horizontal;
            padding-right: theme.padding-horizontal;
            Rectangle {
                height: theme.font-size + theme.padding-vertical * 3;
                clip: true;
                input := TextInput {
                    property <length> h-padding: theme.padding-horizontal * 2;
                    property <length> computed_x;
                    text: root.value;
                    width: max(parent.width, self.preferred-width);
                    x: min(computed_x, 0px);
                    input-type: root.number ? InputType.number : InputType.decimal;
                    read-only: !root.enabled;
                    font-size: theme.font-size;
                    font-weight: theme.font-weight;
                    color: theme.text-color;
                    vertical-alignment: center;
                    horizontal-alignment: center;
                    single-line: true;
                    wrap: no-wrap;
					// Shamelessly taken from Surrealisme UI
					// Source : https://github.com/Surrealism-All/SurrealismUI/blob/main/src/input/input.slint
					cursor-position-changed(cpos) => {
                        if cpos.x + self.computed_x < self.h-padding {
                            self.computed_x = - cpos.x + self.h-padding;
                        } else if cpos.x + self.computed_x > parent.width - 1px {
                            self.computed_x = parent.width - cpos.x - 1px;
                        }
                    }
                    edited => {
                        root.value = self.text.to-float();
                        if root.enable-min-max {
                            if root.value < root.min-value {
                                root.value = root.min-value;
                            } else if root.value > root.max-value {
                                root.value = root.max-value;
                            }
                        }
                        self.text = root.value;
                    }
                    key-pressed(event) => {
                        if event.text == Key.UpArrow {
                            btn-increase.clicked();
                            return accept;
                        } else if event.text == Key.DownArrow {
                            btn-decrease.clicked();
                            return accept;
                        }
                        reject
                    }
                }
            }
        }

        VerticalLayout {
            alignment: center;
            padding-left: UAppTheme.padding-small;
            Rectangle {
                height: 100%;
                width: theme.icon-size + theme.padding-horizontal;
                UIcon {
                    size: theme.icon-size;
                    colorize: theme.icon-color;
                    source: @image-url("../assets/icons/plus.svg");
                }

                btn-increase := TouchArea {
                    accessible-role: button;
                    accessible-label: @tr("Increase number input value.");
                    mouse-cursor: MouseCursor.pointer;
                    clicked => {
                        if !root.enabled {
                            return;
                        }
                        if root.enable-min-max && root.value > root.max-value {
                            root.value = root.max-value;
                        } else {
                            root.value = input.text.to-float() + root.step;
                        }
                        input.text = root.value;
                        input.focus();
                    }
                }
            }
        }
    }

    states [
        disabled when !input.enabled: {
            background: theme.background-disabled;
            border-color: theme.border-color-disabled;
            input.color: theme.text-color-disabled;
        }
        error when error: {
            background: theme.background-error;
            border-color: theme.border-color-error;
        }
        active when input.has-focus: {
            background: theme.background-active;
            border-color: theme.border-color-active;
        }
    ]

	// Link the functions and callback of TextInput to child.
	public function set-selection-offsets(start: int, end: int) {
        input.set-selection-offsets(start, end);
    }
    public function select-all() {
        input.select-all();
    }
    public function clear-selection() {
        input.clear-selection();
    }
    public function copy() {
        input.copy();
    }
    public function cut() {
        input.cut();
    }
    public function paste() {
        input.paste();
    }
    callback accepted <=> input.accepted;
    callback cursor-position-changed <=> input.cursor-position-changed;
    callback edited <=> input.edited;
    callback key-pressed <=> input.key-pressed;
    callback key-released <=> input.key-released;
}
