import { UAppTheme } from "../app-theme.slint";
import { ProgressDirection } from "common/enums.slint";


export component ULineProgress inherits Rectangle {
	// Accessibility properties
	accessible-role: progress-indicator;
    accessible-value: indeterminate ? 0 : progress;
    accessible-value-minimum: 0;
    accessible-value-maximum: 100;
    accessible-orientation: orientation;
    // Regular properties
    in-out property <brush> progress-color: UAppTheme.primary.base;
    in property <length> default-size: 10px;
    in property <length> default-radius: UAppTheme.radius-round;
    in property <Orientation> orientation: horizontal;
    in property <ProgressDirection> direction: start;
    in-out property <percent> progress;
    in-out property <bool> indeterminate: false;
    callback reset-x();
    background: UAppTheme.color-fill-secondary;
    border-radius: default-radius;
    clip: true;
    height: default-size;
    width: default-size;
    if orientation == Orientation.horizontal: Rectangle {
        private property <length> x-pos: 0;
        x: indeterminate ? x-pos : direction == end ? root.width - self.width : 0;
        background: progress-color;
        border-radius: default-radius;
        width: indeterminate ? 30% : clamp(progress, 0%, 100%);
        animate width {
            easing: ease-in-out;
            duration: 350ms;
        }
        Timer {
            running: indeterminate;
            interval: 5ms;
            triggered => {
                if direction == ProgressDirection.start {
                    parent.x-pos += 1px;
                    if parent.x-pos > root.width {
                        parent.x-pos = -parent.width;
                    }
                } else {
                    parent.x-pos -= 1px;
                    if parent.x-pos < -parent.width {
                        parent.x-pos = root.width - parent.width;
                    }
                }
            }
        }
    }
    if orientation == Orientation.vertical: Rectangle {
        private property <length> y-pos: 0;
        y: indeterminate ? y-pos : direction == end ? root.height - self.height : 0;
        background: progress-color;
        border-radius: default-radius;
        height: indeterminate ? 30% : clamp(progress, 0%, 100%);
        animate height {
            easing: ease-in-out;
            duration: 350ms;
        }
        Timer {
            running: indeterminate;
            interval: 10ms;
            triggered => {
                if direction == ProgressDirection.start {
                    parent.y-pos += 1px;
                    if parent.y-pos > root.height {
                        parent.y-pos = -parent.height;
                    }
                } else {
                    parent.y-pos -= 1px;
                    if parent.y-pos < -parent.height {
                        parent.y-pos = root.height;
                    }
                }
            }
        }
    }
}
