import { UAppTheme } from "../app-theme.slint";

import { ULinkTheme, ULinkThemes } from "../widget-themes/link.slint";
import { ButtonInterface } from "../utils/button-interface.slint";
import { UText } from "text.slint";


export component ULink inherits ButtonInterface {
	// Accessability properties
	accessible-role: button;
    accessible-label: self.text;
    accessible-description: @tr("A link that opens an URL or window when clicked");
    accessible-action-default => {
        self.clicked()
    }
	// Regular properties
	in-out property <ULinkTheme> theme: ULinkThemes.primary;
    in-out property <string> text <=> link-text.text;
	// Using this horizontal layout to limit the width of the underline to the text's width.
    HorizontalLayout {
        alignment: start;
        VerticalLayout {
            alignment: center;
            spacing: theme.underline-spacing;
            link-text := UText {
                color: theme.text-color;
                font-size: theme.font-size;
            }

            underline := Rectangle {
                height: theme.underline-thickness;
                background: theme.text-color;
            }
        }
    }

    states [
        focus when root.has-focus: {
            border-width: UAppTheme.focus-border-width;
            border-color: UAppTheme.focus-color;
        }
        hover when root.has-hover: {
            underline.visible: false;
        }
    ]
}
