import { UAppTheme } from "../app-theme.slint";

import { ButtonInterface } from "button-interface.slint";
import { UText } from "text.slint";
import { UIcon } from "icon.slint";
import { IconTextPlacement } from "../structs/data-structs.slint";


export component ULink inherits Rectangle {
	// Regular properties
	in-out property <string> text <=> link-text.text;
    in-out property <IconTextPlacement> icon-placement: hidden;
    in-out property <bool> disable-underline;
    callback clicked();
    touch := ButtonInterface {
		// Accessability properties
		accessible-role: button;
        accessible-label: text;
        accessible-description: @tr("A link that opens an URL or window when clicked");
        accessible-action-default => {
            root.clicked()
        }
        clicked => {
            root.clicked();
        }
		// Using this horizontal layout to limit the width of the underline to the text's width.
		HorizontalLayout {
            alignment: start;
            spacing: UAppTheme.spacing-base;
            if icon-placement == IconTextPlacement.start: VerticalLayout {
                alignment: center;
                padding-top: -1px;
                padding-bottom: 1px;
                UIcon {
                    size: UAppTheme.font-size-base;
                    source: @image-url("../assets/icons/external-link.svg");
                    colorize: UAppTheme.primary.base;
                    states [
                        active when touch.pressed: {
                            colorize: UAppTheme.primary.active;
                        }
                        hover when touch.has-hover: {
                            colorize: UAppTheme.primary.hover;
                        }
                    ]
                }
            }
            VerticalLayout {
                alignment: start;
                spacing: -1px;
                link-text := UText {
                    color: UAppTheme.primary.base;
                    font-size: UAppTheme.font-size-base;
                }

                if !disable-underline: Rectangle {
                    height: UAppTheme.border-width-base;
                    background: UAppTheme.primary.base;
                    states [
                        active when touch.pressed: {
                            visible: false;
                        }
                        hover when touch.has-hover: {
                            visible: false;
                        }
                    ]
                }
            }

            if icon-placement == IconTextPlacement.end: VerticalLayout {
                alignment: center;
                padding-top: -1px;
                padding-bottom: 1px;
                UIcon {
                    size: UAppTheme.font-size-base;
                    source: @image-url("../assets/icons/external-link.svg");
                    colorize: UAppTheme.primary.base;
                    states [
                        active when touch.pressed: {
                            colorize: UAppTheme.primary.active;
                        }
                        hover when touch.has-hover: {
                            colorize: UAppTheme.primary.hover;
                        }
                    ]
                }
            }
        }

        states [
            focus when self.has-tab-focus: {
                border-width: UAppTheme.focus-border-width;
                border-color: UAppTheme.focus-color;
            }
            active when self.pressed: {
                link-text.color: UAppTheme.primary.active;
            }
            hover when self.has-hover: {
                link-text.color: UAppTheme.primary.hover;
            }
        ]
    }
}
