import { UAppTheme } from "../app-theme.slint";

import { ButtonInterface } from "button-interface.slint";
import { UText } from "text.slint";


export component ULink inherits Rectangle {
	// Regular properties
	in-out property <string> text <=> link-text.text;
    in-out property <TextWrap> wrap: no-wrap;
    callback clicked();
    ButtonInterface {
		// Accessability properties
		accessible-role: button;
        accessible-label: text;
        accessible-description: @tr("A link that opens an URL or window when clicked");
        accessible-action-default => {
            root.clicked()
        }
        clicked => {
            root.clicked();
        }
		// Using this horizontal layout to limit the width of the underline to the text's width.
		HorizontalLayout {
            alignment: start;
            VerticalLayout {
                alignment: center;
                spacing: -1px;
                link-text := UText {
                    color: UAppTheme.primary.base;
                    font-size: UAppTheme.font-size-base;
                }

                underline := Rectangle {
                    height: UAppTheme.border-width-base;
                    background: UAppTheme.primary.base;
                }
            }
        }

        states [
            focus when self.has-tab-focus: {
                border-width: UAppTheme.focus-border-width;
                border-color: UAppTheme.focus-color;
            }
            active when self.pressed: {
                link-text.color: UAppTheme.primary.active;
                underline.visible: false;
            }
            hover when self.has-hover: {
                link-text.color: UAppTheme.primary.hover;
                underline.visible: false;
            }
        ]
    }
}
