import { UAppTheme } from "../app-theme.slint";

import { UCard } from "card.slint";
import { UDivider } from "divider.slint";
import { UButton } from "button.slint";
import { UIconButton } from "icon-button.slint";
import { UTitle } from "title.slint";

import { UTitleThemes } from "../widget-themes/title.slint";
import { UModalTheme, UModalThemes } from "../widget-themes/modal.slint";


export component UModal {
    in-out property <UModalTheme> theme: UModalThemes.default;
    in-out property <string> title;
    in-out property <string> accept-btn-text: @tr("Done");
    in-out property <string> cancel-btn-text: @tr("Cancel");
    in-out property <bool> accept-btn-toggle: true;
    in-out property <bool> cancel-btn-toggle: true;
    in-out property <bool> close-on-click-outside: false;
    in-out property <bool> close-on-accept: true;
    in-out property <bool> close-on-cancel: true;
    in-out property <bool> accept-btn-enabled: true;
    in-out property <bool> cancel-btn-enabled: true;
    in-out property <length> modal-min-width: 300px * UAppTheme.scale-factor;
    in-out property <length> modal-min-height;
    in-out property <length> modal-max-width: 600px * UAppTheme.scale-factor;
    in-out property <length> modal-max-height: 600px * UAppTheme.scale-factor;
    callback showed();
    callback closed();
    // Both callbacks are linked to the Cancel/No and Accept/Done/Ok buttons.
	callback accepted();
    callback rejected();
    public function show() {
        self.visible = true;
        rect-background-focus.focus();
        self.showed();
    }
    public function close() {
        self.visible = false;
        self.closed();
    }
    visible: false;
    width: 100%;
    height: 100%;
    Rectangle {
        width: 100%;
        height: 100%;
        background: theme.blurred-background-color;
        touch-background := TouchArea {
            clicked => {
                if root.close-on-click-outside {
                    root.close();
                }
            }
        }

		// Used to skip focus directly to the modal.
		// This avoid having to focus all the elements in the window before getting to the modal.
		rect-background-focus := FocusScope { }

        accessible-role: button;
        accessible-label: @tr("Background panel for modal.");
        accessible-description: @tr("Close the modal if is is enabled.");
        accessible-enabled: close-on-click-outside;
        accessible-action-default => {
            touch-background.clicked();
        }
    }

    VerticalLayout {
        alignment: center;
        HorizontalLayout {
            alignment: center;
            modal-card := UCard {
                min-width: modal-min-width;
                min-height: modal-min-height;
                max-width: modal-max-width;
                max-height: modal-max-height;

				
				// Used to prevent clicks made in the modal to count as clicks made in the background.
                TouchArea { }

                VerticalLayout {
                    HorizontalLayout {
                        padding-top: theme.title-vertical-padding;
                        padding-bottom: theme.title-vertical-padding;
                        padding-left: theme.title-horizontal-padding;
                        padding-right: theme.title-horizontal-padding;
                        VerticalLayout {
                            alignment: center;
                            UTitle {
                                theme: theme.title-theme;
                                horizontal-stretch: 1;
                                text: title;
                                wrap: no-wrap;
                                overflow: elide;
                                accessible-label: @tr("Title for the modal");
                            }
                        }

                        VerticalLayout {
                            alignment: center;
                            UIconButton {
                                variant: theme.close-button-variant;
                                icon: @image-url("../assets/icons/x.svg");
                                clicked => {
                                    root.close();
                                }
                                accessible-label: @tr("Close button for modal.");
                            }
                        }
                    }

                    UDivider { }

                    VerticalLayout {
                        vertical-stretch: 2;
                        padding-top: theme.content-vertical-padding;
                        padding-bottom: theme.content-vertical-padding;
                        padding-left: theme.content-horizontal-padding;
                        padding-right: theme.content-horizontal-padding;
                        @children
                    }

                    if cancel-btn-enabled || accept-btn-enabled: VerticalLayout {
                        alignment: start;
                        vertical-stretch: 0;
                        UDivider { }

                        HorizontalLayout {
                            alignment: end;
                            padding-top: theme.buttons-vertical-padding;
                            padding-bottom: theme.buttons-vertical-padding;
                            padding-left: theme.buttons-horizontal-padding;
                            padding-right: theme.buttons-horizontal-padding;
                            spacing: theme.buttons-spacing;
                            if cancel-btn-toggle: UButton {
                                variant: theme.cancel-button-variant;
                                text: cancel-btn-text;
                                enabled: cancel-btn-enabled;
                                clicked => {
                                    self.loading = true;
                                    root.rejected();
                                    self.loading = false;
                                    if close-on-cancel {
                                        root.close();
                                    }
                                }
                                accessible-label: @tr("Cancel or refuse button for modal.");
                            }
                            if accept-btn-toggle: UButton {
                                variant: theme.accept-button-variant;
                                text: accept-btn-text;
                                enabled: accept-btn-enabled;
                                clicked => {
                                    self.loading = true;
                                    root.accepted();
                                    self.loading = false;
                                    if close-on-accept {
                                        root.close();
                                    }
                                }
                                accessible-label: @tr("Accept or done button for modal.");
                            }
                        }
                    }
                }
            }
        }
    }
}
