import { UAppTheme } from "../app-theme.slint";
import { ButtonInterface } from "button-interface.slint";

import { UIcon } from "icon.slint";
import { UText } from "text.slint";
import { UIconButton, UIconButtonVariant } from "icon-button/icon-button.slint";


export enum UNotificationVariant {
    info,
    success,
    warning,
    danger,
}

export component UNotification inherits Rectangle {
    in-out property <UNotificationVariant> variant: info;
    in-out property <string> title;
    in-out property <string> message;
    in-out property <image> icon;
    in-out property <brush> icon-color;
    callback close <=> close-button.clicked;
    callback clicked <=> btn-interface.clicked;
    width: 300px;
    background: UAppTheme.bg-elevated;
    border-radius: clamp(UAppTheme.radius-base, 0, 4px);
    border-width: btn-interface.has-tab-focus ? UAppTheme.focus-border-width : 0;
    border-color: btn-interface.has-tab-focus ? UAppTheme.focus-color : transparent;
    drop-shadow-blur: UAppTheme.shadow-blur;
    drop-shadow-color: UAppTheme.shadow-color;
    drop-shadow-offset-y: UAppTheme.shadow-y-offset;
    btn-interface := ButtonInterface {
        HorizontalLayout {
            padding: UAppTheme.padding-base;
            GridLayout {
                padding-top: UAppTheme.padding-base;
                padding-bottom: UAppTheme.padding-base;
                padding-left: UAppTheme.padding-medium;
                padding-right: UAppTheme.padding-medium;
                spacing-horizontal: UAppTheme.spacing-medium;
                Row {
                    VerticalLayout {
                        alignment: center;
                        UIcon {
                            source: icon;
                            colorize: icon-color;
                            size: UAppTheme.font-size-big;
                            accessible-role: none;
                        }
                    }

                    VerticalLayout {
                        alignment: center;
                        UText {
                            text: title;
                            wrap: no-wrap;
                            overflow: elide;
                            font-size: UAppTheme.font-size-medium;
                        }
                    }

                    close-button := UIconButton {
                        variant: text;
                        icon: @image-url("../assets/icons/x.svg");
                        accessible-label: @tr("Close notification");
                        accessible-action-default => {
                            self.clicked();
                        }
                    }
                }

                Row {
                    if message != "": UText {
                        col: 1;
                        overflow: clip;
                        wrap: word-wrap;
                        text: root.message;
                    }
                }
            }
        }
    }

    states [
        info when variant == UNotificationVariant.info: {
            icon: @image-url("../assets/icons/circle-check.svg");
            icon-color: UAppTheme.primary.base;
        }
        success when variant == UNotificationVariant.success: {
            icon: @image-url("../assets/icons/circle-check.svg");
            icon-color: UAppTheme.success.base;
        }
        warning when variant == UNotificationVariant.warning: {
            icon: @image-url("../assets/icons/circle-check.svg");
            icon-color: UAppTheme.warning.base;
        }
        danger when variant == UNotificationVariant.danger: {
            icon: @image-url("../assets/icons/circle-check.svg");
            icon-color: UAppTheme.danger.base;
        }
    ]
}
