import { UAppTheme } from "../app-theme.slint";
import { UCard } from "card.slint";


export component UPopover inherits PopupWindow {
    in-out property <length> default-border-radius: UAppTheme.radius-base > 4px ? 4px : UAppTheme.radius-base;
    min-height: 10px * UAppTheme.scale-factor;
    UCard {
        width: 100%;
        height: 100%;
        border-radius: root.default-border-radius;
        @children
    }
}
