import { UAppTheme } from "../app-theme.slint";
import { ButtonInterface } from "button-interface.slint";
import { UText } from "text.slint";


component URadioOption inherits ButtonInterface {
	// Accessability properties
	accessible-role: checkbox;
    accessible-label: self.option;
    accessible-item-selectable: true;
    accessible-item-selected: self.option == self.selected-value;
    accessible-action-default => {
        self.clicked();
    }
	// Regular properties
    in-out property <string> option;
    in-out property <string> selected-value;
    callback selected(value: string);
    clicked => {
        self.selected-value = self.option;
        selected(self.option);
    }
    changed selected-value => {
        if selected-value != self.option {
        }
    }
    HorizontalLayout {
        alignment: start;
        spacing: UAppTheme.spacing-base;
        VerticalLayout {
            alignment: center;
            Rectangle {
                width: UAppTheme.font-size-base;
                height: UAppTheme.font-size-base;
                background: UAppTheme.bg-elevated;
                border-width: UAppTheme.border-width-base;
                border-radius: UAppTheme.radius-circle;
                border-color: UAppTheme.border;
                animate background, border-color {
                    easing: ease;
                    duration: 200ms;
                }
                HorizontalLayout {
                    alignment: center;
                    VerticalLayout {
                        alignment: center;
                        Rectangle {
                            opacity: root.selected-value == root.option ? 1 : 0;
                            width: UAppTheme.font-size-base / 3;
                            height: UAppTheme.font-size-base / 3;
                            background: white;
                            border-radius: UAppTheme.radius-circle;
                            animate opacity { duration: 200ms; }
                            states [
                                disabled when !root.enabled: {
                                    background: UAppTheme.color-fill-plus;
                                }
                            ]
                        }
                    }
                }

                states [
                    disabled-unselected when !root.enabled && root.selected-value != root.option: {
                        border-color: UAppTheme.border;
                        background: UAppTheme.color-fill-tertiary;
                    }
                    disabled-selected when !root.enabled && root.selected-value == root.option: {
                        border-color: UAppTheme.border;
                        background: UAppTheme.primary.disabled;
                    }
                    focused-hover-selected when root.has-focus && root.selected-value == root.option && root.has-hover: {
                        border-color: UAppTheme.focus-color;
                        border-width: UAppTheme.focus-border-width;
                        background: UAppTheme.primary.hover;
                    }
                    focused-selected when root.has-focus && root.selected-value == root.option: {
                        border-color: UAppTheme.focus-color;
                        border-width: UAppTheme.focus-border-width;
                        background: UAppTheme.primary.base;
                    }
                    focused when root.has-focus: {
                        border-color: UAppTheme.focus-color;
                        border-width: UAppTheme.focus-border-width;
                    }
                    hover-unselected when root.has-hover && root.selected-value != root.option: {
                        border-color: UAppTheme.primary.hover;
                    }
                    hover-selected when root.has-hover && root.selected-value == root.option: {
                        border-color: UAppTheme.primary.hover;
                        background: UAppTheme.primary.hover;
                    }
                    selected when root.selected-value == root.option: {
                        border-color: UAppTheme.primary.base;
                        background: UAppTheme.primary.base;
                    }
                ]
            }
        }

        VerticalLayout {
            alignment: center;
            UText {
                text: root.option;
                color: UAppTheme.text;
                font-size: UAppTheme.font-size-base;
                states [
                    disabled when !root.enabled: {
                        color: UAppTheme.text-disabled;
                    }
                ]
            }
        }
    }
}

export component URadio {
    accessible-role: groupbox;
    accessible-item-count: self.options.length;
	// Regular properties
	in-out property <bool> enabled: true;
    in-out property <[string]> options;
    in-out property <string> selected-value;
    in-out property <Orientation> orientation: vertical;
    callback selected(value: string);
    VerticalLayout {
        if orientation == Orientation.vertical: VerticalLayout {
            alignment: start;
            spacing: UAppTheme.spacing-base;
            for option in root.options: URadioOption {
                enabled <=> root.enabled;
                option: option;
                selected-value <=> root.selected-value;
                selected(value) => {
                    root.selected(value);
                }
            }
        }
        if orientation == Orientation.horizontal: HorizontalLayout {
            alignment: start;
            spacing: UAppTheme.spacing-base;
            for option in root.options: URadioOption {
                enabled <=> root.enabled;
                option: option;
                selected-value <=> root.selected-value;
                selected(value) => {
                    root.selected(value);
                }
            }
        }
    }
}
