import { Button } from "std-widgets.slint";
import { UAppTheme } from "../../sleek-ui/app-theme.slint";


// TODO Manage clicks in the scrollbar
// 		Click on handles -> 1% to 5% scroll (to test) (if handles are used)
//		Click in scrollbar space -> 10% to 20% scroll (to test)
//		Drag scrollbar
//		Accessability with keyboard management
export component UScrollview {
    in-out property <bool> interactive: false;
    private property <bool> scrollbar-visible-y: flickable.viewport-height > flickable.height;
    private property <bool> scrollbar-visible-x: flickable.viewport-width > flickable.width;
    height: 100%;
    width: 100%;
    HorizontalLayout {
        VerticalLayout {
            horizontal-stretch: 2;
            vertical-stretch: 2;
            flickable := Flickable {
                interactive: root.interactive;
                @children
            }
        }

        Rectangle {
            horizontal-stretch: 0;
            height: 100%;
            width: 10px * UAppTheme.scale-factor;

			// TODO Define handle minimum height.
			// TODO Handle shrinking when reducing window height to its maximum.
			//		Handle should keep the same height after passing the min-handle-pct threshold.
			Rectangle {
                private property <float> min-handle-pct: 0.05;
                private property <float> handle-pct: flickable.height / flickable.viewport-height;
                visible: scrollbar-visible-y;
                background: UAppTheme.color-fill;
                height: handle-pct > min-handle-pct ? flickable.height * handle-pct : flickable.height * min-handle-pct;
                width: parent.width;
                border-radius: UAppTheme.radius-circle;
            }
        }
    }

    Button {
        text: "debug";
        clicked => {
            debug("size");
            debug(flickable.height);
            debug(flickable.width);
            debug("viewport");
            debug(flickable.viewport-height);
            debug(flickable.viewport-width);
            debug("position");
            debug(flickable.viewport-x);
            debug(flickable.viewport-y);
            debug("scrollbar visibility");
            debug(root.scrollbar-visible-y);
            debug(root.scrollbar-visible-x);
            debug("\n\n\n");
        }
    }
}
