import { UAppTheme } from "../../sleek-ui/app-theme.slint";


component Scrollbar inherits Rectangle {
    in-out property <Orientation> orientation: vertical;
    in-out property <length> value;
    in-out property <length> max-scroll-pos;
    in property <length> handle-size;
    out property <bool> pressed <=> touch.pressed;
    private property <length> available-space: (orientation == Orientation.vertical ? self.height : self.width) - handle-size;
    private property <float> min-handle-pct: 0.05;
    width: orientation == Orientation.vertical ? 8px : 0;
    height: orientation == Orientation.horizontal ? 8px : 0;
    handle := Rectangle {
        x: orientation == Orientation.horizontal ? -value / max-scroll-pos * (root.width - handle-size) : 1px;
        y: orientation == Orientation.vertical ? -value / max-scroll-pos * (root.height - handle-size) : 1px;
        width: orientation == Orientation.vertical ? 6px : handle-size;
        height: orientation == Orientation.horizontal ? 6px : handle-size;
        background: UAppTheme.color-fill;
        border-radius: UAppTheme.radius-circle;
        animate background { duration: UAppTheme.animation-duration; }
        states [
            hover when touch.has-hover: {
                background: UAppTheme.color-fill-plus;
            }
        ]
    }

    touch := TouchArea {
        private property <length> initial-pressed;
        pointer-event(event) => {
            if event.button == PointerEventButton.left && event.kind == PointerEventKind.down {
                initial-pressed = orientation == Orientation.vertical ? self.mouse-y : self.mouse-x;
            }
        }
        moved => {
            if orientation == Orientation.vertical && self.mouse-y >= 0 && self.mouse-y <= root.height {
                let move-diff = initial-pressed - self.mouse-y;
                let new-y = clamp(handle.y - move-diff, 0px, available-space);
                initial-pressed = self.mouse-y;
                value = -(max-scroll-pos * (new-y / available-space));
            } else if orientation == Orientation.horizontal && self.mouse-x >= 0 && self.mouse-x <= root.width {
                let move-diff = initial-pressed - self.mouse-x;
                let new-x = clamp(handle.x - move-diff, 0px, available-space);
                initial-pressed = self.mouse-x;
                value = -(max-scroll-pos * (new-x / available-space));
            }
        }
    }
}

export component UScrollView inherits Rectangle {
    in-out property <bool> interactive: false;
    out property <length> scrollbar-area: 8px;
    in-out property <length> viewport-x <=> flickable.viewport-x;
    in-out property <length> viewport-y <=> flickable.viewport-y;
    in-out property <length> viewport-width <=> flickable.viewport-width;
    in-out property <length> viewport-height <=> flickable.viewport-height;
    private property <length> min-handle-size: 30px;
    private property <duration> scroll-anim-duration: !v-scrollbar.pressed && !h-scrollbar.pressed ? UAppTheme.animation-duration : 0;
    public function scroll-x-to(new-x: length) {
        self.viewport-x = new-x;
    }
    public function scroll-y-to(new-y: length) {
        self.viewport-y = new-y;
    }
    VerticalLayout {
        flickable := Flickable {
            horizontal-stretch: 2;
            vertical-stretch: 2;
            interactive: root.interactive;
            viewport-y <=> v-scrollbar.value;
            viewport-x <=> h-scrollbar.value;
            animate viewport-x, viewport-y { duration: scroll-anim-duration; }
            @children
        }
    }

    v-scrollbar := Scrollbar {
        property <length> raw-handle-size: flickable.height / flickable.viewport-height * self.height;
        y: 0;
        x: root.width - self.width;
        height: root.height - (h-scrollbar.visible ? h-scrollbar.height : 0);
        visible: flickable.viewport-height > flickable.height;
        max-scroll-pos: flickable.viewport-height - flickable.height;
        handle-size: raw-handle-size < min-handle-size ? min-handle-size : raw-handle-size;
    }

    h-scrollbar := Scrollbar {
        property <length> raw-handle-size: flickable.width / flickable.viewport-width * self.width;
        orientation: horizontal;
        x: 0;
        y: root.height - self.height;
        width: root.width - (v-scrollbar.visible ? v-scrollbar.width : 0);
        visible: flickable.viewport-width > flickable.width;
        max-scroll-pos: flickable.viewport-width - flickable.width;
        handle-size: raw-handle-size < min-handle-size ? min-handle-size : raw-handle-size;
    }
}
