import { UAppTheme } from "../app-theme.slint";

import { ButtonInterface } from "../utils/button-interface.slint";
import { USelectOption } from "../utils/structs.slint";

import { UPopover } from "popover.slint";
import { UText } from "text.slint";
import { UIcon } from "icon.slint";

import { ScrollView } from "std-widgets.slint";


export component USelect inherits ButtonInterface {
	// Accessability properties
	accessible-role: combobox;
    accessible-expandable: true;
    accessible-value: self.selected-text;
    accessible-item-count: self.options.length;
    accessible-action-default => {
        self.clicked();
    }
	// Theming properties
	in-out property <brush> t-background: transparent;
    in-out property <length> t-border-width: UAppTheme.border-width-base;
    in-out property <length> t-border-radius: UAppTheme.radius-base;
    in-out property <brush> t-border-color: UAppTheme.border;
    in-out property <brush> t-border-color-hover: UAppTheme.primary-hover;
    in-out property <brush> t-border-color-disabled: UAppTheme.border-secondary;
    in-out property <length> t-font-size: UAppTheme.font-size-base;
    in-out property <brush> t-text-color: UAppTheme.text;
    in-out property <brush> t-text-color-disabled: UAppTheme.text-disabled;
    in-out property <length> t-icon-size: UAppTheme.icon-size-base;
    in-out property <brush> t-icon-color: UAppTheme.border;
    in-out property <length> t-popup-max-height: 124px * UAppTheme.scale-factor;
    in-out property <length> t-option-height:29px * UAppTheme.scale-factor;
    in-out property <brush> t-option-bg-fill: UAppTheme.color-fill-tertiary;
    in-out property <brush> t-option-bg-selected: UAppTheme.primary-selected;
    in-out property <brush> t-option-text-selected-color: UAppTheme.primary;
    in-out property <brush> t-option-text-disabled-color: UAppTheme.text-disabled;
    in-out property <length> t-padding-vertical: UAppTheme.padding-vertical;
    in-out property <length> t-padding-horizontal: UAppTheme.padding-horizontal;
    in-out property <length> t-padding-popover: UAppTheme.padding-base;
	// Regular properties
    in-out property <int> current-index: -1;
    in-out property <[USelectOption]> options;
    private property <string> selected-text;
    private property <length> full-options-height: t-option-height * options.length + t-padding-popover * 2;
    callback selected-changed(new-index: int);
    background: t-background;
    border-width: self.has-focus ? UAppTheme.focus-border-width : t-border-width;
    border-color: self.has-focus ? UAppTheme.focus-color : t-border-color;
    border-radius: t-border-radius;
    clicked => {
        popup.show();
    }
    HorizontalLayout {
        alignment: space-between;
        spacing: UAppTheme.spacing-base;
        padding-top: t-padding-vertical;
        padding-bottom: t-padding-vertical;
        padding-left: t-padding-horizontal;
        padding-right: t-padding-horizontal;
        VerticalLayout {
            alignment: center;
            text-obj := UText {
                text: current-index != -1 ? options[current-index].text : "";
                overflow: elide;
                font-size: t-font-size;
                color: t-text-color;
            }
        }

        VerticalLayout {
            alignment: center;
            UIcon {
                source: @image-url("../assets/icons/chevron-up-down.svg");
                size: t-icon-size;
                colorize: t-icon-color;
            }
        }
    }

    popup := UPopover {
        close-policy: close-on-click-outside;
        width: root.width;
        height: root.full-options-height > t-popup-max-height ? t-popup-max-height : root.full-options-height;
        y: root.y + root.height + 1px;
        ScrollView {
            height: parent.height;
            list-contents := VerticalLayout {
                padding: t-padding-popover;
                for option[index] in root.options: select-item := Rectangle {
					// List item accessability
					accessible-role: list-item;
                    accessible-item-selectable: true;
                    accessible-item-selected: options[current-index].value == option.value;
                    accessible-value: option.text;
                    accessible-action-default => {
                        touch.clicked();
                    }
					// Item contents and properties.
					height: t-option-height;
                    border-radius: popup.t-border-radius;
                    width: 100%;
                    VerticalLayout {
                        alignment: center;
                        padding-left: t-padding-horizontal;
                        padding-right: t-padding-horizontal;
                        UText {
                            text: option.text;
                            font-size: t-font-size;
                            overflow: elide;
                            wrap: no-wrap;
                            states [
                                disabled when !option.enabled: {
                                    color: t-option-text-disabled-color;
                                }
                                selected when options[current-index].value == option.value: {
                                    color: t-option-text-selected-color;
                                }
                            ]
                        }
                    }

                    touch := TouchArea {
                        enabled: option.enabled;
                        mouse-cursor: pointer;
                        clicked => {
                            current-index = index;
                            selected-changed(index);
                            popup.close();
                        }
                    }

                    animate background { duration: 200ms; }
                    states [
                        selected when options[current-index].value == option.value && option.enabled: {
                            background: t-option-bg-selected;
                        }
                        hover when touch.has-hover && option.enabled: {
                            background: t-option-bg-fill;
                        }
                    ]
                }
            }
        }
    }

    states [
        disabled when !self.enabled: {
            border-color: t-border-color-disabled;
            text-obj.color: t-text-color-disabled;
        }
        hover when self.has-hover: {
            border-color: self.has-focus ? black : t-border-color-hover;
        }
    ]
}
