import { UAppTheme } from "../app-theme.slint";
import { ButtonInterface } from "button-interface.slint";
import { UPrimaryColors } from "../styling/colors.slint";


export component USlider inherits ButtonInterface {
	// Accessability properties
	accessible-role: slider;
    accessible-value: root.value;
    accessible-value-step: root.step;
    accessible-value-minimum: root.min-value;
    accessible-value-maximum: root.max-value;
    accessible-action-set-value(value) => {
        if value.is-float() {
            root.value = value.to-float();
        }
    }
    accessible-action-decrement => {
        root.value -= root.step
    }
    accessible-action-increment => {
        root.value += root.step
    }
	// Regular properties
    in-out property <float> value: 0;
    in-out property <float> step: 1;
    in-out property <float> min-value: 0;
    in-out property <float> max-value: 100;
    in-out property <Orientation> orientation: horizontal;
    changed value => {
        value = clamp(root.value, min-value, max-value);
    }
    function update-value() {
        let pos-value = orientation == Orientation.horizontal ? root.mouse-x : (root.height - root.mouse-y);
        let raw-value = pos-value * max-value / (orientation == Orientation.horizontal ? root.width : root.height);
        let value-diff = mod(raw-value, step);
        value = raw-value - value-diff;
    }
    clicked => {
        update-value();
    }
    moved => {
        update-value();
    }
    key-pressed(event) => {
        if event.text == Key.UpArrow {
            value = max-value;
            return EventResult.accept;
        } else if event.text == Key.DownArrow {
            value = min-value;
            return EventResult.accept;
        } else if event.text == Key.RightArrow {
            value += step;
            return EventResult.accept;
        } else if event.text == Key.LeftArrow {
            value -= step;
            return EventResult.accept;
        }
        return EventResult.reject;
    }
    width: 14px * UAppTheme.scale-factor;
    height: 14px * UAppTheme.scale-factor;
    if orientation == Orientation.horizontal: Rectangle {
        background: UAppTheme.color-fill-secondary;
        border-radius: UAppTheme.radius-circle;
        height: 5px * UAppTheme.scale-factor;
        HorizontalLayout {
            alignment: start;
            h-slider := Rectangle {
                property <int> curr-width: (value / 1px) * root.width / max-value;
                background: UAppTheme.primary.base;
                border-radius: UAppTheme.radius-circle;
                width: curr-width * 1px;
                animate background { duration: UAppTheme.animation-duration; }
                states [
                    disabled when !root.enabled: {
                        background: UAppTheme.color-fill;
                    }
                    focus when root.has-focus: {
                        background: UAppTheme.primary.hover;
                    }
                    hover when root.has-hover: {
                        background: UAppTheme.primary.hover;
                    }
                ]
            }
        }

        // Manage the aura-like border that appears around the handle.
        Rectangle {
            property <length> size: 14px * UAppTheme.scale-factor;
            x: h-slider.width - size / 2;
            border-radius: UAppTheme.radius-circle;
            width: size;
            height: size;
            animate size { duration: UAppTheme.animation-duration; }
            states [
                hover when root.enabled && (root.has-hover || root.has-focus): {
                    background: UAppTheme.primary.base.with-alpha(0.2);
                    size: 22px * UAppTheme.scale-factor;
                }
            ]
        }

        // The handle itself.
        Rectangle {
            property <length> size: 14px * UAppTheme.scale-factor;
            x: h-slider.width - size / 2;
            background: UAppTheme.bg-container;
            border-color: UAppTheme.primary.base;
            border-width: 2px * UAppTheme.scale-factor;
            border-radius: UAppTheme.radius-circle;
            width: size;
            height: size;
            animate border-color, size { duration: UAppTheme.animation-duration; }
            states [
                disabled when !root.enabled: {
                    border-color: UAppTheme.color-fill-plus;
                }
                hover when root.has-hover || root.has-focus: {
                    border-color: UAppTheme.primary.hover;
                    size: 18px * UAppTheme.scale-factor;
                }
            ]
        }
    }
    if orientation == Orientation.vertical: Rectangle {
        background: UAppTheme.color-fill-secondary;
        border-radius: UAppTheme.radius-circle;
        width: 5px * UAppTheme.scale-factor;
        VerticalLayout {
            alignment: end;
            v-slider := Rectangle {
                property <int> curr-height: (value / 1px) * root.height / max-value;
                background: UAppTheme.primary.base;
                border-radius: UAppTheme.radius-circle;
                height: curr-height * 1px;
                animate background { duration: UAppTheme.animation-duration; }
                states [
                    disabled when !root.enabled: {
                        background: UAppTheme.color-fill;
                    }
                    focus when root.has-focus: {
                        background: UAppTheme.primary.hover;
                    }
                    hover when root.has-hover: {
                        background: UAppTheme.primary.hover;
                    }
                ]
            }
        }

        // Manage the aura-like border that appears around the handle.
        Rectangle {
            property <length> size: 14px * UAppTheme.scale-factor;
            y: root.height - (v-slider.height + size / 2);
            border-radius: UAppTheme.radius-circle;
            width: size;
            height: size;
            animate size { duration: UAppTheme.animation-duration; }
            states [
                hover when root.has-hover || root.has-focus: {
                    background: UAppTheme.primary.base.with-alpha(0.2);
                    size: 22px * UAppTheme.scale-factor;
                }
            ]
        }

        // The handle itself.
        Rectangle {
            property <length> size: 14px * UAppTheme.scale-factor;
            y: root.height - (v-slider.height + size / 2);
            background: UAppTheme.bg-container;
            border-color: UAppTheme.primary.base;
            border-width: 2px * UAppTheme.scale-factor;
            border-radius: UAppTheme.radius-circle;
            width: size;
            height: size;
            animate border-color, size { duration: UAppTheme.animation-duration; }
            states [
                disabled when !root.enabled: {
                    border-color: UAppTheme.color-fill-plus;
                }
                hover when root.has-hover || root.has-focus: {
                    border-color: UAppTheme.primary.hover;
                    size: 18px * UAppTheme.scale-factor;
                }
            ]
        }
    }
}
