import { UAppTheme } from "../app-theme.slint";


export component USpinner inherits Image {
    accessible-role: image;
    accessible-label: @tr("Loading spinner.");
	// Theming properties
    in-out property <brush> t-color: UAppTheme.primary;
    in-out property <angle> t-rotation-speed: 240deg;
    in-out property <length> size: UAppTheme.icon-size-base;
    colorize: t-color;
    width: size;
    height: size;
    source: @image-url("../assets/icons/loader-circle.svg");
    rotation-angle: t-rotation-speed * animation-tick() / 1s;
    animate rotation-angle {
        easing: ease-in-out;
        iteration-count: -1;
    }
}
