import { UAppTheme } from "../app-theme.slint";


export component USpinner inherits Image {
    in-out property <length> size: UAppTheme.icon-size-base;
    accessible-role: image;
    accessible-label: @tr("Loading spinner.");
    colorize: UAppTheme.primary.base;
    width: size;
    height: size;
    source: @image-url("../assets/icons/loader-circle.svg");
    transform-rotation: 240deg * animation-tick() / 1s;
	// Used to apply the transform rotation, otherwise the "transform-rotation" warning will be fired and it won't be applied.
    animate transform-rotation { }
}
