import { UAppTheme } from "../app-theme.slint";
import { UText } from "text.slint";
import { UDivider } from "divider.slint";
import { ButtonInterface } from "button-interface.slint";


export enum UTabsAlignment {
    start,
    stretch,
}

export component UTabs inherits Rectangle {
    accessible-role: tab-list;
	// Regular properties
    in property <[string]> tabs;
    in-out property <int> current-index: 0;
    in property <UTabsAlignment> tabs-alignment: stretch;
    private property <length> underline-x: 0px;
    private property <length> underline-width: 0px;
    VerticalLayout {
        alignment: start;
        HorizontalLayout {
            alignment: tabs-alignment == start ? start : stretch;
            padding-bottom: UAppTheme.padding-base;
            for tab[idx] in tabs: ButtonInterface {
                accessible-role: AccessibleRole.tab;
                accessible-label: tab;
                property <bool> is-current: current-index == idx;
                function update-underline() {
                    if is-current {
                        underline-x = self.x;
                        underline-width = self.width;
                    }
                }
                changed is-current => { update-underline() }
                changed x => { update-underline() }
                changed width => { update-underline() }
                // Used to render the underline for the first time.
				init => {
                    update-underline();
                }
                clicked => {
                    current-index = idx;
                    underline-x = self.x;
                    underline-width = self.width;
                }
                border-color: UAppTheme.focus-color;
                border-width: self.has-tab-focus ? UAppTheme.focus-border-width : 0px;
                border-radius: UAppTheme.radius-base;
                HorizontalLayout {
                    alignment: center;
                    padding-top: UAppTheme.padding-vertical;
                    padding-bottom: UAppTheme.padding-vertical;
                    padding-left: UAppTheme.padding-horizontal;
                    padding-right: UAppTheme.padding-horizontal;
                    tab-text := UText {
                        text: tab;
                        font-size: UAppTheme.font-size-base;
                        color: current-index == idx ? UAppTheme.primary.base : UAppTheme.text;
                        animate color { duration: UAppTheme.animation-duration; }
                    }
                }

                states [
                    pressed when self.pressed: {
                        tab-text.color: UAppTheme.primary.base;
                    }
                    hover when self.has-hover && !is-current: {
                        tab-text.color: UAppTheme.primary.hover;
                    }
                ]
            }
        }

        Rectangle {
            height: 2px;
            UDivider { }

            Rectangle {
                width: underline-width;
                height: 2px;
                x: underline-x;
                background: UAppTheme.primary.base;
                animate x, width { duration: UAppTheme.animation-duration; }
            }
        }

        VerticalLayout {
            accessible-role: tab-panel;
            padding-top: UAppTheme.spacing-bigger;
            @children
        }
    }
}
