import { UAppTheme } from "../app-theme.slint";
import { UText } from "text.slint";
import { UDivider } from "divider.slint";
import { UIcon } from "icon.slint";
import { ButtonInterface } from "button-interface.slint";
import { IconTextPlacement } from "common/enums.slint";


export enum UTabsAlignment {
    start,
    stretch,
}


export struct UTabData {
    title: string,
    icon: image,
    icon-placement: IconTextPlacement = IconTextPlacement.hidden,
}

component TabIcon inherits UIcon {
    in property <image> icon;
    in property <bool> is-current;
    in property <bool> pressed;
    in property <bool> has-hover;
    source: icon;
    animate colorize { duration: UAppTheme.animation-duration; }
    states [
        current when is-current: {
            colorize: UAppTheme.primary.base;
        }
        pressed when pressed: {
            colorize: UAppTheme.primary.base;
        }
        hover when has-hover: {
            colorize: UAppTheme.primary.hover;
        }
    ]
}


export component UTabs inherits Rectangle {
    accessible-role: tab-list;
    accessible-item-count: tabs.length;
	// Regular properties
    in property <[UTabData]> tabs;
    in-out property <int> current-index: 0;
    in property <UTabsAlignment> tabs-alignment: stretch;
    private property <length> underline-x: 0px;
    private property <length> underline-width: 0px;
    VerticalLayout {
        alignment: start;
        HorizontalLayout {
            alignment: tabs-alignment == start ? start : stretch;
            padding-bottom: UAppTheme.padding-base;
            for tab[idx] in tabs: tab-btn := ButtonInterface {
                accessible-role: AccessibleRole.tab;
                accessible-label: tab.title;
                accessible-item-index: idx;
                accessible-item-selectable: true;
                accessible-item-selected: is-current;
                property <bool> is-current: current-index == idx;
                function update-underline() {
                    if is-current {
                        underline-x = self.x;
                        underline-width = self.width;
                    }
                }
                changed is-current => { update-underline() }
                changed x => { update-underline() }
                changed width => { update-underline() }
                // Used to render the underline for the first time.
				init => {
                    update-underline();
                }
                clicked => {
                    current-index = idx;
                    update-underline();
                }
                border-color: UAppTheme.focus-color;
                border-width: self.has-tab-focus ? UAppTheme.focus-border-width : 0px;
                border-radius: UAppTheme.radius-base;
                HorizontalLayout {
                    alignment: center;
                    cross-axis-alignment: center;
                    spacing: UAppTheme.spacing-base;
                    padding-top: UAppTheme.padding-vertical;
                    padding-bottom: UAppTheme.padding-vertical;
                    padding-left: UAppTheme.padding-horizontal;
                    padding-right: UAppTheme.padding-horizontal;
                    if tab.icon-placement == IconTextPlacement.start: TabIcon {
                        source: tab.icon;
                        is-current: is-current;
                        pressed: tab-btn.pressed;
                        has-hover: tab-btn.has-hover;
                    }

                    UText {
                        text: tab.title;
                        font-size: UAppTheme.font-size-base;
                        animate color { duration: UAppTheme.animation-duration; }
                        states [
                            current when tab-btn.is-current: {
                                color: UAppTheme.primary.base;
                            }
                            pressed when tab-btn.pressed: {
                                color: UAppTheme.primary.base;
                            }
                            hover when tab-btn.has-hover: {
                                color: UAppTheme.primary.hover;
                            }
                        ]
                    }

                    if tab.icon-placement == IconTextPlacement.end: TabIcon {
                        source: tab.icon;
                        is-current: is-current;
                        pressed: tab-btn.pressed;
                        has-hover: tab-btn.has-hover;
                    }
                }
            }
        }

        Rectangle {
            height: 2px;
            UDivider { }

            Rectangle {
                width: underline-width;
                height: 2px;
                x: underline-x;
                background: UAppTheme.primary.base;
                animate x, width { duration: UAppTheme.animation-duration; }
            }
        }

        VerticalLayout {
            accessible-role: tab-panel;
            padding-top: UAppTheme.spacing-bigger;
            @children
        }
    }
}
