import { UAppTheme } from "../app-theme.slint";

export component UTitle inherits Text {
	// Accessability properties
	accessible-role: text;
    accessible-value: self.text;
	// Regular properties
	property <length> t-font-size: 36px;
    in-out property <int> level: 1;
    color: UAppTheme.text;
    font-size: t-font-size * UAppTheme.scale-factor;
    font-weight: {
        if level == 1 {
            return 600;
        } else if level == 5 {
            return 500;
        }
        return 400;
    };
    init => {
        if level == 1 {
            self.t-font-size = 36px;
        } else if level == 2 {
            self.t-font-size = 30px;
        } else if level == 3 {
            self.t-font-size = 24px;
        } else if level == 4 {
            self.t-font-size = 20px;
        } else if level == 5 {
            self.t-font-size = 18px;
        } else if level == 6 {
            self.t-font-size = 16px;
        }
    }
}
