import { UAppTheme } from "../app-theme.slint";

export component UTitle inherits Text {
	// Accessability properties
	accessible-role: text;
    accessible-value: self.text;
	// Regular properties
	in-out property <int> level: 1;
    color: UAppTheme.text;
    font-size: 36px * UAppTheme.scale-factor;
    font-weight: 600;
    init => {
        if level == 1 {
            self.font-size = 36px * UAppTheme.scale-factor;
            self.font-weight = 600;
        } else if level == 2 {
            self.font-size = 30px * UAppTheme.scale-factor;
            self.font-weight = 500;
        } else if level == 3 {
            self.font-size = 24px * UAppTheme.scale-factor;
        } else if level == 4 {
            self.font-size = 20px * UAppTheme.scale-factor;
        } else if level == 5 {
            self.font-size = 18px * UAppTheme.scale-factor;
        } else if level == 6 {
            self.font-size = 16px * UAppTheme.scale-factor;
        }
    }
}
