export struct SlintDocPageStyledText {
	text: string,
	code: string,
	link: string,
	url: string,
	local: bool,
}

export struct SlintDocPageSection {
	title: string,
	description: [[SlintDocPageStyledText]],
	widget-id: string,
	// This allows a widget presentation to have multiple variants 
	// instead of having a widget presentation per variant.
	widget-variant: string,
	code: string,
}

export struct SlintDocPage {
	title: string,
	description: string,
	sections: [SlintDocPageSection]
}