import { AppTheme } from "app-themes/app-theme-struct.slint";
import { DaybreakBlueTheme } from "app-themes/daybreak-blue.slint";
import { Palette } from "std-widgets.slint";

export global UAppTheme {
    in-out property <AppTheme> light-theme: DaybreakBlueTheme.light-theme;
    in-out property <AppTheme> dark-theme: DaybreakBlueTheme.dark-theme;
    in-out property <AppTheme> theme: Palette.color-scheme == ColorScheme.dark ? dark-theme : light-theme;
    in-out property <float> scale-factor: 1;

    // Primary color.
    in-out property <color> primary: theme.primary;
    in-out property <color> primary-hover: theme.primary-hover;
    in-out property <color> primary-active: theme.primary-active;
    in-out property <color> primary-disabled: theme.primary-disabled;
    in-out property <color> primary-selected: theme.primary-selected;

    // Success color.
    in-out property <color> success: theme.success;
    in-out property <color> success-hover: theme.success-hover;
    in-out property <color> success-active: theme.success-active;
    in-out property <color> success-disabled: theme.success-disabled;
    in-out property <color> success-selected: theme.success-selected;

    // Warning color.
    in-out property <color> warning: theme.warning;
    in-out property <color> warning-hover: theme.warning-hover;
    in-out property <color> warning-active: theme.warning-active;
    in-out property <color> warning-disabled: theme.warning-disabled;
    in-out property <color> warning-selected: theme.warning-selected;

    // Danger color.
    in-out property <color> danger: theme.danger;
    in-out property <color> danger-hover: theme.danger-hover;
    in-out property <color> danger-active: theme.danger-active;
    in-out property <color> danger-disabled: theme.danger-disabled;
    in-out property <color> danger-selected: theme.danger-selected;
	
	// Background color
    in-out property <color> bg-container: theme.bg-container;
    in-out property <color> bg-elevated: theme.bg-elevated;
    in-out property <color> bg-layout: theme.bg-layout;
    in-out property <color> bg-inverse: theme.bg-inverse;

	// Color fill
    in-out property <color> color-fill-plus: theme.color-fill-plus;
    in-out property <color> color-fill: theme.color-fill;
    in-out property <color> color-fill-secondary: theme.color-fill-secondary;
    in-out property <color> color-fill-tertiary: theme.color-fill-tertiary;
    in-out property <color> color-fill-quaternary: theme.color-fill-quaternary;
	
    // Shadow
    in-out property <color> shadow-color: theme.shadow-color;
    in-out property <length> shadow-blur: theme.shadow-blur * scale-factor;
    in-out property <length> shadow-x-offset: theme.shadow-x-offset * scale-factor;
    in-out property <length> shadow-y-offset: theme.shadow-y-offset * scale-factor;

	// Text color
    in-out property <color> inverse-text: theme.inverse-text;
    in-out property <color> text: theme.text;
    in-out property <color> text-secondary: theme.text-secondary;
    in-out property <color> text-heading: theme.text-heading;
    in-out property <color> text-disabled: theme.text-disabled;

    // Font size
    in-out property <length> font-size-smaller: theme.font-size-smaller * scale-factor;
    in-out property <length> font-size-small: theme.font-size-small * scale-factor;
    in-out property <length> font-size-base: theme.font-size-base * scale-factor;
    in-out property <length> font-size-medium: theme.font-size-medium * scale-factor;
    in-out property <length> font-size-big: theme.font-size-big * scale-factor;
    in-out property <length> font-size-bigger: theme.font-size-bigger * scale-factor;

	// Focus display
    in-out property <color> focus-color: theme.focus-color;
    in-out property <length> focus-border-width: theme.focus-border-width * scale-factor;

    // Borders
	in-out property <length> border-width-base: theme.border-width-base * scale-factor;
    in-out property <color> border: theme.border;
    in-out property <color> border-secondary: theme.border-secondary;
    in-out property <color> separator: theme.separator;

    // Icons
    in-out property <length> icon-size-base: theme.icon-size-base * scale-factor;

    // Padding
    in-out property <length> padding-vertical: theme.padding-vertical * scale-factor;
    in-out property <length> padding-horizontal: theme.padding-horizontal * scale-factor;
    in-out property <length> padding-small: theme.padding-small * scale-factor;
    in-out property <length> padding-base: theme.padding-base * scale-factor;
    in-out property <length> padding-medium: theme.padding-medium * scale-factor;
    in-out property <length> padding-big: theme.padding-big * scale-factor;
    in-out property <length> padding-bigger: theme.padding-bigger * scale-factor;

    // Spacing
    in-out property <length> spacing-small: theme.spacing-small * scale-factor;
    in-out property <length> spacing-base: theme.spacing-base * scale-factor;
    in-out property <length> spacing-medium: theme.spacing-medium * scale-factor;
    in-out property <length> spacing-big: theme.spacing-big * scale-factor;
    in-out property <length> spacing-bigger: theme.spacing-bigger * scale-factor;

    // Radius
    in-out property <length> radius-base: theme.radius-base * scale-factor;
    in-out property <length> radius-small: theme.radius-small * scale-factor;
    in-out property <length> radius-medium: theme.radius-medium * scale-factor;
    in-out property <length> radius-large: theme.radius-large * scale-factor;
    in-out property <length> radius-round: theme.radius-round * scale-factor;
    in-out property <length> radius-circle: theme.radius-circle;
}
